const normalize=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[.!]+$/,'').trim();
/** Only an explicit approval applies the last visible proposal; questions never do. */
export function approvesAssistantProposal(text:string){
 return /^(?:(?:sim|ok|certo|beleza),?\s+)?(?:pode (?:aplicar|preencher|colocar|atualizar|publicar|programar)|aplique|aplicar|confirmo|autorizo)(?: (?:isso|a sugestao|essa sugestao|as alteracoes|essas alteracoes|os campos|o texto|no texto|nos campos|no formulario))?$/.test(normalize(text));
}
export function requestsTechnicalReview(message:string,label:string){
 return /relato|tecnic|ocorrencia/i.test(normalize(label))&&/tudo (?:certo|correto|ok)|(?:esta|ta) (?:certo|correto|bom)|revis|referencia|valid|adequad|bem descrit|linguagem tecnic/.test(normalize(message));
}
export const technicalReviewPolicy='REVISÃO DO RELATO: avalie separadamente clareza da redação, completude da observação e fundamentação documental. Uma descrição curta não prova completude nem correção técnica. Para "Altímetro / intermitente em voo", proponha "Indicação intermitente do altímetro durante o voo", preservando somente os fatos; pergunte qual indicação/instrumento e como a intermitência se manifesta, uma pergunta por vez. Não atribua causa, diagnóstico ou teste. Consulte a biblioteca para a referência pertinente e cite de forma curta documento/seção SOMENTE quando encontrado e aplicabilidade demonstrada. Um documento público genérico não é o AMM/FIM aprovado nem valida este relato. Se faltar referência aplicável, diga isso diretamente e peça a referência/documento do operador; jamais preencha AMM/FIM/página por memória. A observação pode ser registrada mesmo sem referência; não a trate como procedimento executado. Não aprove tecnicamente apenas porque a ortografia está correta. Uma revisão deve apresentar a sugestão e aguardar "pode aplicar"; não use preparar_campos para certificar conformidade.';
