export type CockpitKind='person'|'qualification'|'location'|'contract'|'settings'|'preparation'|'document'|'diary'|'counter'|'occurrence'|'duty';
export type CockpitData=Record<string,string|number|null|{actor:string;at:string;revision:number}>;
export type CockpitEntry={id:string;kind:CockpitKind;subject:string|null;flight_id:string|null;data:CockpitData;revision:number;created_by:string;updated_by:string;updated_at:string};
export type CockpitField={key:string;label:string;type?:'number'|'date'|'datetime-local'|'textarea'|'url';options?:string[]};
const field=(key:string,label:string,type?:CockpitField['type'],options?:string[]):CockpitField=>({key,label,type,options});
export const cockpitFields:Record<CockpitKind,CockpitField[]>={
 person:[field('regime','Regime de escala',undefined,['Missão','Mensalista']),field('externalEmployeeId','Identificador do tripulante no eDB'),field('ruleReference','Manual / acordo / apêndice RBAC 117 aplicável'),field('historyFrom','Histórico conferido desde','date'),field('flightDaily','Limite de voo por jornada validado (min)','number'),field('flightMonthly','Limite mensal de voo validado (min)','number'),field('flightYearly','Limite anual de voo validado (min)','number'),field('dutyMonthly','Limite mensal de jornada validado (min)','number'),field('mealRule','Apuração de refeição',undefined,['A validar','Excluir intervalo registrado da jornada','Manter intervalo na jornada']),field('reviewer','Responsável pela validação das regras'),field('reviewDate','Data da validação','date')],
 qualification:[field('category','Categoria',undefined,['Habilitação','Certificado','CMA','Designação','Treinamento','Outro vencimento']),field('title','Nome / item'),field('code','Código / número'),field('fleet','Frota'),field('qualificationType','Tipo / designação'),field('issued','Emissão / data da designação','date'),field('expires','Vencimento / validade','date'),field('documentUrl','Link do documento','url'),field('notes','Observações','textarea')],
 location:[field('title','Base / aeródromo / heliponto'),field('icao','Sigla ICAO'),field('latitude','Latitude decimal'),field('longitude','Longitude decimal'),field('timezone','Fuso IANA (ex.: America/Sao_Paulo)'),field('source','Fonte de referência'),field('verifiedAt','Conferido em','datetime-local'),field('sunrise','Nascer do sol · referência com data','datetime-local'),field('sunset','Pôr do sol · referência com data','datetime-local'),field('nextSunrise','Próximo nascer do sol · referência com data','datetime-local')],
 contract:[field('title','Contrato'),field('code','Código do contrato'),field('client','Cliente'),field('base','Base'),field('validUntil','Validade','date'),field('notes','Observações','textarea')],
 settings:[field('title','Fornecedor do eDB · a confirmar'),field('systemName','Nome do sistema (ex.: Sigtrip)'),field('portalUrl','Endereço do Logbook oficial','url'),field('supportContact','Contato da TI / suporte do fornecedor'),field('apiDocumentationUrl','Documentação da API','url'),field('sandboxUrl','Endereço do ambiente de testes','url'),field('authenticationMethod','Método de autenticação · somente descrição, sem senhas ou chaves'),field('externalOperatorId','Identificador do operador'),field('mappingNotes','Correspondência de IDs: aeronaves, matrículas, voos e diários','textarea'),field('syncRequirements','Regras de envio, retorno e correções no eDB','textarea'),field('reference','Referência do manual operacional'),field('notes','Pendências / observações · integração ainda não conectada','textarea')],
 preparation:[field('flightNumber','Número do voo'),field('contract','Contrato / cliente'),field('route','Rota / trechos'),field('originIcao','Origem ICAO'),field('destinationIcao','Destino ICAO'),field('alternate','Alternado'),field('plannedFuel','Combustível planejado','number'),field('alternateFuel','Combustível para alternado','number'),field('reserveFuel','Reserva de combustível','number'),field('fuelUnit','Unidade',undefined,['kg','lb','L']),field('passengers','Passageiros','number'),field('cargoKg','Carga (kg)','number'),field('conditions','Condições da rota / planejamento','textarea'),field('notes','Observações','textarea')],
 document:[field('title','Documento'),field('documentUrl','Link para visualizar / baixar','url'),field('requiresSignature','Requer assinatura no eDB',undefined,['Não','Sim']),field('status','Conferência local',undefined,['Pendente','Conferido']),field('externalId','Referência do documento no eDB'),field('notes','Observações','textarea')],
 diary:[field('title','Identificação do diário'),field('externalId','Identificador do diário no eDB'),field('externalUrl','Link do diário oficial','url'),field('cycle','Ciclo / página / sequência'),field('fuelCheck','Fuel Check · referência / observação','textarea'),field('bff','BFF · referência / observação','textarea'),field('deferred','Itens diferidos · referência oficial, condição e prazo','textarea'),field('releaseReference','Airworthiness Release · referência oficial'),field('pending','Pendências / observações para o comandante','textarea')],
 counter:[field('title','Contador'),field('equipment','Motor / equipamento / número de série'),field('externalId','Identificador no eDB'),field('unit','Unidade',undefined,['Horas decimais','Minutos','Ciclos','Acionamentos','Outro']),field('previous','Valor anterior','number'),field('current','Valor atual / total acumulado','number'),field('source','Origem dos valores'),field('correctionReason','Motivo da correção / troca','textarea')],
 occurrence:[field('title','Título'),field('occurrenceType','Tipo de ocorrência'),field('leg','Trecho do voo'),field('at','Data e hora','datetime-local'),field('location','Local'),field('latitude','Latitude decimal'),field('longitude','Longitude decimal'),field('system','Sistema'),field('crew','Tripulação envolvida'),field('description','Descrição / observações','textarea'),field('technicalType','Relato técnico para avaliação',undefined,['discrepancy']),field('priority','Prioridade do acompanhamento',undefined,['routine','urgent'])],
 duty:[field('date','Data da jornada','date'),field('origin','Origem'),field('destination','Destino'),field('presentation','Apresentação efetiva','datetime-local'),field('mealStart','Início da refeição','datetime-local'),field('mealEnd','Término da refeição','datetime-local'),field('release','Liberação','datetime-local'),field('flightMinutes','Total de voo conferido (minutos)','number'),field('nightMinutes','Voo noturno conferido (minutos)','number'),field('nightBasis','Critério usado para voo noturno'),field('source','Origem dos horários / referência FIRA'),field('notes','Observações / motivo da correção','textarea')]
};
export const cockpitLabels:Record<CockpitKind,string>={person:'Regras e escala',qualification:'Licenças e certificados',location:'Bases / AIS',contract:'Contratos',settings:'Integração eDB',preparation:'Preparação do voo',document:'Documento',diary:'Diário · preparação eDB',counter:'Contador especial',occurrence:'Ocorrência',duty:'Jornada / papeleta'};
export const valueOf=(data:CockpitData,key:string)=>typeof data[key]==='string'||typeof data[key]==='number'?String(data[key]):'';
export const cockpitDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function dateInput(value:string){if(!value)return '';const date=new Date(value);if(!Number.isFinite(date.getTime()))return '';const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
export function safeLink(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
export function dutyTotals(rows:CockpitEntry[],date:string,person:CockpitData){
 const end=new Date(`${date}T12:00:00Z`);const cutoff=(days:number)=>{const d=new Date(end);d.setUTCDate(d.getUTCDate()-(days-1));return d.toISOString().slice(0,10);};
 const duties=rows.filter(r=>r.kind==='duty'&&valueOf(r.data,'date')<=date);
 const sum=(match:(day:string)=>boolean,key:string)=>{const eligible=duties.filter(r=>match(valueOf(r.data,'date')));return {minutes:eligible.reduce((n,r)=>n+Number(valueOf(r.data,key)||0),0),incomplete:eligible.some(r=>valueOf(r.data,key)==='')};};
 const month=date.slice(0,7),year=date.slice(0,4);
 return [
  {label:'Dia',from:date,limit:'flightDaily',...sum(d=>d===date,'flightMinutes')},
  {label:'Mês',from:month+'-01',limit:'flightMonthly',...sum(d=>d.startsWith(month),'flightMinutes')},
  {label:'Ano',from:year+'-01-01',limit:'flightYearly',...sum(d=>d.startsWith(year),'flightMinutes')},
  {label:'Últimos 30 dias',from:cutoff(30),limit:'',...sum(d=>d>=cutoff(30),'flightMinutes')},
  {label:'Últimos 90 dias',from:cutoff(90),limit:'',...sum(d=>d>=cutoff(90),'flightMinutes')}
 ].map(total=>{const limit=valueOf(person,total.limit);const complete=!total.incomplete&&valueOf(person,'historyFrom')!==''&&valueOf(person,'historyFrom')<=total.from;const validated=Boolean(valueOf(person,'reviewer')&&valueOf(person,'reviewDate')&&valueOf(person,'ruleReference'));return {...total,remaining:limit&&complete&&validated?Number(limit)-total.minutes:null};});
}
