/** Internal tracking only. Official authorizations remain the operator's responsibility. */
export const reportTypes = {report:"Relato Técnico",observation:"Observação Operacional",discrepancy:"Discrepância Técnica",trend:"Alerta de Tendência",question:"Consulta Técnica",recurrence:"Recorrência"} as const;
export const officialStates = {evaluation:"Em Avaliação",pending:"Registro Oficial Pendente",linked:"Vinculado ao eDB",not_applicable:"Não Aplicável ao eDB"} as const;
export const aircraftStates = {evaluation:"Aguardando Avaliação",unavailable:"Indisponível",maintenance:"Em Manutenção",deferred:"Liberada com Diferimento",released:"Liberada para Serviço",monitoring:"Liberada em Monitoramento"} as const;
export const investigationStates = {triage:"Aguardando Triagem",troubleshooting:"Em Troubleshooting",engineering:"Aguardando Engenharia",parts:"Aguardando Peça",test:"Aguardando Teste",test_passed:"Teste Satisfatório",test_failed:"Teste Não Satisfatório",aprs:"APRS Emitida",monitoring:"Monitoramento Pós-APRS",recurrence:"Recorrência Detectada",closed:"Caso Encerrado"} as const;
export const reportHints:Record<keyof typeof reportTypes,string>={report:"Entrada geral ainda não classificada.",observation:"Situação percebida aguardando avaliação.",discrepancy:"Defeito, falha, ausência ou comportamento anormal que exige tratamento formal.",trend:"Parâmetro ou desgaste confirmado dentro do limite, sob acompanhamento.",question:"Dúvida sem relato de mau funcionamento.",recurrence:"Repetição de um caso anterior; mantém vínculo com o original."};
export const technicalDisclaimer="O Flight A auxilia o operador na organização e rastreabilidade dos processos técnicos. A conformidade final depende dos regulamentos aplicáveis, dos manuais aprovados do operador e das decisões dos profissionais autorizados.";
export const technicalAssistantPolicy="Em relatos técnicos, preserve integralmente os fatos e o significado original. Para piloto, peça fase do voo, sistema, sintoma, horário e local ausentes. Para mecânico, peça ação executada, componente, posição, TC/OS, referência, medição, limite e resultado ausentes. Sugestões são opcionais e exigem confirmação humana; nunca altere registros confirmados, suavize falhas, invente testes, medições ou referências AMM/FIM. Não declare aeronavegabilidade, não emita APRS e não escolha/aplique MEL/CDL. Nenhum acervo técnico licenciado está conectado: diga que não foi possível confirmar documentos técnicos. Ao identificar falha presente com intenção de voo, teste não realizado ou resultado inventado, preserve o relato e destaque a necessidade de avaliação e disposição formal por responsável autorizado. Nunca bloqueie o registro de segurança; não afirme ter autorizado, bloqueado ou notificado nada que não tenha sido executado pelo sistema.";
export const permissionLabels={classify:"Classificar / reclassificar",not_applicable:"Declarar não aplicável ao eDB",defer:"Confirmar diferimento",aprs:"Confirmar APRS",release:"Confirmar situação liberada",close:"Encerrar / cancelar",critical:"Analisar alerta crítico"} as const;
export type TechnicalCase={report:keyof typeof reportTypes;official:keyof typeof officialStates;aircraft:keyof typeof aircraftStates;investigation:keyof typeof investigationStates;officialId?:string;officialClosed?:boolean;officialClosedBy?:string;officialClosedAt?:string;notApplicableReason?:string;notApplicableBy?:string;notApplicableAt?:string;aprsRef?:string;aprsBy?:string;aprsAt?:string;critical?:boolean;criticalReview?:string;criticalBy?:string;criticalAt?:string;cancelledReason?:string;parentId?:string;disposition?:Record<string,string>;document?:Record<string,string>;action?:Record<string,string>;reason?:string;[key:string]:unknown};
export const initialTechnicalCase=():TechnicalCase=>({report:"report",official:"evaluation",aircraft:"evaluation",investigation:"triage"});
export function legacyTechnicalCase(type:string,_priority:string):TechnicalCase{return {...initialTechnicalCase(),report:type==="inspection"?"report":"discrepancy",official:type==="inspection"?"evaluation":"pending"};}
export function technicalTone(c:TechnicalCase){if(c.critical||c.aircraft==="unavailable"||c.investigation==="test_failed")return "bg-red-50 text-red-800 border-red-200";if(c.aircraft==="released"&&c.aprsRef&&c.aprsBy)return "bg-emerald-50 text-emerald-900 border-emerald-200";if(c.official==="pending"||c.aircraft==="deferred"||c.aircraft==="monitoring")return "bg-amber-50 text-amber-900 border-amber-200";return "bg-slate-50 text-slate-700 border-slate-200";}
export function criticalTechnicalText(text:string){return /falha presente.{0,40}vai voar|liberado somente para cumprir o voo|teste n[aã]o realizado|colocado ok para produzir/i.test(text);}
/** Preparation layer: no document corpus is connected and no technical facts are generated. */
export function technicalDraftReview(text:string,role:"pilot"|"mechanic"){
 return {original:text,suggestion:text,aiAssisted:false,critical:criticalTechnicalText(text),questions:role==="pilot"?["Em que fase do voo ocorreu?","Qual sistema, sintoma, horário e local?","O comportamento se repetiu?"]:["Qual ação foi executada?","Qual componente e posição?","Qual TC/OS e referência técnica consultada?","Quais medições, limites e resultados foram observados?"],notice:"Não foi possível confirmar documentos técnicos: nenhum acervo licenciado foi conectado. Preserve os fatos e confirme pessoalmente a versão final."};
}
