begin;
do $test$
declare adm uuid; pilot uuid; other uuid; employee text; other_employee text; f jsonb; r jsonb; payload jsonb; blocked boolean; prefix text; code text;
begin
 select d.auth_user_id into adm from public.device_identities d join public.authorized_users u using(employee_number) where d.is_admin and u.active limit 1;
 select d.auth_user_id,d.employee_number into pilot,employee from public.device_identities d join public.authorized_users u using(employee_number) where u.active and u.job_role='commander' limit 1;
 select d.auth_user_id,d.employee_number into other,other_employee from public.device_identities d join public.authorized_users u using(employee_number) where u.active and u.job_role='mechanic' limit 1;
 if adm is null or pilot is null or other is null then raise exception 'Fixture missing';end if;
 select x->>'prefix' into prefix from public.shared_app_state s cross join lateral jsonb_array_elements(s.catalogs->'aircraft') x where s.id='main' limit 1;
 f:=jsonb_build_object('id','00000000-0000-4000-8000-000000009999','prefix',prefix,'date','2026-09-08','departure','08:00','commander',employee);
 perform set_config('request.jwt.claim.sub',adm::text,true);
 update public.shared_app_state set flights=flights||jsonb_build_array(f) where id='main';
 perform public.cockpit('save',jsonb_build_object('id','qa-qualification','kind','qualification','subject',employee,'data',jsonb_build_object('title','QA licença')));
 perform set_config('request.jwt.claim.sub',pilot::text,true);
 if not exists(select 1 from jsonb_array_elements(public.cockpit('list')) x where x->>'id'='qa-qualification') then raise exception 'Own qualification hidden';end if;
 blocked:=false;begin perform public.cockpit('save',jsonb_build_object('id','qa-intrusion','kind','qualification','subject',employee,'data','{}'::jsonb));exception when others then blocked:=true;end;if not blocked then raise exception 'Pilot changed qualifications';end if;
 payload:=jsonb_build_object('id','qa-prep','kind','preparation','flightId',f->>'id','data',jsonb_build_object('contract','QA','externalStatus','synced'));
 r:=public.cockpit('save',payload);
 if r#>>'{data,externalStatus}'<>'not_connected' then raise exception 'Forged sync';end if;
 blocked:=false;begin perform public.cockpit('save',payload);exception when others then blocked:=true;end;if not blocked then raise exception 'Stale write allowed';end if;
 perform set_config('request.jwt.claim.sub',other::text,true);
 if exists(select 1 from jsonb_array_elements(public.cockpit('list')) x where x->>'id' in ('qa-prep','qa-qualification')) then raise exception 'Other crew data leaked';end if;
 blocked:=false;begin perform public.cockpit('save',payload||jsonb_build_object('revision',1));exception when others then blocked:=true;end;if not blocked then raise exception 'Unassigned crew changed flight';end if;
 blocked:=false;begin perform public.cockpit('export',jsonb_build_object('flightId',f->>'id'));exception when others then blocked:=true;end;if not blocked then raise exception 'Unassigned export';end if;
 perform set_config('request.jwt.claim.sub',pilot::text,true);
 payload:=jsonb_build_object('id','qa-duty','kind','duty','subject',employee,'data',jsonb_build_object('date','2026-09-08','presentation','2026-09-08T10:00:00Z','release','2026-09-08T20:00:00Z','mealStart','2026-09-08T15:00:00Z','mealEnd','2026-09-08T16:00:00Z','flightMinutes','120','nightMinutes','30'));
 r:=public.cockpit('save',payload);
 if r#>>'{data,elapsedMinutes}'<>'600' or r#>>'{data,mealMinutes}'<>'60' then raise exception 'Duty calculation incorrect';end if;
 blocked:=false;begin perform public.cockpit('save',payload||jsonb_build_object('id','qa-duty-bad','data',(payload->'data')||'{"nightMinutes":"200"}'::jsonb));exception when others then blocked:=true;end;if not blocked then raise exception 'Night exceeds flight';end if;
 r:=public.cockpit('save',jsonb_build_object('id','qa-counter','kind','counter','flightId',f->>'id','data',jsonb_build_object('previous','100','current','103.5')));
 if r#>>'{data,delta}'<>'3.5' then raise exception 'Counter delta incorrect';end if;
 r:=public.cockpit('save',jsonb_build_object('id','qa-diary','kind','diary','flightId',f->>'id','data','{}'::jsonb));
 r:=public.cockpit('prepare_export','{"id":"qa-diary","revision":1}');
 blocked:=false;begin perform public.cockpit('save','{"id":"qa-diary","revision":2,"data":{}}');exception when others then blocked:=true;end;if not blocked then raise exception 'Prepared record editable';end if;
 r:=public.cockpit('reopen','{"id":"qa-diary","revision":2,"reason":"QA correção"}');
 if r#>>'{data,preparedAt}' is not null then raise exception 'Reopen failed';end if;
 r:=public.cockpit('save',jsonb_build_object('id','qa-occurrence','kind','occurrence','flightId',f->>'id','data',jsonb_build_object('title','QA rollback','prefix',prefix,'description','QA','technicalType','fault')));
 r:=public.cockpit('send_maintenance','{"id":"qa-occurrence","revision":1}');code:=r#>>'{data,maintenanceCode}';
 if code is null then raise exception 'Maintenance not created';end if;
 r:=public.cockpit('send_maintenance','{"id":"qa-occurrence","revision":2}');
 if r#>>'{data,maintenanceCode}'<>code then raise exception 'Duplicate maintenance';end if;
 if jsonb_array_length(public.cockpit('history','{"id":"qa-occurrence"}'))<>2 then raise exception 'Audit incomplete';end if;
 if public.cockpit('export',jsonb_build_object('flightId',f->>'id'))->>'official'<>'false' then raise exception 'Export official flag wrong';end if;
end $test$;
rollback;
