const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const lib={};new Function('exports',ts.transpileModule(fs.readFileSync('src/lib/crew-operational-base.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(lib);
const flight={id:'one',prefix:'PR-A',commander:'pilot',date:'2026-09-09',departure:'08:00'};const planes=[{prefix:'PR-A',base:'Jacarepaguá'},{prefix:'PR-B',base:'Tomé'}];
test('base follows current aircraft location, not flight base',()=>{assert.equal(lib.crewOperationalBase('pilot',[{...flight,base:'OLD'}],planes,'2026-09-09').base,'Jacarepaguá');assert.equal(lib.crewOperationalBase('pilot',[flight],[{prefix:'PR-A',base:'Tomé'}],'2026-09-09').base,'Tomé');});
test('ongoing operation takes priority over upcoming assignments',()=>{assert.equal(lib.crewOperationalBase('pilot',[{...flight,id:'next'},{...flight,id:'active',prefix:'PR-B',date:'2026-09-08',operationStartedAt:'2026-09-08T23:00:00Z'}],planes,'2026-09-09').flightId,'active');});
test('closed, cancelled, deleted, expired and unrelated flights do not assign a base',()=>{for(const patch of [{cancelled:true},{deletedAt:'now'},{actualShutdown:'now'},{operationEndedAt:'now'},{shutdown:'ok'},{date:'2026-09-08'},{commander:'other'},{compressorDryingTaskId:'dry'}])assert.equal(lib.crewOperationalBase('pilot',[{...flight,...patch}],planes,'2026-09-09').base,'');});
test('next valid assignment selected; no catalog aircraft means no assumed base',()=>{assert.equal(lib.crewOperationalBase('pilot',[{...flight,id:'later',date:'2026-09-10'},flight],planes,'2026-09-09').flightId,'one');assert.equal(lib.crewOperationalBase('pilot',[flight],[],'2026-09-09').base,'');});

test('drying keeps completed aircraft base without claiming an active flight',()=>{const done={...flight,shutdown:'ok'};assert.equal(lib.crewOperationalBase('pilot',[done],planes,'2026-09-09').base,'');assert.equal(lib.crewDryingBase('pilot',[done],planes,'2026-09-09'),'Jacarepaguá');assert.equal(lib.crewDryingBase('pilot',[done],[{prefix:'PR-A',base:'Tomé'}],'2026-09-09'),'Tomé');assert.equal(lib.crewDryingBase('pilot',[done],planes,'2026-09-10'),'');});
test('drying excludes unrelated and cancelled flights; today wins over tomorrow',()=>{const done={...flight,shutdown:'ok'};assert.equal(lib.crewDryingBase('pilot',[{...done,commander:'other'}],planes,'2026-09-09'),'');assert.equal(lib.crewDryingBase('pilot',[{...done,cancelled:true}],planes,'2026-09-09'),'');assert.equal(lib.crewDryingBase('pilot',[done,{...flight,date:'2026-09-10',prefix:'PR-B'}],planes,'2026-09-09','Tomé'),'Jacarepaguá');});
