begin;
do $test$
declare actor uuid; emp text; other_auth uuid; other_emp text; base_name text; original_shift text; cid uuid:=gen_random_uuid(); ordinary uuid:=gen_random_uuid(); msg_before bigint; msg_during bigint; msg_gap bigint; msg_return bigint; data jsonb; failed boolean; audience jsonb; callid uuid:=gen_random_uuid(); sessionid uuid:=gen_random_uuid(); media_path text;
begin
 select d.auth_user_id,d.employee_number,u.assigned_base into actor,emp,base_name from public.device_identities d join public.authorized_users u using(employee_number) where u.active and coalesce(u.job_role,u.access_profile)='maintenance_coordinator' and u.assigned_base is not null limit 1;
 select d.auth_user_id,d.employee_number,u.work_shift into other_auth,other_emp,original_shift from public.device_identities d join public.authorized_users u using(employee_number) where u.active and coalesce(u.job_role,u.access_profile)='mechanic' and u.assigned_base=base_name and d.employee_number<>emp limit 1;
 if actor is null or other_auth is null then raise exception 'Missing fixture';end if;
 update public.authorized_users set work_shift='day' where employee_number=other_emp;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 audience:=jsonb_build_object('rules',jsonb_build_array(jsonb_build_object('base',base_name,'shift','night','role','mechanic')),'included',jsonb_build_array(emp),'excluded','[]'::jsonb);
 execute 'set local role authenticated';
 perform public.chat_fixed_group('create',jsonb_build_object('id',cid,'title','QA fixed audience','audience',audience));
 msg_before:=(public.internal_chat('send',jsonb_build_object('id',cid,'requestId',gen_random_uuid(),'body','QA BEFORE ENTRY'))->>'id')::bigint;
 execute 'reset role';
 update public.authorized_users set work_shift='night' where employee_number=other_emp;
 execute 'set local role authenticated';
 msg_during:=(public.internal_chat('send',jsonb_build_object('id',cid,'requestId',gen_random_uuid(),'body','QA DURING'))->>'id')::bigint;
 perform set_config('request.jwt.claim.sub',other_auth::text,true);
 data:=public.internal_chat('messages',jsonb_build_object('id',cid));
 if data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_before)) or not data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_during)) then raise exception 'Entry boundary failed';end if;
 perform public.chat_receipt('ack',cid,array[msg_before,msg_during]);
 execute 'reset role';
 if exists(select 1 from public.chat_receipts where message_id=msg_before and employee_number=other_emp) then raise exception 'Receipt leaked previous message';end if;
 update public.authorized_users set work_shift='day' where employee_number=other_emp;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 execute 'set local role authenticated';
 msg_gap:=(public.internal_chat('send',jsonb_build_object('id',cid,'requestId',gen_random_uuid(),'body','QA HIDDEN GAP'))->>'id')::bigint;
 data:=public.chat_call('start',jsonb_build_object('conversation',cid,'id',callid,'session',sessionid,'mode','audio'));
 if data->'members' @> jsonb_build_array(jsonb_build_object('employee',other_emp)) then raise exception 'Former member invited to call';end if;
 perform set_config('request.jwt.claim.sub',other_auth::text,true);
 data:=public.internal_chat('messages',jsonb_build_object('id',cid));
 if data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_gap)) or not data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_during)) or (data#>>'{conversation,is_current}')::boolean then raise exception 'Frozen history failed';end if;
 failed:=false;begin perform public.internal_chat('send',jsonb_build_object('id',cid,'requestId',gen_random_uuid(),'body','must reject'));exception when others then failed:=true;end;
 if not failed then raise exception 'Former member could send';end if;
 failed:=false;begin perform public.chat_call('start',jsonb_build_object('conversation',cid,'id',gen_random_uuid(),'session',gen_random_uuid(),'mode','video'));exception when others then failed:=true;end;
 if not failed then raise exception 'Former member could call';end if;
 data:=public.internal_chat('list');
 if exists(select 1 from jsonb_array_elements(data) c where c->>'id'=cid::text and c->>'last_message' like '%HIDDEN GAP%') then raise exception 'List preview leaked gap';end if;
 execute 'reset role';
 if exists(select 1 from public.chat_push_jobs where message_id=msg_gap and employee_number=other_emp) then raise exception 'Push sent to former member';end if;
 update public.authorized_users set work_shift='night' where employee_number=other_emp;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 execute 'set local role authenticated';
 msg_return:=(public.internal_chat('send',jsonb_build_object('id',cid,'requestId',gen_random_uuid(),'body','QA RETURN'))->>'id')::bigint;
 perform set_config('request.jwt.claim.sub',other_auth::text,true);
 data:=public.internal_chat('messages',jsonb_build_object('id',cid));
 if data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_gap)) or not data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_during)) or not data->'messages' @> jsonb_build_array(jsonb_build_object('id',msg_return)) then raise exception 'Reentry periods failed';end if;
 execute 'reset role';
 if (select count(*) from public.chat_membership_periods where conversation_id=cid and employee_number=other_emp)<>2 then raise exception 'Unexpected periods';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 execute 'set local role authenticated';
 perform public.chat_fixed_group('update',jsonb_build_object('id',cid,'audience',audience||jsonb_build_object('excluded',jsonb_build_array(other_emp))));
 execute 'reset role';
 if private.chat_current(cid,other_emp) then raise exception 'Explicit exclusion failed';end if;
 execute 'set local role authenticated';
 perform public.chat_fixed_group('update',jsonb_build_object('id',cid,'audience',jsonb_build_object('rules','[]'::jsonb,'included',jsonb_build_array(emp,other_emp),'excluded','[]'::jsonb)));
 execute 'reset role';
 update public.authorized_users set work_shift='day' where employee_number=other_emp;
if not private.chat_current(cid,other_emp) then raise exception 'Manual inclusion should persist';end if;
 if exists(select 1 from public.authorized_users where assigned_base is not null and assigned_base<>base_name) then
  update public.authorized_users set assigned_base=(select max(assigned_base) from public.authorized_users where assigned_base<>base_name) where employee_number=other_emp;
  execute 'set local role authenticated';
  perform public.chat_fixed_group('update',jsonb_build_object('id',cid,'audience',jsonb_build_object('rules','[]'::jsonb,'included',jsonb_build_array(emp,other_emp),'excluded','[]'::jsonb)));
  execute 'reset role';
  if not private.chat_current(cid,other_emp) then raise exception 'Existing manual exception lost after base move';end if;
  update public.authorized_users set assigned_base=base_name where employee_number=other_emp;
 end if;
 execute 'set local role authenticated';
 perform public.internal_chat('create',jsonb_build_object('id',ordinary,'members',jsonb_build_array(other_emp)));
 perform public.internal_chat('send',jsonb_build_object('id',ordinary,'requestId',gen_random_uuid(),'body','QA ORDINARY'));
 execute 'reset role';
 update public.authorized_users set work_shift='night' where employee_number=other_emp;
 perform set_config('request.jwt.claim.sub',other_auth::text,true);
 execute 'set local role authenticated';
 data:=public.internal_chat('messages',jsonb_build_object('id',ordinary));
 if not data->'messages' @> '[{"body":"QA ORDINARY"}]'::jsonb then raise exception 'Ordinary chat regression';end if;
 execute 'reset role';
 -- An attachment from before entry must be inaccessible, while participating-period media remains readable.
 media_path:=cid::text||'/'||actor::text||'/qa-before.pdf';
 update public.internal_messages set attachments=jsonb_build_array(jsonb_build_object('bucket','internal-chat','url',media_path,'type','document','name','before.pdf')) where id=msg_before;
 insert into storage.objects(bucket_id,name) values('internal-chat',media_path);
 execute 'set local role authenticated';
 if exists(select 1 from storage.objects where bucket_id='internal-chat' and name=media_path) then raise exception 'Pre-entry attachment exposed';end if;
 execute 'reset role';
 media_path:=cid::text||'/'||actor::text||'/qa-during.pdf';
 update public.internal_messages set attachments=jsonb_build_array(jsonb_build_object('bucket','internal-chat','url',media_path,'type','document','name','during.pdf')) where id=msg_during;
 insert into storage.objects(bucket_id,name) values('internal-chat',media_path);
 execute 'set local role authenticated';
 if not exists(select 1 from storage.objects where bucket_id='internal-chat' and name=media_path) then raise exception 'Own-period attachment missing';end if;
 failed:=false;begin perform public.chat_fixed_group('update',jsonb_build_object('id',cid,'audience',audience));exception when others then failed:=true;end;
 if not failed then raise exception 'Member could alter fixed audience';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 failed:=false;begin perform public.chat_fixed_group('update',jsonb_build_object('id',ordinary,'audience',audience));exception when others then failed:=true;end;
 if not failed then raise exception 'Ordinary converted to fixed';end if;
 failed:=false;begin perform public.chat_fixed_group('create',jsonb_build_object('id',gen_random_uuid(),'audience',jsonb_build_object('rules',jsonb_build_array(jsonb_build_object('base','OTHER BASE')),'included',jsonb_build_array(emp),'excluded','[]'::jsonb)));exception when others then failed:=true;end;
 if not failed then raise exception 'Cross-base audience allowed';end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub','',true);
 execute 'set local role authenticated';
 failed:=false;begin perform public.internal_chat('list');exception when others then failed:=true;end;
 if not failed then raise exception 'Anonymous chat access';end if;
 execute 'reset role';
end $test$;
rollback;
