const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(path,deps={}){const exports={};new Function('exports','require',ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,name=>{if(!(name in deps))throw Error(name);return deps[name];});return exports;}
const lib=load('src/lib/flight-import.ts');
const row=()=>({prefix:'PR-TEST',date:'2026-09-09',departure:'08:00',destination:'P-01',duration:'01:30',fuelAmount:null,fuelUnit:null,notes:'Página 1'});
test('partial import leaves unknown fields empty without defaults for flight date/time or fuel',()=>{const source={...row(),prefix:'PR-UNKNOWN',date:null,departure:null,duration:null,fuelAmount:'350',fuelUnit:null};const draft=lib.importedDraftFields(source,[{prefix:'PR-TEST'}]);assert.equal(draft.prefix,'');assert.equal(draft.date,'');assert.equal(draft.departure,'');assert.equal(draft.duration,'');assert.equal(draft.fuelAmount,'');assert.equal(draft.repeat,false);assert.equal(source.fuelAmount,'350');assert.ok(lib.importIssues(source,[{prefix:'PR-TEST'}]).length>=4);});
test('calendar and clock validation rejects rollover dates, invalid hours and zero duration',()=>{assert.equal(lib.validDate('2026-02-30'),false);assert.equal(lib.validDate('2024-02-29'),true);assert.equal(lib.validClock('24:10'),false);assert.equal(lib.validClock('08:61'),false);assert.equal(lib.importedDraftFields({...row(),duration:'00:00'},[{prefix:'PR-TEST'}]).duration,'');});
test('duplicate detection ignores cancelled/deleted flights but catches same aircraft date/time',()=>{assert.equal(lib.duplicateFlight(row(),[{...row(),prefix:'pr-test'}]),true);assert.equal(lib.duplicateFlight(row(),[{...row(),cancelled:true}]),false);assert.equal(lib.duplicateFlight(row(),[{...row(),deletedAt:'date'}]),false);assert.equal(lib.duplicateFlight({...row(),date:null},[row()]),false);});
test('schema parsing rejects forged fields, oversized lists, external URLs and unsupported attachments',()=>{assert.throws(()=>lib.parseFlightImportAnswer({reply:'ok',flights:[{...row(),planningStatus:'confirmed'}]}));assert.throws(()=>lib.parseFlightImportAnswer({reply:'ok',flights:Array(31).fill(row())}));for(const data of ['https://example.com/a.pdf','data:image/svg+xml;base64,YQ=='])assert.throws(()=>lib.parseFlightImportRequest({message:'',attachment:{name:'file',data}}));assert.equal(lib.parseFlightImportAnswer({reply:'ok',flights:[{...row(),prefix:'pr-test'}]}).flights[0].prefix,'PR-TEST');});
test('route gates model by session, validates file magic, handles quota and sends typed attachments',async()=>{let allowed=false,calls=0,payload,mode='ok';const beforeFetch=global.fetch,beforeKey=process.env.OPENAI_API_KEY;const route=load('src/app/api/ai/flight-import/route.ts',{'@/lib/assistant-access':{assistantAccess:async()=>{if(!allowed)throw Error('denied');}},'@/lib/flight-import':lib});const req=body=>new Request('http://test/api/ai/flight-import',{method:'POST',body:JSON.stringify(body)});try{process.env.OPENAI_API_KEY='test-only';global.fetch=async(url,options)=>{calls++;payload=JSON.parse(options.body);if(mode==='quota')return Response.json({}, {status:429});return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({reply:'ok',flights:[row()]})}]}]});};assert.equal((await route.POST(req({message:'texto'}))).status,401);assert.equal(calls,0);allowed=true;assert.equal((await route.POST(req({message:'',attachment:{name:'a.pdf',data:'data:application/pdf;base64,YQ=='}}))).status,400);assert.equal(calls,0);const data='data:application/pdf;base64,'+Buffer.from('%PDF-1.4 synthetic').toString('base64');assert.equal((await route.POST(req({message:'extraia',attachment:{name:'a.pdf',data}}))).status,200);assert.equal(payload.input[0].content[1].type,'input_file');assert.equal(payload.store,false);mode='quota';assert.equal((await route.POST(req({message:'extraia'}))).status,429);}finally{global.fetch=beforeFetch;if(beforeKey===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=beforeKey;}});
