begin;
do $test$
declare a public.device_identities;b public.device_identities;outsider public.device_identities;
 cid uuid:=gen_random_uuid();callid uuid:=gen_random_uuid();sa uuid:=gen_random_uuid();sb uuid:=gen_random_uuid();v jsonb;denied boolean;req uuid:=gen_random_uuid();group_people jsonb;person jsonb;counter int:=0;
begin
 select d.* into a from public.device_identities d join public.authorized_users u using(employee_number) where u.active limit 1;
 select d.* into b from public.device_identities d join public.authorized_users u using(employee_number) where u.active and d.employee_number<>a.employee_number limit 1;
 select d.* into outsider from public.device_identities d join public.authorized_users u using(employee_number) where u.active and d.employee_number not in(a.employee_number,b.employee_number) limit 1;
 if outsider.auth_user_id is null then raise exception 'Need three test identities';end if;
 perform set_config('request.jwt.claim.sub',a.auth_user_id::text,true);
 perform public.internal_chat('create',jsonb_build_object('id',cid,'members',jsonb_build_array(b.employee_number)));
 v:=public.chat_call('start',jsonb_build_object('id',callid,'conversation',cid,'mode','audio','session',sa));
 if (v->'call'->>'id')::uuid<>callid or v->>'ended'<>'false' then raise exception 'Start failed';end if;
 if (public.chat_call('start',jsonb_build_object('id',gen_random_uuid(),'conversation',cid,'mode','audio','session',sa))->'call'->>'id')::uuid<>callid then raise exception 'Duplicate call';end if;
 perform set_config('request.jwt.claim.sub',outsider.auth_user_id::text,true);
 if exists(select 1 from jsonb_array_elements(public.chat_call('incoming')) x where x->>'id'=callid::text) then raise exception 'Leaked incoming';end if;
 denied:=false;begin perform public.chat_call('join',jsonb_build_object('id',callid,'session',gen_random_uuid()));exception when others then denied:=true;end;
 if not denied then raise exception 'Outsider joined';end if;
 perform set_config('request.jwt.claim.sub',b.auth_user_id::text,true);
 if not exists(select 1 from jsonb_array_elements(public.chat_call('incoming')) x where x->>'id'=callid::text) then raise exception 'Missing incoming';end if;
 perform public.chat_call('join',jsonb_build_object('id',callid,'session',sb));
 denied:=false;begin perform public.chat_call('join',jsonb_build_object('id',callid,'session',gen_random_uuid()));exception when others then denied:=true;end;
 if not denied then raise exception 'Duplicate device allowed';end if;
 perform set_config('request.jwt.claim.sub',a.auth_user_id::text,true);
 perform public.chat_call('signal',jsonb_build_object('id',callid,'session',sa,'recipient',sb,'requestId',req,'signal',jsonb_build_object('type','offer','sdp','test')));
 perform public.chat_call('signal',jsonb_build_object('id',callid,'session',sa,'recipient',sb,'requestId',req,'signal',jsonb_build_object('type','offer','sdp','test')));
 if jsonb_array_length(public.chat_call('poll',jsonb_build_object('id',callid,'session',sa))->'signals')<>0 then raise exception 'Sender sees recipient signals';end if;
 denied:=false;begin perform public.chat_call('signal',jsonb_build_object('id',callid,'session',sb,'recipient',sa,'requestId',gen_random_uuid(),'signal',jsonb_build_object('type','offer','sdp','forged')));exception when others then denied:=true;end;
 if not denied then raise exception 'Forged session accepted';end if;
 perform set_config('request.jwt.claim.sub',b.auth_user_id::text,true);
 if jsonb_array_length(public.chat_call('poll',jsonb_build_object('id',callid,'session',sb))->'signals')<>1 then raise exception 'Signal missing or duplicate';end if;
 perform public.chat_call('leave',jsonb_build_object('id',callid,'session',sb));
 if not exists(select 1 from public.chat_calls where id=callid and ended_at is not null) or exists(select 1 from public.chat_call_signals where call_id=callid) then raise exception 'Leave or signal cleanup failed';end if;
 if not exists(select 1 from public.internal_messages where conversation_id=cid and body like 'Chamada encerrada%') then raise exception 'History missing';end if;
 perform set_config('request.jwt.claim.sub',a.auth_user_id::text,true);
 if public.chat_call('poll',jsonb_build_object('id',callid,'session',sa))->>'ended'<>'true' then raise exception 'Other side not notified of end';end if;
 callid:=gen_random_uuid();perform public.chat_call('start',jsonb_build_object('id',callid,'conversation',cid,'mode','video','session',sa));
 perform set_config('request.jwt.claim.sub',b.auth_user_id::text,true);
 perform public.chat_call('decline',jsonb_build_object('id',callid));
 if not exists(select 1 from public.chat_calls where id=callid and ended_at is not null) then raise exception 'Decline failed';end if;
 select jsonb_agg(to_jsonb(t)) into group_people from (select distinct on(d.employee_number) d.employee_number,d.auth_user_id from public.device_identities d join public.authorized_users u using(employee_number) where u.active and d.employee_number<>a.employee_number order by d.employee_number limit 6) t;
 if jsonb_array_length(group_people)<>6 then raise exception 'Need seven test identities';end if;
 perform set_config('request.jwt.claim.sub',a.auth_user_id::text,true);cid:=gen_random_uuid();callid:=gen_random_uuid();
 perform public.internal_chat('create',jsonb_build_object('id',cid,'members',(select jsonb_agg(x->>'employee_number') from jsonb_array_elements(group_people) x)));
 perform public.chat_call('start',jsonb_build_object('id',callid,'conversation',cid,'mode','video','session',sa));
 for person in select * from jsonb_array_elements(group_people) loop
  counter:=counter+1;perform set_config('request.jwt.claim.sub',person->>'auth_user_id',true);
  if counter<6 then perform public.chat_call('join',jsonb_build_object('id',callid,'session',gen_random_uuid()));
  else denied:=false;begin perform public.chat_call('join',jsonb_build_object('id',callid,'session',gen_random_uuid()));exception when others then denied:=true;end;if not denied then raise exception 'Capacity exceeded';end if;end if;
 end loop;
 update public.chat_call_members set heartbeat=now()-interval '1 minute' where call_id=callid and state='joined';
 perform private.expire_chat_calls();
 if not exists(select 1 from public.chat_calls where id=callid and ended_at is not null) then raise exception 'Stale calls remain open';end if;
 if has_function_privilege('anon','public.chat_call(text,jsonb)','execute') or has_table_privilege('authenticated','public.chat_call_signals','select') then raise exception 'Permissions too broad';end if;
end $test$;
rollback;
select 'PASS: incoming, consent, outsider isolation, device isolation, signals and retry, decline, end and history' result;
