begin;
do $$
declare inspector uuid;mech uuid;pilot uuid;coord uuid;inspector_emp text;emp text;pilot_emp text;b text;r uuid:=gen_random_uuid();w text;second_w text;procedure_w text;fid text;op jsonb;req uuid;card jsonb;
begin
 select d.auth_user_id,d.employee_number,d.assigned_base into inspector,inspector_emp,b from device_identities d join authorized_users u using(employee_number) where u.active and u.job_role='maintenance_inspector' limit 1;
 select d.auth_user_id,d.employee_number into mech,emp from device_identities d join authorized_users u using(employee_number) where u.active and u.job_role='mechanic' and d.assigned_base=b limit 1;
 select d.auth_user_id,d.employee_number into pilot,pilot_emp from device_identities d join authorized_users u using(employee_number) where u.active and u.job_role='commander' and d.assigned_base=b limit 1;
 select d.auth_user_id into coord from device_identities d join authorized_users u using(employee_number) where u.active and u.job_role='coordination' limit 1;
 perform set_config('request.jwt.claim.sub',inspector::text,true);
 insert into maintenance_records(id,record_type,base,model,prefix,priority,status,title,created_by,data) values(r,'fault',b,'S92','TEST-TRAIL','urgent','open','Vazamento de teste',inspector_emp,'{"entries":[]}');
 execute 'set local role authenticated';
 w:=public.create_maintenance_request(r,'Giro em baixa','Finalidade e FC-123',array[emp],null,jsonb_build_object('spot','P4','commander',pilot_emp,'crewRequirement','Conforme FC-123'));
 second_w:=public.create_maintenance_request(r,'Giro em alta','Outra tarefa',array[emp],null,'{}');
 procedure_w:=public.create_maintenance_request(r,'Procedimentos','Interno',array[emp],null,'{}');
 execute 'reset role';
 select f->>'id' into fid from shared_app_state s,jsonb_array_elements(s.flights) f where f->>'maintenancePostId'=w;
 if fid is null then raise exception 'No operational card created';end if;
 if not exists(select 1 from shared_app_state s,jsonb_array_elements(s.flights) f where f->>'id'=fid and f->>'maintenancePriority'='urgent') then raise exception 'Urgency was lost';end if;
 if exists(select 1 from shared_app_state s,jsonb_array_elements(s.flights) f where f->>'maintenancePostId'=procedure_w) then raise exception 'Procedure became operational';end if;
 perform set_config('request.jwt.claim.sub',pilot::text,true);execute 'set local role authenticated';
 op:=public.get_flight_operation(fid);
 begin perform public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'event','{"type":"apu_on"}');raise exception 'Started without required checks';exception when others then if sqlerrm='Started without required checks' then raise;end if;end;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',mech::text,true);execute 'set local role authenticated';
 op:=public.get_flight_operation(fid);
 if not(op->>'first')::boolean then raise exception 'Maintenance needs preflight';end if;
 op:=public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'approve','{"key":"fuel","result":"ok"}');
 op:=public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'approve','{"key":"inspection","result":"ok"}');
 begin perform public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'approve','{"key":"drain","result":"ok"}');raise exception 'Drain accepted';exception when others then if sqlerrm='Drain accepted' then raise;end if;end;
 execute 'reset role';perform set_config('request.jwt.claim.sub',pilot::text,true);execute 'set local role authenticated';
 op:=public.get_flight_operation(fid);
 op:=public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'event','{"type":"apu_on"}');
 op:=public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'event','{"type":"apu_off"}');
 op:=public.record_flight_operation(fid,gen_random_uuid(),(op->>'revision')::int,'event','{"type":"finish"}');
 if not(op->>'closed')::boolean then raise exception 'APU-only operation did not finish';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',mech::text,true);execute 'set local role authenticated';
 req:=gen_random_uuid();perform public.record_maintenance_task_result(w,'SECRET technical result','nonconforming',req);perform public.record_maintenance_task_result(w,'SECRET technical result','nonconforming',req);
 execute 'reset role';
 if (select jsonb_array_length(data#>'{actions,0,executions}') from operational_wall_posts where id=w)<>1 then raise exception 'Duplicate result';end if;
 if (select data#>>'{actions,0,status}' from operational_wall_posts where id=second_w)<>'pending' then raise exception 'Result changed another task';end if;
 if not exists(select 1 from maintenance_records m,jsonb_array_elements(m.data->'entries') e where m.id=r and e->>'actionPostId'=w) then raise exception 'Result not linked to technical record';end if;
 perform set_config('request.jwt.claim.sub',coord::text,true);execute 'set local role authenticated';
 if exists(select 1 from operational_wall_posts where id=w) then raise exception 'Coordination sees technical post';end if;
 select c into card from public.list_maintenance_operation_cards() c where c->>'flightId'=fid;
 if card is null or card->>'spot'<>'P4' or card->>'category'<>'Giro em baixa' or card::text like '%SECRET%' or card::text like '%PAN-%' then raise exception 'Invalid operational projection';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',pilot::text,true);execute 'set local role authenticated';
 select c into card from public.list_crew_maintenance_actions() c where c->>'flightId'=fid;
 if card is null or card::text like '%SECRET%' then raise exception 'Pilot projection failed';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',inspector::text,true);execute 'set local role authenticated';
 perform public.mark_wall_read(w,now(),null);
 execute 'reset role';
 if exists(select 1 from wall_read_receipts where post_id=w and employee_number=inspector_emp and comments_at is not null) then raise exception 'Content read consumed unseen comments';end if;
-- Deleting a source retires its card but keeps operational event history.
 perform set_config('request.jwt.claim.sub',inspector::text,true);
 execute 'set local role authenticated';
 perform public.delete_own_operational_wall_post(second_w);
 execute 'reset role';
 if not exists(select 1 from shared_app_state s,jsonb_array_elements(s.flights) f where f->>'maintenancePostId'=second_w and f->>'deletedAt' is not null and (f->>'maintenanceSourceDeleted')::boolean) then raise exception 'Orphan card remains active';end if;
 perform set_config('request.jwt.claim.sub',coord::text,true);execute 'set local role authenticated';
 if exists(select 1 from public.list_maintenance_operation_cards() c where c->>'title'='Outra tarefa') then raise exception 'Deleted task remains visible';end if;
 execute 'reset role';
perform set_config('request.jwt.claim.sub',inspector::text,true);execute 'set local role authenticated';
 perform public.delete_own_operational_wall_post(w);
 execute 'reset role';
 if (select jsonb_array_length(events) from public.flight_operation_records where flight_id=fid)<>3 then raise exception 'Operational history lost on source deletion';end if;
end $$;
select 'PASS operational card, schedule, crew, procedures excluded, minimal checks, APU-only finish, linked/idempotent results, privacy, separate read markers, urgency and orphan retirement preserving events' result;
rollback;
