const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const path=require('node:path');
function load(file){const exports={};new Function('exports','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,name=>load(path.resolve(path.dirname(file),name+'.ts')));return exports;}
const {timelineTone,timelineStatus}=load('src/lib/maintenance-wall-state.ts');const {wallTimeline}=load('src/lib/wall-selectors.ts');
const post={id:'task',category:'Voo de manutenção',title:'Giro',body:'Resultado satisfatório',priority:'urgent',createdAt:'2026-09-10T12:00:00Z',comments:[],views:[],history:[],technicalCase:{priority:'urgent',report:'report',official:'evaluation',aircraft:'evaluation',investigation:'triage'},actions:[{status:'satisfactory',executions:[{at:'2026-09-10T13:00:00Z',result:'satisfactory',description:'OK',employeeNumber:'M'}]}]};
test('satisfactory giro is green while source remains pending',()=>{assert.equal(timelineTone(post,'M'),'border-emerald-500');assert.match(timelineStatus(post),/aguardando encerramento/);assert.equal(timelineTone({...post,actions:[]},'M'),'border-red-500');});
test('nonconforming or pending sibling is never hidden by a successful task',()=>{assert.equal(timelineTone({...post,actions:[...post.actions,{status:'nonconforming',executions:[]}]},'M'),'border-red-500');assert.notEqual(timelineTone({...post,actions:[...post.actions,{status:'pending',executions:[]}]},'M'),'border-emerald-500');});
test('closed and released origin is green; critical or re-opened stays visible',()=>{const closed={...post,actions:[],technicalCase:{...post.technicalCase,investigation:'closed',aircraft:'released'}};assert.equal(timelineTone(closed,'M'),'border-emerald-500');assert.equal(timelineStatus(closed),'Caso encerrado');assert.equal(timelineTone({...closed,technicalCase:{...closed.technicalCase,critical:true}},'M'),'border-red-500');});
test('closed source cards leave the live wall while the mechanic result remains and history is preserved',()=>{
 const source={...post,id:'origin',maintenanceRecordId:'record',category:'Relato Técnico',actions:[],technicalCase:{...post.technicalCase,investigation:'closed',aircraft:'released'},history:[{at:'2026-09-10T12:00:00Z',event:'Criou relato técnico',employeeNumber:'M'},{at:'2026-09-11T15:00:00Z',event:'Encerrou relato técnico',employeeNumber:'I'}]};
 const giro={...post,maintenanceRecordId:'record',technicalCase:source.technicalCase};
 const items=wallTimeline([giro,source],'2026-09-10','2026-09-11','UTC');assert.deepEqual(items.map(i=>i.id),['task']);assert.equal(items[0].actor,'M');assert.equal(items[0].summary,'OK');assert.equal(source.history.length,2);
 const reopened={...source,technicalCase:{...source.technicalCase,investigation:'triage'},history:[...source.history,{at:'2026-09-11T16:00:00Z',event:'Reabriu relato técnico',employeeNumber:'I'}]};assert.equal(wallTimeline([reopened],'2026-09-11','2026-09-11','UTC').length,1);
});

test("reopened activity does not reuse an old post closure",()=>{const reopened={...post,resolved:true,actions:[{...post.actions[0],status:"pending"}]};assert.notEqual(timelineTone(reopened,"M"),"border-emerald-500");assert.notEqual(timelineStatus(reopened),"Concluído");assert.match(timelineStatus({...post,resolved:true}),/aguardando encerramento/);});
