const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const lib={};new Function('exports',ts.transpileModule(fs.readFileSync('src/lib/service-handover.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(lib);
const task={recordType:'inspection',status:'open',revision:2,planningState:'completed'};
test('concluded stays across midnight until personal acknowledgment, then returns after intervention',()=>{assert.ok(lib.handoverVisible(task,'active'));assert.equal(lib.handoverVisible(task,'active',2),false);assert.ok(lib.handoverVisible({...task,revision:3},'active',2));assert.ok(lib.handoverVisible(task,'active',1));});
test('acknowledgment does not remove pending work or open technical cases',()=>{assert.ok(lib.handoverVisible({...task,planningState:undefined},'active',2));assert.ok(lib.handoverVisible({...task,recordType:'fault',technicalCase:{investigation:'open'}},'active',2));assert.ok(lib.handoverVisible({...task,entries:[{kind:'action',result:'nonconforming',at:'2026-09-12T03:00:00Z'}]},'pending',2));});
test('history retains excluded and acknowledged; pending filter omits completed',()=>{assert.ok(lib.handoverVisible({...task,planningState:'excluded'},'all',2));assert.equal(lib.handoverVisible({...task,planningState:'excluded'},'active'),false);assert.equal(lib.handoverVisible(task,'pending'),false);assert.ok(lib.handoverVisible(task,'all',2));});

const published=Date.parse('2026-09-11T23:00:00-03:00');const closed={...task,status:'closed',createdAt:new Date(published).toISOString()};
test('24 hours starts at publication, even when closure happens much later',()=>{assert.ok(lib.handoverVisible(closed,'active',undefined,published+86400000-1));assert.equal(lib.handoverVisible(closed,'active',undefined,published+86400000),false);assert.equal(lib.handoverVisible({...closed,updatedAt:new Date(published+90000000).toISOString()},'active',undefined,published+90000000),false);assert.ok(lib.handoverVisible(closed,'all',undefined,published+90000000));});
test('age alone cannot expire pending, failed or unsigned closure records',()=>{for(const item of [{...closed,status:'open'},{...closed,planningState:undefined},{...closed,entries:[{kind:'action',result:'nonconforming',at:new Date(published).toISOString()}]},{...closed,createdAt:'invalid'}])assert.ok(lib.handoverVisible(item,'active',undefined,published+90000000));});
test('technical cases use entry into handover and require successful release',()=>{const item={...closed,recordType:'fault',createdAt:new Date(published-86400000).toISOString(),technicalCase:{serviceEnteredAt:new Date(published).toISOString(),investigation:'closed',aircraft:'released'}};assert.ok(lib.handoverVisible(item,'active',undefined,published+1000));assert.equal(lib.handoverVisible(item,'active',undefined,published+86400000),false);assert.ok(lib.handoverVisible({...item,technicalCase:{...item.technicalCase,aircraft:'unavailable'}},'active',undefined,published+86400000));});
