begin;
do $test$
declare actor uuid;emp text;mech text;base_name text;prefix_name text;id1 uuid:=gen_random_uuid();id2 uuid:=gen_random_uuid();rev bigint; caught boolean; data_before jsonb;
begin
 select d.auth_user_id,d.employee_number,d.assigned_base into actor,emp,base_name from public.device_identities d join public.authorized_users u using(employee_number) where u.active and u.job_role='maintenance_coordinator' and d.assigned_base is not null limit 1;
 select employee_number into mech from public.authorized_users where active and job_role='mechanic' and assigned_base=base_name limit 1;
 select a->>'prefix' into prefix_name from public.shared_app_state s,jsonb_array_elements(s.catalogs->'aircraft') a where s.id='main' and a->>'base'=base_name limit 1;
 if actor is null or mech is null or prefix_name is null then raise exception 'Missing fixtures';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 update public.authorized_users set work_shift='day' where employee_number=emp;
 update public.device_identities set signature_verified_at=now() where auth_user_id=actor;
 insert into public.maintenance_records(id,record_type,base,model,prefix,priority,status,title,created_by,data) values(id1,'inspection',base_name,'S92',prefix_name,'routine','open','QA service',emp,jsonb_build_object('description','QA inspection','entries','[]'::jsonb,'assignedTo','[]'::jsonb)),(id2,'inspection',base_name,'S92',prefix_name,'routine','open','QA other',emp,jsonb_build_object('description','QA inspection','entries','[]'::jsonb));
 select revision into rev from public.maintenance_records where id=id1;
 execute 'set local role authenticated';
 perform public.service_planning_batch(jsonb_build_array(jsonb_build_object('id',id1,'revision',rev)),'assign',array[mech]);
 execute 'reset role';
 if not exists(select 1 from public.maintenance_records where id=id1 and data->'assignedTo' ? mech and data#>'{entries,0,assignedTo}' ? mech) then raise exception 'Assignment lost';end if;
 select revision into rev from public.maintenance_records where id=id1;
 execute 'set local role authenticated';
 caught:=false;begin perform public.service_planning_batch(jsonb_build_array(jsonb_build_object('id',id1,'revision',rev),jsonb_build_object('id',id2,'revision',-1)),'exclude');exception when others then caught:=sqlerrm like '%atualizado%';end;
 if not caught then raise exception 'Stale revision accepted';end if;
 execute 'reset role';
 if exists(select 1 from public.maintenance_records where id=id1 and data ? 'planningState') then raise exception 'Partial batch write';end if;
 update public.authorized_users set work_shift='night' where employee_number=emp;
 execute 'set local role authenticated';
 perform public.service_planning_batch(jsonb_build_array(jsonb_build_object('id',id1,'revision',rev)),'tc','{}','N/A');
 execute 'reset role';
 if not exists(select 1 from public.maintenance_records where id=id1 and data->>'lastWorkShift'='night' and data#>>'{entries,0,workShift}'='day') then raise exception 'Shift provenance lost';end if;
 select revision into rev from public.maintenance_records where id=id1;
 execute 'set local role authenticated';
 perform public.service_planning_batch(jsonb_build_array(jsonb_build_object('id',id1,'revision',rev)),'execute','{}','Inspeção realizada conforme TC.');
 execute 'reset role';
 if not exists(select 1 from public.maintenance_records where id=id1 and status='open' and data->>'planningState'='completed' and data#>>'{entries,2,result}'='satisfactory' and tc='N/A') then raise exception 'Execution improperly closed record';end if;
 select revision into rev from public.maintenance_records where id=id2;
 execute 'set local role authenticated';
 perform public.service_planning_batch(jsonb_build_array(jsonb_build_object('id',id2,'revision',rev)),'exclude');
 execute 'reset role';
 if not exists(select 1 from public.maintenance_records where id=id2 and status='open' and data->>'planningState'='excluded') then raise exception 'Record deleted or closed';end if;
 select revision,technical_case into rev,data_before from public.maintenance_records where id=id2;
 execute 'set local role authenticated';
 perform public.technical_case_action('update',id2,jsonb_build_object('revision',rev,'title','QA edited','description','QA edited task','case',data_before||jsonb_build_object('reason','QA correction')));
 execute 'reset role';
 if not exists(select 1 from public.maintenance_records where id=id2 and title='QA edited' and data->>'planningState'='excluded') then raise exception 'Programmed editing failed';end if;
 update public.device_identities set signature_verified_at=null where auth_user_id=actor;
 execute 'set local role authenticated';
 caught:=false;begin perform public.service_planning_batch(jsonb_build_array(jsonb_build_object('id',id1,'revision',rev)),'tc','{}','123');exception when others then caught:=sqlerrm like '%assinatura%';end;
 if not caught then raise exception 'Unsigned operation accepted';end if;
 execute 'reset role';
end $test$;
select 'PASS assignments, TC N/A, atomic rollback, execution without closure, exclusion without deleting records, signature required' result;
rollback;
