const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const lib={};
new Function('exports',ts.transpileModule(fs.readFileSync('src/lib/technical-case.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(lib);
test('legacy unlogged faults never imply an official exception or release',()=>{const c=lib.legacyTechnicalCase('fault','not_logged');assert.equal(c.official,'pending');assert.equal(c.aircraft,'evaluation');assert.equal(c.report,'discrepancy');});
test('a new report has four independent initial axes',()=>assert.deepEqual(lib.initialTechnicalCase(),{report:'report',official:'evaluation',aircraft:'evaluation',investigation:'triage'}));
test('critical review preserves text and never creates a technical result',()=>{for(const phrase of ['falha presente, mas vai voar','liberado somente para cumprir o voo','teste não realizado','colocado OK para produzir']){const r=lib.technicalDraftReview(phrase,'mechanic');assert.equal(r.original,phrase);assert.equal(r.suggestion,phrase);assert.equal(r.critical,true);assert.equal(r.aiAssisted,false);assert.ok(r.notice.includes('nenhum acervo licenciado'));}});
test('pilot and mechanic review request different missing information',()=>{assert.notDeepEqual(lib.technicalDraftReview('HSI','pilot').questions,lib.technicalDraftReview('HSI','mechanic').questions);});
test('technical cards do not imply dispatch authorization from an APRS reference',()=>{const c={...lib.initialTechnicalCase(),aircraft:'released',aprsRef:'A1',aprsBy:'M1'};assert.ok(!lib.technicalTone(c).includes('emerald'));assert.equal(lib.technicalCardBorder({...c,priority:'urgent'}),'border-red-500');assert.equal(lib.technicalCardBorder({...c,critical:true}),'border-red-500');});
test('handover remains pending after reprioritization until case closure',()=>{const c={...lib.initialTechnicalCase(),serviceEnteredAt:'2026-09-01',priority:'routine'};assert.equal(lib.serviceCasePending(c),true);assert.equal(lib.serviceCasePending({...c,investigation:'closed'}),false);assert.equal(lib.serviceCasePending(lib.initialTechnicalCase()),false);});
test('expired deferral and due counters remain visible as attention',()=>{const c={...lib.initialTechnicalCase(),aircraft:'deferred',disposition:{deadline:'2026-09-01T00:00:00Z'}};const now=Date.parse('2026-09-08T00:00:00Z');assert.match(lib.technicalDeadline(c,now),/vencido/);assert.equal(lib.technicalCardBorder(c,now),'border-red-500');const watch={...lib.initialTechnicalCase(),investigation:'condition_watch',conditionWatch:{dueKind:'hours',currentValue:'100',dueValue:'100'}};assert.match(lib.technicalDeadline(watch,now),/atingido/);assert.equal(lib.technicalDeadline({...watch,conditionWatch:{...watch.conditionWatch,currentValue:'99'}},now),'');});
