begin;
do $t$
declare keeper public.device_identities; inspector public.device_identities; owner_d public.device_identities; borrower public.device_identities; b uuid;o uuid;e uuid;blocked boolean;
begin
 select * into keeper from public.device_identities where coalesce(job_role,access_profile)='toolroom' limit 1;
 select * into inspector from public.device_identities where coalesce(job_role,access_profile)='maintenance_inspector' limit 1;
 select * into owner_d from public.device_identities where coalesce(job_role,access_profile)='mechanic' limit 1;
 select * into borrower from public.device_identities where coalesce(job_role,access_profile)='mechanic' and employee_number<>owner_d.employee_number limit 1;
 perform set_config('request.jwt.claim.sub',inspector.auth_user_id::text,true);
 b:=public.create_toolbox_catalog('QA custody '||gen_random_uuid(),'Jacarepaguá');
 blocked:=false;begin perform public.toolbox_command('assign_box',jsonb_build_object('boxId',b,'assignedTo',owner_d.employee_number));exception when others then blocked:=true;end;if not blocked then raise exception 'Inspector lent box';end if;
 perform set_config('request.jwt.claim.sub',keeper.auth_user_id::text,true);
 o:=(public.toolbox_command('assign_box',jsonb_build_object('boxId',b,'assignedTo',owner_d.employee_number))->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',borrower.auth_user_id::text,true);
 blocked:=false;begin perform public.toolbox_command('accept_box',jsonb_build_object('operationId',o));exception when others then blocked:=true;end;if not blocked then raise exception 'Wrong recipient accepted';end if;
 perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);perform public.toolbox_command('accept_box',jsonb_build_object('operationId',o));
 perform set_config('request.jwt.claim.sub',borrower.auth_user_id::text,true);
 e:=(public.toolbox_command('take_tool',jsonb_build_object('boxId',b,'description','Alicate','aircraftPrefix','PR-CHT'))->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',inspector.auth_user_id::text,true);
 blocked:=false;begin perform public.toolbox_command('approve_tool_withdrawal',jsonb_build_object('eventId',e));exception when others then blocked:=true;end;if not blocked then raise exception 'Unrelated inspector approved loan';end if;
 perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);perform public.toolbox_command('approve_tool_withdrawal',jsonb_build_object('eventId',e));
 perform set_config('request.jwt.claim.sub',keeper.auth_user_id::text,true);
 blocked:=false;begin perform public.toolbox_command('request_box_return',jsonb_build_object('operationId',o));exception when others then blocked:=true;end;if not blocked then raise exception 'Box returned with outstanding tool';end if;
 perform set_config('request.jwt.claim.sub',borrower.auth_user_id::text,true);perform public.toolbox_command('mark_tool_returned',jsonb_build_object('eventId',e));
 perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);perform public.toolbox_command('confirm_tool_return',jsonb_build_object('eventId',e,'ok',true));
 perform set_config('request.jwt.claim.sub',inspector.auth_user_id::text,true);
 blocked:=false;begin perform public.toolbox_command('request_box_return',jsonb_build_object('operationId',o));exception when others then blocked:=true;end;if not blocked then raise exception 'Inspector received box';end if;
 perform set_config('request.jwt.claim.sub',keeper.auth_user_id::text,true);perform public.toolbox_command('request_box_return',jsonb_build_object('operationId',o));
 if (select status from public.toolboxes where id=b)='available' then raise exception 'Available before owner signature';end if;
 perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);perform public.toolbox_command('sign_box_return',jsonb_build_object('operationId',o));
 if (select status from public.toolboxes where id=b)<>'available' then raise exception 'Box not available';end if;
end $t$;
rollback;
select 'PASS: exclusive toolroom lending/return; recipient signature; scoped loan confirmation; outstanding tools block return' as result;
