begin; do $test$
declare keeper public.device_identities; inspector public.device_identities; owner_d public.device_identities; borrower public.device_identities; box uuid; op uuid; ev uuid; ev2 uuid; draft jsonb; failed boolean; dest text;
begin
select * into keeper from public.device_identities where coalesce(job_role,access_profile)='toolroom' limit 1;
select * into inspector from public.device_identities where coalesce(job_role,access_profile)='maintenance_inspector' limit 1;
select * into owner_d from public.device_identities where coalesce(job_role,access_profile)='mechanic' limit 1;
select * into borrower from public.device_identities where coalesce(job_role,access_profile)='mechanic' and employee_number<>owner_d.employee_number limit 1;
perform set_config('request.jwt.claim.sub',inspector.auth_user_id::text,true);
box:=public.create_toolbox_catalog('QA visual '||gen_random_uuid(),'Jacarepaguá');
draft:='[{"id":"drawer1","name":"Gaveta 1","photo":"","reviewed":true,"tools":[{"id":"socket10","name":"Soquete","measure":"10 mm","x":10,"y":10,"reviewed":true},{"id":"socket12","name":"Soquete","measure":"12 mm","x":30,"y":10,"reviewed":true}]}]';
perform public.save_toolbox_visual(box,draft,0);
failed:=false;begin perform public.save_toolbox_visual(box,draft,0);exception when others then failed:=true;end;if not failed then raise exception 'Stale write allowed';end if;
perform set_config('request.jwt.claim.sub',keeper.auth_user_id::text,true);
op:=(public.toolbox_command('assign_box',jsonb_build_object('boxId',box,'assignedTo',owner_d.employee_number))->>'id')::uuid;
perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);
failed:=false;begin perform public.save_toolbox_visual(box,draft,1);exception when others then failed:=true;end;if not failed then raise exception 'Mechanic edited catalog';end if;
perform public.toolbox_command('accept_box',jsonb_build_object('operationId',op));
perform set_config('request.jwt.claim.sub',borrower.auth_user_id::text,true);
ev:=(public.toolbox_command('take_tool',jsonb_build_object('boxId',box,'toolIds','["socket10"]'::jsonb,'aircraftPrefix',(select prefix from public.aircraft order by prefix limit 1)))->>'id')::uuid;
if (select tool_refs->0->>'drawer' from public.toolbox_events where id=ev)<>'Gaveta 1' then raise exception 'Missing snapshot';end if;
failed:=false;begin perform public.toolbox_command('take_tool',jsonb_build_object('boxId',box,'toolIds','["socket10"]'::jsonb));exception when others then failed:=true;end;if not failed then raise exception 'Duplicate loan';end if;
perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);
perform public.toolbox_command('approve_tool_withdrawal',jsonb_build_object('eventId',ev));
perform set_config('request.jwt.claim.sub',borrower.auth_user_id::text,true);
perform public.toolbox_command('correct_tool_selection',jsonb_build_object('eventId',ev,'toolIds','["socket12"]'::jsonb,'reason','Selecionei tamanho errado'));
if (select status from public.toolbox_events where id=ev)<>'awaiting_approval' then raise exception 'Correction skipped confirmation';end if;
if not exists(select 1 from public.toolbox_audit where target_id=ev and action='correct_tool_selection' and payload->'before'->0->>'id'='socket10') then raise exception 'Missing old selection audit';end if;
perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);
perform public.toolbox_command('approve_tool_withdrawal',jsonb_build_object('eventId',ev));
perform set_config('request.jwt.claim.sub',borrower.auth_user_id::text,true);perform public.toolbox_command('mark_tool_returned',jsonb_build_object('eventId',ev));
perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);perform public.toolbox_command('confirm_tool_return',jsonb_build_object('eventId',ev,'ok',true));
perform set_config('request.jwt.claim.sub',keeper.auth_user_id::text,true);perform public.toolbox_command('request_box_return',jsonb_build_object('operationId',op));
perform set_config('request.jwt.claim.sub',owner_d.auth_user_id::text,true);perform public.toolbox_command('sign_box_return',jsonb_build_object('operationId',op));
perform set_config('request.jwt.claim.sub',inspector.auth_user_id::text,true);
select name into dest from public.operation_bases where name<>'Jacarepaguá' and active limit 1;
perform public.move_toolbox_base(box,dest);
if (select base from public.toolboxes where id=box)<>'Jacarepaguá' then raise exception 'Origin changed before receipt';end if;
failed:=false;begin perform public.toolbox_command('assign_box',jsonb_build_object('boxId',box,'assignedTo',owner_d.employee_number));exception when others then failed:=true;end;if not failed then raise exception 'Assigned while in transit';end if;
perform public.receive_toolbox_transfer(box);
if (select base from public.toolboxes where id=box)<>dest then raise exception 'Destination not recorded';end if;
end $test$; rollback;select 'PASS: inspector catalog, revision, visual loans, duplicate prevention, signed correction, transfer release and receipt; rolled back' as result;
