"use client";
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Conversation={id:string;title:string;context_kind:string;context_id:string|null;context_label:string|null;created_at:string;updated_at:string};
export function AssistantConversations({client,user,onClose,renderConversation,context}:{client:SupabaseClient|null;user:string;onClose:()=>void;renderConversation:(id:string,onBack:()=>void,title:string)=>ReactNode;context?:{id:string;label:string}}){
 const [items,setItems]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[renaming,setRenaming]=useState<string|null>(null),[title,setTitle]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[more,setMore]=useState(false);
 const creationId=useRef<string|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const call=useCallback(async(action:string,payload:Record<string,unknown>={})=>{if(!client)throw Error('Sem conexão com as conversas.');const result=await client.rpc('personal_assistant',{p_action:action,p_payload:{...payload,employee:user}});if(result.error)throw Error('Não foi possível acessar as conversas. Tente novamente.');return result.data;},[client,user]);
 async function load(older=false){setBusy(true);setError('');try{const last=items.at(-1);const data=await call('conversations',older&&last?{beforeCreated:last.created_at,beforeId:last.id}:{}) as Conversation[];if(!mounted.current)return;setItems(previous=>older?[...new Map([...previous,...data].map(c=>[c.id,c])).values()]:data);setMore(data.length===50);}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setBusy(false);}}
 useEffect(()=>{let active=true;void call('conversations').then((data:Conversation[])=>{if(active){setItems(data);setMore(data.length===50);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[call]);
 useEffect(()=>{let active=true;const refresh=()=>{void call('conversations').then((data:Conversation[])=>{if(!active)return;setItems(data);setMore(data.length===50);setSelected(current=>current?data.find(c=>c.id===current.id)||current:null);}).catch(()=>{});};window.addEventListener('flight-ia-assistant-history-saved',refresh);return()=>{active=false;window.removeEventListener('flight-ia-assistant-history-saved',refresh);};},[call]);
 async function create(){if(busy)return;setBusy(true);setError('');try{const id=creationId.current??(creationId.current=crypto.randomUUID());const item=await call('create_conversation',{id,title:'Nova conversa',autoTitle:true,contextKind:context?'maintenance-draft':'general',contextId:context?.id,contextLabel:context?.label}) as Conversation;if(!mounted.current)return;setItems(previous=>[item,...previous.filter(c=>c.id!==item.id)]);setSelected(item);creationId.current=null;}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setBusy(false);}}
 async function rename(){if(busy||!renaming||!title.trim())return;setBusy(true);setError('');try{const item=await call('rename_conversation',{conversationId:renaming,title:title.trim()}) as Conversation;if(!mounted.current)return;setItems(previous=>previous.map(c=>c.id===item.id?item:c));setRenaming(null);}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setBusy(false);}}
 if(selected)return <div className="flex min-h-0 min-w-0 flex-1 flex-col">{renderConversation(selected.id,()=>setSelected(null),selected.title)}</div>;
 const visible=context?items.filter(item=>item.context_kind==='maintenance-draft'&&item.context_id===context.id):items;
 return <section aria-label="Conversas com a IA" className="flex min-h-0 flex-1 flex-col overflow-auto bg-white p-4 text-slate-900">
  <header className="flex items-center justify-between gap-2"><h2 className="font-bold">Conversas com a IA</h2><button type="button" onClick={onClose} className="min-h-11 rounded-lg border px-3">Voltar</button></header>
  {context?<p className="my-2 text-sm">Vinculada a: {context.label}</p>:null}
  <button type="button" disabled={busy} onClick={()=>void create()} className="my-3 min-h-11 rounded-xl bg-blue-700 px-4 font-bold text-white disabled:opacity-50">Nova conversa</button>
  {error?<p role="alert" className="text-sm text-red-700">{error}<button disabled={busy} onClick={()=>void load()} className="ml-2 underline">Tentar novamente</button></p>:null}
  {busy?<p role="status">Carregando…</p>:null}
  <div className="space-y-2">{visible.map(item=><div key={item.id} className="rounded-xl border p-3">
   {renaming===item.id?<form onSubmit={e=>{e.preventDefault();void rename();}} className="space-y-2"><label className="block text-sm font-bold">Título da conversa<input aria-label="Título da conversa" maxLength={120} disabled={busy} value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><div className="flex gap-2"><button disabled={busy||!title.trim()} className="min-h-11 rounded-lg bg-blue-700 px-3 text-white disabled:opacity-50">Salvar título</button><button type="button" disabled={busy} onClick={()=>setRenaming(null)} className="min-h-11 px-3">Cancelar</button></div></form>:<div className="flex items-start gap-2"><button type="button" disabled={busy} onClick={()=>setSelected(item)} className="min-h-11 min-w-0 flex-1 text-left"><strong className="block break-words">{item.title}</strong>{item.context_label?<span className="block text-xs">{item.context_label}</span>:null}<span className="text-xs text-slate-500">{new Date(item.updated_at).toLocaleString('pt-BR')}</span></button><button type="button" disabled={busy} aria-label={`Editar título de ${item.title}`} onClick={()=>{setRenaming(item.id);setTitle(item.title);}} className="min-h-11 shrink-0 px-2 text-sm text-blue-700">Editar título</button></div>}
  </div>)}</div>
  {!busy&&!visible.length&&!error?<p className="mt-3 text-sm">Nenhuma conversa aqui. Use “Nova conversa” para começar.</p>:null}
  {more?<button disabled={busy} onClick={()=>void load(true)} className="mt-3 min-h-11 text-blue-700">Carregar conversas anteriores</button>:null}
 </section>;
}
