'use client';
import {PreparationBadge} from "./flight-preparation";
import {useOperationalDay} from "./use-operational-day";
import {AssistantForm} from './assistant-form';
import {useAssistantScreen} from './assistant-workspace';
import {cockpitAssistantForm,cockpitAssistantPatch} from '@/lib/assistant-cockpit';
import {SearchableSelect} from './searchable-select';
import {WeatherResults} from './weather-results';
import {TechnicalAxes,TechnicalDraftReview} from './technical-case';
import type {TechnicalCase} from '@/lib/technical-case';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {FlightCounters,FlightChecksSummary} from './flight-counters';
import {OccurrenceLocation} from './occurrence-location';
import {MediaPicker,MediaGallery} from './record-media';
import {ChatCapture} from './chat-capture';
import {proposeDuty,occurrenceMedia,uploadOccurrenceMedia} from '@/lib/cockpit-automation';
import {BookOpen,X} from 'lucide-react';
import {CrewPresentation} from './crew-presentation';
import type {CrewFlight} from './crew-dashboard';
import {ModalLayer} from './modal-layer';
import {cockpitFields,cockpitLabels,cockpitDay,dateInput,dutyTotals,safeLink,valueOf,type CockpitEntry,type CockpitKind,type CockpitData} from '@/lib/cockpit';

type Signature=(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>;
type Aircraft={prefix:string;model?:string;base?:string};
type Person={employeeNumber:string;name:string;profile?:string};
const input='mt-1 min-h-11 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800';
const button='min-h-11 rounded-xl border border-blue-200 bg-white px-3 py-2 text-sm font-semibold text-blue-800 disabled:opacity-40';
const primary='min-h-11 rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40';
export async function cockpitCall<T>(client:SupabaseClient,action:string,payload:Record<string,unknown>={}):Promise<T>{const {data,error}=await client.rpc('cockpit',{p_action:action,p_payload:payload});if(error)throw Error(error.message);return data as T;}
export function openCockpit(flightId?:string,description?:string,section?:string){window.dispatchEvent(new CustomEvent('flight-ia-cockpit',{detail:{flightId,description,section}}));}
function useCockpit(client:SupabaseClient|null){const [rows,setRows]=useState<CockpitEntry[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(Boolean(client));const load=useCallback(async()=>{if(!client)return;try{setRows(await cockpitCall(client,'list'));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[client]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);const interval=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);window.addEventListener('focus',load);window.addEventListener('online',load);return()=>{clearTimeout(timer);clearInterval(interval);window.removeEventListener('focus',load);window.removeEventListener('online',load);};},[load]);return {rows,error,loading,load};}
function initialEntry(kind:CockpitKind,subject?:string,flight?:CrewFlight):CockpitEntry{return {id:crypto.randomUUID(),kind,subject:subject||null,flight_id:flight?.id||null,data:kind==='duty'?{date:cockpitDay()}:kind==='preparation'?{route:flight?.destination||'',plannedFuel:flight?.fuelAmount??'',fuelUnit:flight?.fuelUnit||''}:{},revision:0,created_by:'',updated_by:'',updated_at:''};}

export function Cockpit({client,user,profile,flights,aircraft,people,readOnly=false,requireSignature,onOpenTrail,initialFlightId,initialDescription,initialSection,initialEntryId}:{client:SupabaseClient|null;user:string;profile:string;flights:CrewFlight[];aircraft:Aircraft[];people:Person[];readOnly?:boolean;requireSignature:Signature;onOpenTrail:(flight:CrewFlight)=>void;initialFlightId?:string;initialDescription?:string;initialSection?:string;initialEntryId?:string}){
 const {rows,error,loading,load}=useCockpit(client);
 const [creating,setCreating]=useState(false),[creationError,setCreationError]=useState('');
 const [tab,setTab]=useState(initialDescription?'occurrence':(initialSection==='new-occurrence'?'occurrence':initialSection)||(initialFlightId?'preparation':'day')),[date,setDate]=useState(()=>flights.find(f=>f.id===initialFlightId)?.date||cockpitDay()),[flightId,setFlightId]=useState(initialFlightId||''),[editing,setEditing]=useState<CockpitEntry|null>(()=>{if(initialSection!=='new-occurrence'||readOnly)return null;const selected=flights.find(f=>f.id===initialFlightId);if(!selected)return null;return {...initialEntry('occurrence',undefined,selected),data:{prefix:selected.prefix,leg:`${selected.base} → ${selected.destination||''}`,crew:people.filter(p=>[selected.commander,selected.copilot,selected.flightAttendant].includes(p.employeeNumber)).map(p=>p.name).join(', '),at:new Date().toISOString(),description:initialDescription||''}};});
 const currentDay=useOperationalDay(),previousDay=useRef(currentDay);
 useEffect(()=>{const before=previousDay.current;previousDay.current=currentDay;if(before!==currentDay&&!flightId&&!editing)void Promise.resolve().then(()=>setDate(value=>value===before?currentDay:value));},[currentDay,flightId,editing]);
 const openedEntry=useRef<string|null>(null);
 useEffect(()=>{if(!initialEntryId||loading||openedEntry.current===initialEntryId)return;const entry=rows.find(row=>row.id===initialEntryId);const timer=setTimeout(()=>{openedEntry.current=initialEntryId;if(!entry){setCreationError('Registro indisponível no Cockpit atual.');return;}setEditing(entry);setFlightId(entry.flight_id||'');setTab(entry.kind==='document'||entry.kind==='diary'?'edb':entry.kind==='qualification'||entry.kind==='person'?'qualification':entry.kind==='location'?'ais':entry.kind);},0);return()=>clearTimeout(timer);},[initialEntryId,loading,rows]);
 useAssistantScreen({area:'Cockpit',section:tab,date,flightId,record:editing?{id:editing.id,kind:editing.kind,revision:editing.revision}:null});
 const coordinator=['admin','app_manager','coordination','dispatch','legacy'].includes(profile);
 const ownFlights=flights.filter(f=>!f.deletedAt&&(coordinator||[f.commander,f.copilot,f.flightAttendant].includes(user)));
 const available=ownFlights.filter(f=>f.date===date);const flight=ownFlights.find(f=>f.id===flightId);
 const linked=rows.filter(r=>r.flight_id===flight?.id);
 const person=rows.find(r=>r.kind==='person'&&r.subject===user)?.data||{};
 const crew=people.filter(p=>flight&&[flight.commander,flight.copilot,flight.flightAttendant].includes(p.employeeNumber)).map(p=>p.name).join(', ');
 async function create(kind:CockpitKind){if(creating)return;setCreationError('');const old=kind==='preparation'?linked.find(r=>r.kind===kind):kind==='duty'?rows.find(r=>r.kind===kind&&r.subject===user&&valueOf(r.data,'date')===date):undefined;const draft=old||initialEntry(kind,kind==='duty'?user:undefined,flight);if(kind==='duty'&&!old){draft.data.date=date;draft.flight_id=null;draft.id=`duty:${user}:${date}`;}if(kind==='occurrence'){draft.data={...draft.data,prefix:flight?.prefix||'',leg:flight?`${flight.base} → ${flight.destination||''}`:'',crew,description:initialDescription||'',at:new Date().toISOString()};}if(kind==='duty'&&client){setCreating(true);try{draft.data=await proposeDuty(client,user,date,ownFlights,draft.data);}catch(e){setCreationError((e as Error).message);}finally{setCreating(false);}}setEditing(draft);}
 const tabs=[['day','Meu dia'],['preparation','Preparação'],['ais','AIS'],['edb','Documentos / eDB'],['occurrence','Ocorrências'],['counter','Contadores'],['duty','Jornada'],['qualification','Minha situação']];
 return <section className="min-w-0 space-y-4 pb-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><BookOpen/>Cockpit</h1><p className="text-sm text-slate-600">Sua operação, registros e preparação do diário.</p></div><label className="text-sm">Data<input type="date" value={date} onChange={e=>{setDate(e.target.value);setFlightId('');}} className={input}/></label></header>
 <nav aria-label="Seções do Cockpit" className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)} className={tab===key?primary:button}>{label}</button>)}</nav>
 {creationError?<p role="alert">{creationError} A jornada pode ser preenchida manualmente.</p>:null}{creating?<p role="status">Preparando jornada com os registros realizados…</p>:null}
 {error?<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}<button className={button} onClick={()=>void load()}>Tentar novamente</button></p>:null}{loading?<p role="status">Consultando registros…</p>:null}
 {!['day','duty','qualification'].includes(tab)?<div className="rounded-2xl border bg-white p-4"><label className="text-sm font-semibold">Voo<SearchableSelect aria-label="Voo do Cockpit" className={input} value={flightId} onValueChange={e=>setFlightId(e)}><option value="">{tab==='occurrence'?'Sem voo específico':'Selecione um voo'}</option>{[...available,...(flight&&!available.some(f=>f.id===flight.id)?[flight]:[])].map(f=><option key={f.id} value={f.id}>{f.prefix} · {f.departure} · {f.destination||f.base}{f.cancelled?' · cancelado':''}</option>)}</SearchableSelect></label>{flight?<div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-sm"><span>{flight.prefix} · {flight.base} · {crew||'Tripulação a definir'}</span><button className={button} onClick={()=>onOpenTrail(flight)}>Abrir nos trilhos</button></div>:null}</div>:null}
 {tab==='day'?<><div className="flex flex-wrap gap-2"><button disabled={readOnly||loading||creating} className={primary} onClick={()=>create('duty')}>Minha jornada / registrar liberação</button></div><CrewPresentation client={client} user={user} flights={ownFlights} readOnly={readOnly} requireSignature={requireSignature} onOpenTrail={onOpenTrail}/><div className="grid gap-3 md:grid-cols-2">{available.map(f=><article key={f.id} className="rounded-2xl border bg-white p-4"><b>{f.prefix} · {f.departure}</b><PreparationBadge flightId={f.id}/><p>{f.base} → {f.destination||'Destino a definir'}</p><p className="text-sm text-slate-600">{rows.find(r=>r.kind==='preparation'&&r.flight_id===f.id)?.data.contract as string||'Contrato não informado'}</p><button className={button+' mt-3'} onClick={()=>{setFlightId(f.id);setTab('preparation');}}>Preparar este voo</button></article>)}</div>{!available.length?<p className="rounded-xl bg-white p-5">Nenhum voo vinculado nesta data.</p>:null}</>:null}
 {tab==='preparation'?<><p className="text-sm text-slate-600">Dados compartilhados com a coordenação. Os campos complementares são opcionais; combustível não é calculado nem aprovado automaticamente.</p><button disabled={!flight||readOnly||loading} className={primary} onClick={()=>create('preparation')}>Editar preparação do voo</button><EntryList rows={linked.filter(r=>r.kind==='preparation')} onOpen={setEditing}/></>:null}
 {tab==='ais'?<AisPanel locations={rows.filter(r=>r.kind==='location')} initialStation={valueOf(linked.find(r=>r.kind==='preparation')?.data||{},'originIcao')} client={client}/>:null}
 {tab==='edb'?<>{flight?<FlightChecksSummary key={flight.id} client={client} flightId={flight.id}/>:null}<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-950">Preparação local · ainda não enviada ao eDB. Aceite, assinatura, liberação e fechamento oficiais permanecem no Logbook.</p><div className="flex flex-wrap gap-2"><button disabled={!flight||readOnly||loading} className={primary} onClick={()=>create('diary')}>Novo rascunho do diário</button><button disabled={!flight||readOnly||loading} className={button} onClick={()=>create('document')}>Adicionar documento</button><button disabled={!flight} className={button} onClick={()=>{if(client&&flight)void cockpitCall(client,'export',{flightId:flight.id}).then(result=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`cockpit-${flight.prefix}-${flight.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}).catch(e=>alert(e.message));}}>Exportar preparação</button></div><EntryList rows={linked.filter(r=>['diary','document'].includes(r.kind))} onOpen={setEditing}/>{flight?<TechnicalSummary client={client} flightId={flight.id}/>:null}</>:null}
 {tab==='occurrence'?<><p className="text-sm text-slate-600">Registre a ocorrência e, se necessário, encaminhe como relato técnico ou caso técnico. O envio não concede acesso aos desfechos da manutenção.</p><button disabled={readOnly||loading||creating} className={primary} onClick={()=>create('occurrence')}>Registrar ocorrência / manutenção</button><EntryList rows={rows.filter(r=>r.kind==='occurrence'&&(!flight||r.flight_id===flight.id))} onOpen={setEditing}/></>:null}
 {tab==='counter'?<>{flight?<FlightCounters key={flight.id} expanded client={client} flightId={flight.id} readOnly={readOnly} requireSignature={requireSignature}/>:null}<details className="rounded-xl border bg-white p-3"><summary className="min-h-11 cursor-pointer py-2 text-sm font-bold">Leituras manuais e outros contadores</summary><p className="text-sm text-slate-600">Valores de referência para o eDB. O total acumulado corresponde ao valor atual; a diferença indica o incremento registrado.</p><button disabled={!flight||readOnly||loading} className={primary} onClick={()=>create('counter')}>Outro contador / leitura manual</button><EntryList rows={linked.filter(r=>r.kind==='counter'&&!valueOf(r.data,'eventMetric'))} onOpen={setEditing}/></details></>:null}
 {tab==='duty'?<><p className="rounded-xl bg-amber-50 p-3 text-sm">Apuração provisória dos registros informados. Não declara aptidão nem substitui a papeleta oficial. Horários usam o fuso deste aparelho.</p><button disabled={readOnly||loading||creating} className={primary} onClick={()=>create('duty')}>Abrir jornada desta data</button><EntryList rows={rows.filter(r=>r.kind==='duty'&&r.subject===user)} onOpen={setEditing}/><DutySummary rows={rows.filter(r=>r.subject===user)} date={date} person={person}/></>:null}
 {tab==='qualification'?<><p className="text-sm text-slate-600">Documentos cadastrados pela administração para sua matrícula. Vencimentos não bloqueiam automaticamente a operação.</p><EntryList rows={rows.filter(r=>r.kind==='qualification'&&r.subject===user)} onOpen={setEditing}/><DutySummary rows={rows.filter(r=>r.subject===user)} date={date} person={person}/></>:null}
 {editing&&client?<CockpitEditor key={editing.id} client={client} entry={editing} readOnly={readOnly||editing.kind==='qualification'} aircraft={aircraft} contracts={rows.filter(r=>r.kind==='contract')} dutyFlights={ownFlights} requireSignature={requireSignature} onClose={()=>setEditing(null)} onSaved={async row=>{setEditing(row);await load();}}/>:null}
 </section>;
}

function EntryList({rows,onOpen}:{rows:CockpitEntry[];onOpen:(row:CockpitEntry)=>void}){return <div className="grid min-w-0 gap-3 md:grid-cols-2">{rows.map(row=><button key={row.id} onClick={()=>onOpen(row)} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm"><span className="text-xs text-blue-700">{cockpitLabels[row.kind]}</span><strong className="mt-1 block break-words">{valueOf(row.data,'title')||valueOf(row.data,'date')||valueOf(row.data,'flightNumber')||'Sem título'}</strong><p className="mt-1 text-sm text-slate-600">{valueOf(row.data,'code')||valueOf(row.data,'equipment')||valueOf(row.data,'contract')}</p>{valueOf(row.data,'expires')?<p className={valueOf(row.data,'expires')<cockpitDay()?'mt-1 text-sm text-red-700':'mt-1 text-sm'}>Validade: {valueOf(row.data,'expires')} {valueOf(row.data,'expires')<cockpitDay()?'· vencido':''}</p>:null}{valueOf(row.data,'maintenanceCode')?<p className="text-sm text-blue-800">Enviado: {valueOf(row.data,'maintenanceCode')}</p>:null}<small className="mt-2 block text-slate-500">Atualizado em {new Date(row.updated_at).toLocaleString('pt-BR')}</small></button>)}{!rows.length?<p className="rounded-xl border border-dashed p-5 text-sm text-slate-600">Nenhum registro cadastrado.</p>:null}</div>;}

export function CockpitAdmin({client,people,requireSignature}:{client:SupabaseClient|null;people:Person[];requireSignature:Signature}){
 const {rows,error,loading,load}=useCockpit(client);const [person,setPerson]=useState(''),[editing,setEditing]=useState<CockpitEntry|null>(null),[profile,setProfile]=useState('');
 useEffect(()=>{if(!client||!person)return;let active=true;client.rpc('get_operational_assignments').then(({data})=>{if(active)setProfile(data?.find((p:{employee_number:string})=>p.employee_number===person)?.access_profile||'');});return()=>{active=false;};},[client,person]);
 const monthly=['toolroom','coordination','dispatch'].includes(profile),pilot=['commander','copilot','flight_attendant'].includes(profile);
 function create(kind:CockpitKind){const subject=['person','qualification'].includes(kind)?person:undefined;setEditing(kind==='person'?(rows.find(r=>r.kind==='person'&&r.subject===person)||{...initialEntry(kind,subject),data:{regime:monthly?'Mensalista':'Missão'}}):kind==='settings'?(rows.find(r=>r.kind===kind)||initialEntry(kind)):initialEntry(kind,subject));}
 return <details className="mt-4 rounded-xl border p-4"><summary className="cursor-pointer font-bold">Cockpit · cadastros, documentos e integrações</summary><div className="mt-4 space-y-4">{error?<p role="alert">{error}</p>:null}<label className="block text-sm font-semibold">Colaborador / matrícula<select className={input} value={person} onChange={e=>{setPerson(e.target.value);setProfile('');}}><option value="">Selecione</option>{people.map(p=><option key={p.employeeNumber} value={p.employeeNumber}>{p.name} · {p.employeeNumber}</option>)}</select></label>{person?<><p className="text-sm">{monthly?'Escala: Mensalista':pilot?'Tripulante · documentos e regras individuais':'Cadastro conforme a função registrada'}</p><div className="flex flex-wrap gap-2"><button type="button" disabled={loading} className={button} onClick={()=>create('person')}>Escala / identificação</button>{pilot?<button type="button" disabled={loading} className={button} onClick={()=>create('qualification')}>Cadastrar habilitação / certificado</button>:null}</div><EntryList rows={rows.filter(r=>r.subject===person&&['person','qualification'].includes(r.kind))} onOpen={setEditing}/></>:null}<div className="flex flex-wrap gap-2">{(['contract','location','settings'] as CockpitKind[]).map(k=><button type="button" disabled={loading} className={button} key={k} onClick={()=>create(k)}>{cockpitLabels[k]}</button>)}</div><EntryList rows={rows.filter(r=>['contract','location','settings'].includes(r.kind))} onOpen={setEditing}/><p className="text-sm text-slate-600">AISWEB e REDEMET: chaves serão configuradas no servidor. Não coloque senhas ou chaves nestes campos. eDB: aguardando identificação do fornecedor e acesso à API.</p></div>{editing&&client?<CockpitEditor key={editing.id} client={client} entry={editing} requireSignature={requireSignature} personProfile={profile} onClose={()=>setEditing(null)} onSaved={async row=>{setEditing(row);await load();}}/>:null}</details>;
}

export function CockpitPersonFields({client,employee,profile,requireSignature}:{client:SupabaseClient|null;employee:string;profile:string;requireSignature:Signature}){
 const [open,setOpen]=useState(false);
 if(['toolroom','coordination','dispatch'].includes(profile))return <p className="mt-3 rounded-lg bg-white p-3 text-sm">Escala: <b>Mensalista</b></p>;
 if(!['commander','copilot','flight_attendant'].includes(profile))return null;
 return <div className="mt-3 rounded-xl border bg-white p-3"><button type="button" className={button} aria-expanded={open} onClick={()=>setOpen(!open)}>Licenças, certificados e regras do tripulante</button>{open&&client?<PersonRecords client={client} employee={employee} requireSignature={requireSignature}/>:null}</div>;
}
function PersonRecords({client,employee,requireSignature}:{client:SupabaseClient;employee:string;requireSignature:Signature}){
 const {rows,error,load}=useCockpit(client);const [editing,setEditing]=useState<CockpitEntry|null>(null);
 return <div className="mt-3 space-y-3">{error?<p role="alert">{error}</p>:null}<div className="flex flex-wrap gap-2"><button className={button} onClick={()=>setEditing(initialEntry('qualification',employee))}>Nova habilitação / certificado</button><button className={button} onClick={()=>setEditing(rows.find(r=>r.kind==='person'&&r.subject===employee)||initialEntry('person',employee))}>Regras / histórico</button></div><EntryList rows={rows.filter(r=>r.subject===employee&&r.kind==='qualification')} onOpen={setEditing}/>{editing?<CockpitEditor key={editing.id} client={client} entry={editing} requireSignature={requireSignature} onClose={()=>setEditing(null)} onSaved={async r=>{setEditing(r);await load();}}/>:null}</div>;
}

export function CockpitEditor({client,entry,readOnly=false,aircraft=[],contracts=[],dutyFlights=[],personProfile,requireSignature,onClose,onSaved}:{client:SupabaseClient;entry:CockpitEntry;readOnly?:boolean;aircraft?:Aircraft[];contracts?:CockpitEntry[];dutyFlights?:CrewFlight[];personProfile?:string;requireSignature:Signature;onClose:()=>void;onSaved:(row:CockpitEntry)=>Promise<void>}){
 const [files,setFiles]=useState<File[]>([]),[recording,setRecording]=useState(false);
 const [data,setData]=useState<CockpitData>(entry.data),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<{revision:number;actor:string;at:string}[]>([]),[reason,setReason]=useState('');
 const [assistantUser,setAssistantUser]=useState('');
 useEffect(()=>{let active=true;void client.rpc('refresh_current_device').then(({data:identity,error})=>{if(active&&!error&&typeof identity?.employeeNumber==='string')setAssistantUser(identity.employeeNumber);});return()=>{active=false;};},[client]);
 const monthly=entry.kind==='person'&&['toolroom','coordination','dispatch'].includes(personProfile||'');
 const fields=cockpitFields[entry.kind].filter(f=>!monthly||['regime','externalEmployeeId'].includes(f.key));
 const locked=readOnly||Boolean(valueOf(entry.data,'preparedAt'));const changed=valueOf(data,'_proposalPending')==='yes'||files.length>0||JSON.stringify(data)!==JSON.stringify(entry.data);
 const assistantForm=cockpitAssistantForm(entry,data,aircraft,monthly);
 async function action(name:string,override?:CockpitData){if(busy||recording)return;setBusy(true);setError('');setMessage('');try{await requireSignature(async()=>{let payload={...(override||data)};delete payload._proposalPending;if(name==='save'&&entry.kind==='occurrence'){if(!valueOf(payload,'title').trim()||!valueOf(payload,'description').trim())throw Error('Informe o título e a descrição da ocorrência.');if(occurrenceMedia(payload).length+files.length>30)throw Error('Limite de 30 anexos por ocorrência.');const media=await uploadOccurrenceMedia(client,entry.id,files);payload={...payload,mediaJson:JSON.stringify([...new Map([...occurrenceMedia(payload),...media].map(item=>[item.id,item])).values()])};}const row=await cockpitCall<CockpitEntry>(client,name,{id:entry.id,kind:entry.kind,subject:entry.subject,flightId:entry.flight_id,revision:entry.revision,data:payload,reason});setFiles([]);setData(row.data);await onSaved(row);setMessage(name==='send_maintenance'?'Enviado à manutenção.':'Registro salvo.');},name==='acknowledge'?'Registrar ciência local':'Confirmar registro do Cockpit');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function importCheckin(){setBusy(true);setError('');try{const proposal=await proposeDuty(client,entry.subject||'',valueOf(data,'date'),dutyFlights,data);setData(proposal);setMessage('Referências atualizadas. Seus horários já preenchidos foram preservados. Confira e salve.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <ModalLayer><div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 p-2 sm:p-5"><section role="dialog" aria-modal="true" aria-label={cockpitLabels[entry.kind]} className="flex max-h-[92dvh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-xl"><header className="flex shrink-0 items-center justify-between border-b p-4"><h2 className="font-bold">{cockpitLabels[entry.kind]}</h2><button type="button" disabled={busy} aria-label="Fechar cadastro Cockpit" onClick={onClose} className={button}><X size={20}/></button></header><div className="min-h-0 overflow-y-auto p-4">{assistantUser&&!locked?<AssistantForm client={client} user={assistantUser} disabled={busy||recording} form={assistantForm} onApply={values=>{const patch=cockpitAssistantPatch(assistantForm,entry,values);setData(current=>({...current,...patch,...(patch.latitude!==undefined||patch.longitude!==undefined?{locationAccuracy:'',locationSource:'Informada no rascunho'}:{})}));}}/>:null}<p className="mb-4 text-sm text-slate-600">{entry.kind==='duty'?'Horários no fuso deste aparelho. Confira os períodos antes de salvar.':'Informações complementares. Referências ao eDB são opcionais.'}</p>{entry.kind==='duty'?<button disabled={locked||busy} onClick={()=>void importCheckin()} className={button+' mb-3'}>Preencher com apresentação e voos realizados</button>:null}
 {entry.kind==='duty'?<div className="mb-4 flex flex-wrap gap-2">{[['mealStart','Iniciar refeição'],['mealEnd','Encerrar refeição'],['release','Registrar liberação']].map(([key,label])=><button key={key} className={button} disabled={locked||busy||valueOf(data,'date')!==cockpitDay()||Boolean(valueOf(data,key))||!valueOf(data,'presentation')||(key==='mealEnd'&&!valueOf(data,'mealStart'))} onClick={()=>void action('save',{...data,[key]:new Date().toISOString()})}>{label}</button>)}{valueOf(data,'airborneReference')!==''?<p className="w-full text-sm text-slate-600">Referência de decolagem a pouso: {valueOf(data,'airborneReference')} min. Confira o total de voo conforme o critério da operação; essa referência não preenche o total regulamentar nem encerra sua jornada.</p>:null}</div>:null}
 {entry.kind==='occurrence'?<OccurrenceLocation autoLocate={entry.revision===0} data={data} disabled={locked||busy} onChange={update=>setData(current=>({...current,...update} as CockpitData))}/>:null}
 {entry.kind==='person'&&!monthly&&!readOnly?<div className="mb-3 rounded-xl bg-amber-50 p-3 text-sm"><p>Limites dependem do enquadramento do operador e da regra validada.</p><button className={button+' mt-2'} onClick={()=>setData({...data,flightMonthly:'5400',flightYearly:'55800',ruleReference:'Referência inicial: Lei 13.475/2017, art. 33, IV. Validar enquadramento, RBAC 117 e acordo do operador.',reviewer:'',reviewDate:''})}>Preencher referência mensal / anual para helicópteros</button><a className="mt-2 block underline" href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/lei/l13475.htm" target="_blank" rel="noopener noreferrer">Consultar Lei 13.475/2017</a></div>:null}<div className="grid gap-4 sm:grid-cols-2">{entry.kind==='occurrence'?<label className="text-sm font-semibold">{entry.flight_id?'Aeronave vinculada ao voo':'Aeronave (opcional)'}<SearchableSelect disabled={locked||Boolean(entry.flight_id)} value={valueOf(data,'prefix')} onValueChange={e=>setData({...data,prefix:e})} className={input}><option value="">Sem aeronave</option>{aircraft.map(a=><option key={a.prefix}>{a.prefix}</option>)}</SearchableSelect></label>:null}{fields.map(f=>{const raw=valueOf(data,f.key);const val=f.type==='datetime-local'?dateInput(raw):raw;return <label key={f.key} className={'block text-sm font-semibold '+(f.type==='textarea'?'sm:col-span-2':'')}>{f.label}{f.options?<select className={input} disabled={locked||monthly&&f.key==='regime'} value={monthly&&f.key==='regime'?'Mensalista':val} onChange={e=>setData({...data,[f.key]:e.target.value})}><option value="">Não informado</option>{f.options.map(option=><option key={option} value={option}>{{fault:'Relato Técnico',discrepancy:'Caso Técnico',routine:'Rotina',urgent:'Urgente'}[option]||option}</option>)}</select>:f.type==='textarea'?<textarea disabled={locked} className={input} rows={3} value={val} onChange={e=>setData({...data,[f.key]:e.target.value})}/>:<input className={input} disabled={locked} type={f.type||'text'} min={f.type==='number'?0:undefined} step={f.type==='number'?'any':undefined} list={f.key==='contract'?'cockpit-contracts':undefined} value={val} onChange={e=>setData({...data,...(['latitude','longitude'].includes(f.key)?{locationAccuracy:'',locationSource:'Informada manualmente'}:{}),[f.key]:f.type==='datetime-local'&&e.target.value?new Date(e.target.value).toISOString():e.target.value})}/>}</label>;})}</div><datalist id="cockpit-contracts">{contracts.map(c=><option key={c.id} value={valueOf(c.data,'title')}/>)}</datalist>
 {entry.kind==='occurrence'?<div className="mt-4"><MediaGallery items={occurrenceMedia(data)} supabase={client}/>{!locked?<><MediaPicker files={files} onChange={setFiles} disabled={busy||recording}/><ChatCapture disabled={busy||files.length>=10} allowVideo={false} onRecording={setRecording} onError={setError} onSend={async file=>{setFiles(current=>[...current,file]);}}/><p className="text-xs text-slate-500">O áudio e os anexos serão enviados ao salvar a ocorrência.</p></>:null}</div>:null}
 {valueOf(data,'storagePath')?<StoredDocument client={client} path={valueOf(data,'storagePath')}/>:null}{['documentUrl','externalUrl','portalUrl'].map(key=>safeLink(valueOf(data,key))?<a key={key} target="_blank" rel="noopener noreferrer" href={safeLink(valueOf(data,key))!} className="mt-3 block text-blue-700 underline">Abrir {key==='documentUrl'?'documento':'Logbook oficial'}</a>:null)}
 {entry.kind==='counter'&&valueOf(entry.data,'delta')!==''?<p className="mt-3 rounded-xl bg-blue-50 p-3">Incremento registrado: {valueOf(entry.data,'delta')} · total acumulado: {valueOf(entry.data,'current')}</p>:null}
 {entry.kind==='duty'&&valueOf(entry.data,'elapsedMinutes')!==''?<p className="mt-3 text-sm">Período entre apresentação e liberação: {valueOf(entry.data,'elapsedMinutes')} min · refeição: {valueOf(entry.data,'mealMinutes')} min. Apuração da jornada depende da regra cadastrada.</p>:null}
 {entry.data.acknowledgment&&typeof entry.data.acknowledgment==='object'?<p className="mt-3 text-sm text-green-800">Ciência local: mat. {entry.data.acknowledgment.actor} · {new Date(entry.data.acknowledgment.at).toLocaleString('pt-BR')}. Não é assinatura do eDB.</p>:null}
 {error?<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-red-800">{error}</p>:null}{message?<p role="status" className="mt-3 text-green-800">{message}</p>:null}
 <div className="mt-5 flex flex-wrap gap-2">{!locked?<button disabled={busy||recording} className={primary} onClick={()=>void action('save')}>Salvar</button>:null}{entry.revision>0&&!readOnly? <>{['diary','document','duty'].includes(entry.kind)&&!locked?<button disabled={busy||changed} className={button} onClick={()=>void action('acknowledge')}>Dar ciência local</button>:null}{entry.kind==='occurrence'&&!valueOf(entry.data,'maintenanceId')?<button disabled={busy||changed} className={button} onClick={()=>void action('send_maintenance')}>Enviar à manutenção</button>:null}{entry.kind==='diary'&&!locked?<button disabled={busy||changed} className={button} onClick={()=>void action('prepare_export')}>Concluir preparação local</button>:null}</>:null}{entry.revision>0?<button disabled={busy} className={button} onClick={()=>void cockpitCall<typeof history>(client,'history',{id:entry.id}).then(setHistory).catch(e=>setError(e.message))}>Histórico de alterações</button>:null}</div>
 {entry.kind==='diary'&&valueOf(entry.data,'preparedAt')&&!readOnly?<div className="mt-3"><label className="text-sm">Motivo para reabrir o rascunho<input className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} className={button+' mt-2'} onClick={()=>void action('reopen')}>Reabrir preparação</button></div>:null}
 {entry.kind==='occurrence'?<TechnicalDraftReview role="pilot" text={valueOf(data,'description')}/>:null}{history.map(h=><p key={h.revision} className="mt-2 text-xs text-slate-600">Versão {h.revision} · mat. {h.actor} · {new Date(h.at).toLocaleString('pt-BR')}</p>)}
 </div></section></div></ModalLayer>;
}

function DutySummary({rows,date,person}:{rows:CockpitEntry[];date:string;person:CockpitData}){const totals=dutyTotals(rows,date,person);const duties=rows.filter(r=>r.kind==='duty'&&valueOf(r.data,'date').startsWith(date.slice(0,7))&&valueOf(r.data,'date')<=date);const knownMeal=['Excluir intervalo registrado da jornada','Manter intervalo na jornada'].includes(valueOf(person,'mealRule'));const duty=knownMeal&&duties.every(r=>valueOf(r.data,'elapsedMinutes')!=='')?duties.reduce((n,r)=>n+Number(r.data.elapsedMinutes||0)-(valueOf(person,'mealRule').startsWith('Excluir')?Number(r.data.mealMinutes||0):0),0):null;return <div className="rounded-2xl border bg-white p-4"><h2 className="font-bold">Horas registradas · referência {date}</h2><p className="mt-1 text-sm text-slate-600">Saldo de referência somente com regra validada e histórico informado. Não constitui liberação para voo.</p><div className="mt-3 grid grid-cols-2 gap-3 lg:grid-cols-5">{totals.map(t=><div key={t.label} className="rounded-xl bg-slate-50 p-3"><b className="text-sm">{t.label}</b><p>{Math.floor(t.minutes/60)}h {t.minutes%60}min</p><small>{t.remaining===null?'Saldo não apurado':`Saldo: ${t.remaining} min`}</small></div>)}</div><p className="mt-3 text-sm">Jornada mensal: {duty===null?'aguardando horários / regra de refeição':`${duty} min registrados`} · voo noturno mensal: {duties.reduce((n,r)=>n+Number(valueOf(r.data,'nightMinutes')||0),0)} min informados.</p></div>;}

function TechnicalSummary({client,flightId}:{client:SupabaseClient|null;flightId:string}){const [items,setItems]=useState<{code:string;title:string;type:string;technicalCase?:TechnicalCase}[]>([]),[error,setError]=useState('');useEffect(()=>{if(!client)return;let active=true;cockpitCall<typeof items>(client,'technical_history',{flightId}).then(rows=>{if(active)setItems(rows);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[client,flightId]);return <details className="rounded-xl border bg-white p-4"><summary className="font-bold">Resumo técnico da aeronave · registros em aberto</summary>{error?<p role="alert">{error}</p>:items.map(i=><div key={i.code} className="mt-2 text-sm">{i.code} · {i.title}<TechnicalAxes value={i.technicalCase}/></div>)}{!items.length&&!error?<p className="mt-2 text-sm">Nenhum registro aberto encontrado.</p>:null}<p className="mt-3 text-xs text-slate-500">Consulte o eDB para situação oficial. Conversas internas da manutenção não são exibidas aqui.</p></details>;}

function AisPanel({locations,initialStation,client}:{locations:CockpitEntry[];initialStation:string;client:SupabaseClient|null}){const [station,setStation]=useState(initialStation),[weather,setWeather]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function consult(){setBusy(true);setError('');setWeather('');try{const session=await client?.auth.getSession();const response=await fetch(`/api/cockpit-weather?station=${encodeURIComponent(station.trim().toUpperCase())}`,{headers:{Authorization:`Bearer ${session?.data.session?.access_token||''}`}});const result=await response.json();if(!response.ok)throw Error(result.error||'Consulta indisponível');setWeather(JSON.stringify(result,null,2));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <div className="space-y-4 rounded-2xl border bg-white p-4"><AisClocks timezone={valueOf(locations.find(l=>valueOf(l.data,'icao')===station)?.data||{},'timezone')}/><p className="text-sm">Fonte: DECEA. A consulta automática depende da chave da REDEMET no servidor. NOTAM e horários solares: consulte o AISWEB enquanto a integração não estiver configurada.</p><label className="block text-sm font-semibold">Aeródromo ICAO<input maxLength={4} className={input} value={station} onChange={e=>setStation(e.target.value.toUpperCase())} placeholder="Ex.: SBJR"/></label><div className="flex flex-wrap gap-2"><button disabled={busy||!/^[A-Z]{4}$/.test(station)} className={primary} onClick={()=>void consult()}>Consultar METAR / TAF</button><a className={button} target="_blank" rel="noopener noreferrer" href="https://aisweb.decea.mil.br/">Consultar AISWEB / NOTAM</a><a className={button} target="_blank" rel="noopener noreferrer" href="https://redemet.decea.mil.br/">Abrir REDEMET</a></div>{error?<p role="alert" className="text-amber-800">{error}</p>:null}{weather?<WeatherResults value={weather}/>:null}{locations.map(l=><article key={l.id} className="rounded-xl border p-3"><b>{valueOf(l.data,'title')} · {valueOf(l.data,'icao')}</b><p className="text-sm">{valueOf(l.data,'latitude')}, {valueOf(l.data,'longitude')} · {valueOf(l.data,'timezone')}</p><small>Fonte: {valueOf(l.data,'source')||'não informada'}</small>{['sunrise','sunset','nextSunrise'].map(key=><p key={key} className="mt-1 text-xs">{{sunrise:'Nascer do sol',sunset:'Pôr do sol',nextSunrise:'Próximo nascer do sol'}[key]}: {valueOf(l.data,key)?new Date(valueOf(l.data,key)).toLocaleString('pt-BR'):'Aguardando informação AISWEB'}</p>)}</article>)}</div>;}

function AisClocks({timezone}:{timezone:string}){const [now,setNow]=useState<Date|null>(null);useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[]);let local='Fuso cadastrado inválido';try{local=now?now.toLocaleString('pt-BR',timezone?{timeZone:timezone}:{}):'…';}catch{}return <div className="grid gap-2 sm:grid-cols-2"><p className="rounded-xl bg-blue-50 p-3 text-sm"><b>UTC</b><br/>{now?now.toLocaleString('pt-BR',{timeZone:'UTC'}):'…'}</p><p className="rounded-xl bg-blue-50 p-3 text-sm"><b>{timezone||'Horário deste aparelho'}</b><br/>{local}</p></div>;}

function StoredDocument({client,path}:{client:SupabaseClient;path:string}){const [url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true;client.storage.from('cockpit-documents').createSignedUrl(path,300).then(({data,error})=>{if(!active)return;if(error)setError('Não foi possível abrir o anexo: '+error.message);else setUrl(data.signedUrl);});return()=>{active=false;};},[client,path]);return error?<p role="alert" className="mt-3 text-red-700">{error}</p>:url?<a href={url} target="_blank" rel="noopener noreferrer" className="mt-3 block rounded-xl border p-3 text-blue-700 underline">Abrir / baixar anexo do voo</a>:<p className="mt-3 text-sm">Preparando acesso ao anexo…</p>;}
