"use client";
import {useCallback,useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
export type ReturnAlert={id:string;flight_id:string;prefix:string;base:string;reason:string;occurred_at:string;on_ground:boolean;closed_at:string|null;closed_by:string|null;closure_note:string|null};
export function useReturnAlerts(supabase:SupabaseClient|null,user:string,onError:(message:string)=>void){
 const [alerts,setAlerts]=useState<ReturnAlert[]>([]);const [seen,setSeen]=useState<Set<string>>(new Set());
 const load=useCallback(async()=>{if(!supabase)return;const [a,r]=await Promise.all([supabase.from('coordination_technical_alerts').select('*').order('occurred_at',{ascending:false}),supabase.from('coordination_alert_reads').select('alert_id').eq('employee_number',user)]);if(a.error||r.error){onError(`Alertas de retorno indisponíveis: ${(a.error||r.error)?.message}`);return;}setAlerts(a.data||[]);setSeen(new Set((r.data||[]).map(item=>item.alert_id)));},[supabase,user,onError]);
 useEffect(()=>{if(!supabase)return;const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),15000);const channel=supabase.channel(`coordination-return-${user}`).on('postgres_changes',{event:'*',schema:'public',table:'coordination_technical_alerts'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'coordination_alert_reads'},()=>void load()).subscribe();return()=>{clearTimeout(initial);clearInterval(timer);void supabase.removeChannel(channel);};},[supabase,user,load]);
 const update=async(id:string,action:'read'|'close',note='')=>{if(!supabase)return false;const{error}=await supabase.rpc('update_coordination_alert',{p_id:id,p_action:action,p_note:note});if(error){onError(error.message);return false;}await load();return true;};
 return {alerts,seen,update};
}
export function ReturnAlertCards({alerts,seen,update,onOpen}:{alerts:ReturnAlert[];seen:Set<string>;update:(id:string,action:'read'|'close',note?:string)=>Promise<boolean>;onOpen:(flightId:string)=>void}){
 const [closing,setClosing]=useState<string|null>(null);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const active=alerts.filter(a=>!a.closed_at);const history=alerts.filter(a=>a.closed_at);
 async function act(id:string,action:'read'|'close'){setBusy(true);try{if(await update(id,action,note)){setClosing(null);setNote('');}}finally{setBusy(false);}}
 return <><div className="space-y-2">{active.map(alert=><article key={alert.id} className={`rounded-xl border-l-4 p-3 ${seen.has(alert.id)?'border-amber-500 bg-amber-50':'border-red-600 bg-red-50'}`}><strong className="text-sm">{alert.prefix} · retorno por {alert.reason.toLowerCase()}</strong><p className="mt-1 text-xs font-bold">{alert.on_ground?'Aeronave no solo · acompanhamento pendente':'Retorno registrado · em voo'}</p><p className="mt-1 text-xs">{new Date(alert.occurred_at).toLocaleString('pt-BR')} · {alert.base}</p><p className="mt-1 text-xs">{seen.has(alert.id)?'Ciente · ocorrência ainda aberta':'Novo alerta crítico'}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>onOpen(alert.flight_id)} className="rounded-lg border bg-white px-2 py-1 text-xs font-bold">Abrir no Trilho</button>{!seen.has(alert.id)?<button disabled={busy} onClick={()=>void act(alert.id,'read')} className="rounded-lg border bg-white px-2 py-1 text-xs font-bold">Dar ciência</button>:null}<button onClick={()=>{setClosing(alert.id);setNote('');}} className="rounded-lg border bg-white px-2 py-1 text-xs font-bold">Encerrar acompanhamento</button></div>{closing===alert.id?<div className="mt-3"><p className="text-xs">Encerra o alerta da coordenação, sem encerrar a relato técnico ou liberar a aeronave.</p><textarea aria-label="Motivo do encerramento do acompanhamento" value={note} onChange={e=>setNote(e.target.value)} className="mt-2 w-full rounded-lg border bg-white p-2 text-sm"/><button disabled={busy||!note.trim()} onClick={()=>void act(alert.id,'close')} className="mt-2 rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Confirmar encerramento</button><button onClick={()=>setClosing(null)} className="ml-2 text-xs">Cancelar</button></div>:null}</article>)}</div>{history.length?<details className="mt-3 rounded-xl border p-3"><summary className="cursor-pointer text-xs font-bold">Histórico de retornos acompanhados ({history.length})</summary>{history.map(a=><div key={a.id} className="mt-2 border-t pt-2 text-xs"><strong>{a.prefix} · {a.reason}</strong><p>{new Date(a.occurred_at).toLocaleString('pt-BR')}</p><p>Encerrado em {new Date(a.closed_at!).toLocaleString('pt-BR')} · Mat. {a.closed_by}</p><p>{a.closure_note}</p><button onClick={()=>onOpen(a.flight_id)} className="mt-1 text-blue-700">Abrir no Trilho</button></div>)}</details>:null}</>;
}

