"use client";

import { useEffect, useMemo, useState, useSyncExternalStore } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { CalendarClock, Clock3, Fuel, Gauge, MapPin, Plane, Wind, Wrench, X } from "lucide-react";

export type CrewFlight = {
  id:string; prefix:string; model:string; base:string; date:string; departure:string; destination?:string;
  duration:number; fuelAmount:number; fuelUnit:string; planningStatus?:"planned"|"confirmed";
  commander?:string; copilot?:string; flightAttendant?:string; cancelled?:boolean; actualEngineStart?:string|null; actualShutdown?:string|null;
};
export type CrewMaintenanceAction={id:string;prefix:string;title:string;description:string;assignedTo:string;status:string;createdAt:string};
type Action=CrewMaintenanceAction;
type PostData={id:string;title:string;category:string;createdAt:string;actions?:Action[]};
type Row={id:string;data:PostData};
type DryingTask={id:string;prefix:string;model:string;base:string;reason:string;status:"pending"|"completed";triggered_by:string|null;triggered_at:string;completed_by:string|null;completed_at:string|null};

const today=()=>{const value=new Date();return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;};
const duration=(hours:number)=>{const minutes=Math.round(hours*60);return `${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;};
const assigned=(value:string,user:string,fleets:string[])=>{const text=value.toLocaleLowerCase("pt-BR");return text===user.toLocaleLowerCase("pt-BR")||text.includes(`mat. ${user.toLocaleLowerCase("pt-BR")}`)||text.includes("toda")||text.includes("equipe")||fleets.some((fleet)=>text.includes(fleet.toLocaleLowerCase("pt-BR")));};
const normalized=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/gi,"").toLowerCase();
const fleetMatches=(model:string,fleet:string)=>normalized(model).includes(normalized(fleet))||normalized(fleet).includes(normalized(model));

export function CrewDashboard({supabase,user,base,fleets,flights,requireSignature,onOpenTrail,onError}:{supabase:SupabaseClient|null;user:string;base:string;fleets:string[];flights:CrewFlight[];requireSignature:(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>;onOpenTrail:(flight:CrewFlight)=>void;onError:(message:string)=>void}){
  const [actions,setActions]=useState<Action[]>([]);
  const [selected,setSelected]=useState<CrewFlight|null>(null);
  const [dryingOpen,setDryingOpen]=useState(false);
  const [dryingTasks,setDryingTasks]=useState<DryingTask[]>([]);
  const fleetStorageKey=`flight-ia-crew-fleets-${user}`;
  const storedFleetSelection=useSyncExternalStore((listener)=>{window.addEventListener("crew-fleet-selection",listener);window.addEventListener("storage",listener);return()=>{window.removeEventListener("crew-fleet-selection",listener);window.removeEventListener("storage",listener);};},()=>localStorage.getItem(fleetStorageKey)??"",()=>"");
  const effectiveSelectedFleets=useMemo(()=>{try{const saved=JSON.parse(storedFleetSelection||"[]") as string[];const active=saved.filter((item)=>fleets.includes(item));return active.length?active:fleets;}catch{return fleets;}},[storedFleetSelection,fleets]);
  useEffect(()=>{if(!supabase)return;let active=true;const load=async()=>{const {data,error}=await supabase.from("operational_wall_posts").select("id,data").order("updated_at",{ascending:false});if(error){onError(`Programação da tripulação indisponível: ${error.message}`);return;}if(!active)return;const values=((data??[]) as Row[]).flatMap((row)=>(row.data.actions??[]).filter((item)=>{if(item.createdAt.slice(0,10)!==today())return false;const linkedToCrewAircraft=flights.some((flight)=>flight.prefix===item.prefix&&effectiveSelectedFleets.some((fleet)=>fleetMatches(flight.model,fleet)));return assigned(item.assignedTo,user,effectiveSelectedFleets)||linkedToCrewAircraft;}));setActions(values);};void load();const channel=supabase.channel(`crew-wall-${user}`).on("postgres_changes",{event:"*",schema:"public",table:"operational_wall_posts"},()=>void load()).subscribe();return()=>{active=false;void supabase.removeChannel(channel);};},[supabase,user,effectiveSelectedFleets,flights,onError]);
  useEffect(()=>{if(!supabase)return;let active=true;const load=async()=>{const {data,error}=await supabase.from("compressor_drying_tasks").select("*").eq("status","pending").order("triggered_at",{ascending:true});if(error){onError(`Fila de secagem indisponível: ${error.message}`);return;}if(active)setDryingTasks((data??[]) as DryingTask[]);};void load();const channel=supabase.channel(`compressor-drying-${user}`).on("postgres_changes",{event:"*",schema:"public",table:"compressor_drying_tasks"},()=>void load()).subscribe();return()=>{active=false;void supabase.removeChannel(channel);};},[supabase,user,onError]);
  async function completeDrying(task:DryingTask){if(!supabase)return;await requireSignature(async()=>{const {error}=await supabase.rpc("complete_compressor_drying",{p_task_id:task.id});if(error){onError(`Secagem não confirmada: ${error.message}`);return;}setDryingTasks((items)=>items.filter((item)=>item.id!==task.id));},`Confirmar secagem do ${task.prefix}`);}
  function toggleFleet(fleet:string){const next=effectiveSelectedFleets.includes(fleet)?effectiveSelectedFleets.filter((item)=>item!==fleet):[...effectiveSelectedFleets,fleet];const selection=next.length?next:[fleet];localStorage.setItem(fleetStorageKey,JSON.stringify(selection));window.dispatchEvent(new Event("crew-fleet-selection"));}
  const relevantDryingTasks=useMemo(()=>dryingTasks.filter((task)=>(!base||normalized(task.base)===normalized(base))&&effectiveSelectedFleets.some((fleet)=>fleetMatches(task.model,fleet))),[dryingTasks,base,effectiveSelectedFleets]);
  const daily=useMemo(()=>flights.filter((item)=>{
    const belongsToAuthorizedFleet=fleets.some((fleet)=>fleetMatches(item.model,fleet));
    const belongsToSelectedFleet=effectiveSelectedFleets.some((fleet)=>fleetMatches(item.model,fleet));
    return item.date===today()&&!item.cancelled&&(!base||normalized(item.base)===normalized(base))&&(!belongsToAuthorizedFleet||belongsToSelectedFleet);
  }).sort((a,b)=>a.departure.localeCompare(b.departure)),[flights,base,fleets,effectiveSelectedFleets]);
  const confirmed=daily.filter((item)=>item.planningStatus!=="planned");
  const planned=daily.filter((item)=>item.planningStatus==="planned");
  return <section className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-extrabold text-[#17324d]">Programação</h2><button onClick={()=>setDryingOpen(true)} className={`relative flex min-h-11 items-center gap-2 rounded-xl px-4 text-sm font-bold text-white ${relevantDryingTasks.length?"bg-amber-500":"bg-[#173f70]"}`}><Wind size={18}/>Secagens de compressores<b className={`grid h-6 min-w-6 place-items-center rounded-full px-1.5 text-xs ${relevantDryingTasks.length?"bg-white text-amber-700":"bg-white/20 text-white"}`}>{relevantDryingTasks.length}</b></button></header>
    {fleets.length>1?<details className="rounded-xl border border-[#d8e4ef] bg-white p-3"><summary className="cursor-pointer text-sm font-extrabold text-[#315b86]">Minhas frotas · {effectiveSelectedFleets.join(", ")}</summary><div className="mt-3 flex flex-wrap gap-2">{fleets.map((fleet)=><label key={fleet} className={`flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold ${effectiveSelectedFleets.includes(fleet)?"border-blue-300 bg-blue-50 text-blue-800":"border-[#d8e4ef] text-[#60758c]"}`}><input type="checkbox" checked={effectiveSelectedFleets.includes(fleet)} onChange={()=>toggleFleet(fleet)}/>{fleet}</label>)}</div><p className="mt-2 text-[10px] text-[#718197]">A seleção fica salva neste aparelho até você alterá-la.</p></details>:null}
    <Summary actions={actions.length} confirmed={confirmed.length} planned={planned.length}/>
    <Section title="Giros e voos de manutenção" icon={<Wrench size={18}/>} empty="Nenhuma atividade de manutenção para você hoje.">{actions.map((item)=>{const done=item.status==="satisfactory"||item.status==="resolved";const failed=item.status==="nonconforming";return <article key={item.id} className={`rounded-xl border-l-4 bg-white p-4 shadow-sm ${failed?"border-red-500":done?"border-emerald-500":"border-violet-500"}`}><div className="flex items-start justify-between gap-2"><div><strong className="font-mono text-[#17324d]">{item.prefix}</strong><h3 className="mt-1 font-extrabold">{item.title}</h3></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${failed?"bg-red-100 text-red-800":done?"bg-emerald-100 text-emerald-800":"bg-violet-100 text-violet-800"}`}>{failed?"Não conforme":done?"OK · concluído":"Giro de manutenção"}</span></div><p className="mt-2 line-clamp-2 text-sm text-[#60758c]">{item.description}</p></article>})}</Section>
    <Section title="Voos confirmados" icon={<Plane size={18}/>} empty="Nenhum voo confirmado para você hoje.">{confirmed.map((flight)=><CrewFlightCard key={flight.id} flight={flight} confirmed onOpen={()=>setSelected(flight)}/>)}</Section>
    <Section title="Voos planejados" icon={<CalendarClock size={18}/>} empty="Nenhum outro voo planejado para você hoje.">{planned.map((flight)=><CrewFlightCard key={flight.id} flight={flight} onOpen={()=>setSelected(flight)}/>)}</Section>
    {selected?<FlightDetails flight={selected} onClose={()=>setSelected(null)} onOpenTrail={()=>onOpenTrail(selected)}/>:null}
    {dryingOpen?<DryingDialog fleets={effectiveSelectedFleets} tasks={relevantDryingTasks} onComplete={(task)=>void completeDrying(task)} onClose={()=>setDryingOpen(false)}/>:null}
  </section>;
}

export function useCrewMaintenanceActions(supabase:SupabaseClient|null,user:string,fleets:string[],enabled:boolean,onError:(message:string)=>void,subscriptionKey="main"){
  const [items,setItems]=useState<Action[]>([]);
  useEffect(()=>{if(!supabase||!enabled)return;let active=true;const load=async()=>{const {data,error}=await supabase.from("operational_wall_posts").select("id,data").order("updated_at",{ascending:false});if(error){onError(error.message);return;}if(active)setItems(((data??[]) as Row[]).flatMap((row)=>(row.data.actions??[]).filter((item)=>item.createdAt.slice(0,10)===today()&&assigned(item.assignedTo,user,fleets))));};void load();const channel=supabase.channel(`crew-maintenance-trail-${user}-${subscriptionKey}`).on("postgres_changes",{event:"*",schema:"public",table:"operational_wall_posts"},()=>void load()).subscribe();return()=>{active=false;void supabase.removeChannel(channel);};},[supabase,user,fleets,enabled,onError,subscriptionKey]);
  return enabled?items:[];
}

export function CrewMaintenanceCard({item}:{item:CrewMaintenanceAction}){return <article className="rounded-xl border-l-4 border-violet-500 bg-white p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><strong className="font-mono">{item.prefix}</strong><span className="rounded-full bg-violet-100 px-2 py-1 text-[10px] font-bold text-violet-800">Voo de manutenção</span></div><p className="mt-1 text-sm font-bold">{item.title}</p><p className="line-clamp-1 text-xs text-[#718197]">{item.description}</p></article>}

export function CrewMaintenanceTimeline({supabase,user,fleets,nextFlightAt,position,onError}:{supabase:SupabaseClient|null;user:string;fleets:string[];nextFlightAt:number;position:"before"|"after";onError:(message:string)=>void}){
  const items=useCrewMaintenanceActions(supabase,user,fleets,true,onError,position);
  const positioned=items.filter((item)=>position==="before"?Date.parse(item.createdAt)<=nextFlightAt:Date.parse(item.createdAt)>nextFlightAt).sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt));
  if(!positioned.length)return null;
  return <section className="mb-5"><div className="mb-2 flex items-center gap-2 text-[#17324d]"><Wrench size={18}/><h2 className="font-extrabold">Voo de manutenção · conforme a próxima ação</h2></div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{positioned.map((item)=><CrewMaintenanceCard key={item.id} item={item}/>)}</div></section>;
}

export function CrewPlannedFlights({flights,onOpenTrail}:{flights:CrewFlight[];onOpenTrail:(flight:CrewFlight)=>void}){
  const [selected,setSelected]=useState<CrewFlight|null>(null);
  if(!flights.length)return null;
  return <section className="mt-5 rounded-2xl border border-orange-200 bg-orange-50/50 p-4"><h2 className="mb-1 flex items-center gap-2 font-extrabold text-[#17324d]"><CalendarClock size={18}/>Planejados · ainda não confirmados</h2><p className="mb-3 text-xs text-[#718197]">Aparecem por último porque ainda dependem da confirmação da Coordenação.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{flights.map((flight)=><CrewFlightCard key={flight.id} flight={flight} onOpen={()=>setSelected(flight)}/>)}</div>{selected?<FlightDetails flight={selected} onClose={()=>setSelected(null)} onOpenTrail={()=>onOpenTrail(selected)}/>:null}</section>;
}

function Summary({actions,confirmed,planned}:{actions:number;confirmed:number;planned:number}){return <div className="grid grid-cols-3 gap-2">{[["Manutenção",actions,"bg-violet-50 text-violet-800"],["Confirmados",confirmed,"bg-blue-50 text-blue-800"],["Planejados",planned,"bg-orange-50 text-orange-800"]].map(([label,count,tone])=><div key={String(label)} className={`rounded-xl p-3 text-center ${tone}`}><strong className="block text-xl">{count}</strong><span className="text-[10px] font-bold uppercase tracking-wide">{label}</span></div>)}</div>}
function Section({title,icon,empty,children}:{title:string;icon:React.ReactNode;empty:string;children:React.ReactNode}){const has=Array.isArray(children)?children.length>0:Boolean(children);return <section className="rounded-2xl border border-[#d8e4ef] bg-[#f8fbff] p-4"><h2 className="mb-3 flex items-center gap-2 font-extrabold text-[#17324d]">{icon}{title}</h2>{has?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>:<p className="rounded-xl border border-dashed bg-white p-6 text-center text-sm text-[#718197]">{empty}</p>}</section>}
function CrewFlightCard({flight,confirmed=false,onOpen}:{flight:CrewFlight;confirmed?:boolean;onOpen:()=>void}){return <button onClick={onOpen} className={`rounded-xl border-l-4 bg-white p-4 text-left shadow-sm ${confirmed?"border-blue-500":"border-orange-500"}`}><div className="flex items-start justify-between gap-2"><div><strong className="font-mono text-lg">{flight.prefix}</strong><p className="text-xs text-[#718197]">{flight.model}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${confirmed?"bg-blue-100 text-blue-800":"bg-orange-100 text-orange-800"}`}>{confirmed?"Confirmado":"Planejado"}</span></div><div className="mt-3 flex items-center justify-between text-xs font-semibold"><span className="flex items-center gap-1"><Clock3 size={13}/>{flight.departure}</span><span className="flex items-center gap-1"><MapPin size={13}/>{flight.destination||"Destino a informar"}</span></div></button>}
function FlightDetails({flight,onClose,onOpenTrail}:{flight:CrewFlight;onClose:()=>void;onOpenTrail:()=>void}){return <div className="fixed inset-0 z-[80] grid place-items-end bg-[#071a30]/60 sm:place-items-center sm:p-4" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="w-full rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-2xl"><header className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#1769e0]">{flight.planningStatus==="planned"?"Voo planejado":"Voo confirmado"}</p><h2 className="mt-1 text-2xl font-extrabold">{flight.prefix}</h2><p className="text-sm text-[#718197]">{flight.model} · {flight.base}</p></div><button onClick={onClose} aria-label="Fechar"><X/></button></header><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info icon={<MapPin/>} label="Destino" value={flight.destination||"Não informado"}/><Info icon={<Clock3/>} label="Saída" value={flight.departure}/><Info icon={<Gauge/>} label="Tempo previsto" value={duration(flight.duration)}/><Info icon={<Fuel/>} label="Combustível" value={`${flight.fuelAmount} ${flight.fuelUnit}`}/></div><div className="mt-4 rounded-xl bg-[#f3f7fb] p-3 text-xs leading-6 text-[#52677f]"><p><b>Comandante:</b> {flight.commander||"Não informado"}</p><p><b>Copiloto:</b> {flight.copilot||"Não informado"}</p>{flight.flightAttendant?<p><b>Comissário:</b> {flight.flightAttendant}</p>:null}</div><button onClick={onOpenTrail} className="mt-5 w-full rounded-xl bg-[#1268d8] py-3 text-sm font-extrabold text-white">Abrir este voo no Trilho</button></section></div>}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl bg-[#f3f7fb] p-3"><span className="flex items-center gap-1 text-[10px] font-bold uppercase text-[#718197]">{icon}{label}</span><strong className="mt-1 block">{value}</strong></div>}
function DryingDialog({fleets,tasks,onComplete,onClose}:{fleets:string[];tasks:DryingTask[];onComplete:(task:DryingTask)=>void;onClose:()=>void}){return <div className="fixed inset-0 z-[80] grid place-items-end bg-[#071a30]/60 sm:place-items-center sm:p-4" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="max-h-[90dvh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-2xl"><header className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#1769e0]">Fim da operação</p><h2 className="mt-1 text-xl font-extrabold">Secagem de compressores</h2><p className="mt-1 text-xs text-[#718197]">{fleets.join(", ")} · somente aeronaves da sua base atual</p></div><button onClick={onClose} aria-label="Fechar"><X/></button></header><div className="mt-4 space-y-2">{tasks.map((task)=><article key={task.id} className="rounded-xl border-l-4 border-amber-500 bg-amber-50 p-4"><div className="flex items-start justify-between gap-2"><div><strong className="font-mono text-lg text-[#17324d]">{task.prefix}</strong><p className="text-xs font-semibold text-[#52677f]">{task.model} · {task.base}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold text-amber-800">Aguardando secagem</span></div><p className="mt-2 text-sm font-semibold">{task.reason}</p><p className="mt-1 text-[10px] text-[#718197]">Gerado em {new Date(task.triggered_at).toLocaleString("pt-BR")}{task.triggered_by?" · Mat. "+task.triggered_by:""}</p><button onClick={()=>onComplete(task)} className="mt-3 w-full rounded-lg bg-[#1268d8] py-2.5 text-xs font-extrabold text-white">Confirmar secagem concluída</button></article>)}{!tasks.length?<div className="rounded-xl border border-dashed p-8 text-center"><Wind className="mx-auto text-[#8aa2bb]"/><p className="mt-2 font-bold">Nenhuma secagem aguardando</p><p className="mt-1 text-xs text-[#718197]">Quando uma das três lavagens for confirmada, a aeronave aparecerá aqui.</p></div>:null}</div></section></div>}
