'use client';
import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {CrewFlight} from './crew-dashboard';
type Signature=(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>;
type Summary={date:string;timezone:string;flight:CrewFlight|null;scheduledAt:string|null;expectedAt:string|null;leadMinutes:number;canCheckin:boolean;changed:boolean;checkin:null|{checked_at:string;expected_at:string;flight_snapshot:CrewFlight}};
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const time=(value:string)=>new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
async function request<T>(client:SupabaseClient,action:string,payload:Record<string,unknown>={}):Promise<T>{const {data,error}=await client.rpc('crew_presentation',{p_action:action,p_payload:payload});if(error)throw error;return data as T;}
export function CrewPresentation({client,user,flights,readOnly=false,hideAfterCheckin=false,requireSignature,onOpenTrail}:{client:SupabaseClient|null;user:string;flights:CrewFlight[];readOnly?:boolean;hideAfterCheckin?:boolean;requireSignature:Signature;onOpenTrail:(flight:CrewFlight)=>void}){
 const [date,setDate]=useState(day),[data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const schedule=JSON.stringify(flights.map(f=>[f.id,f.date,f.departure,f.cancelled,f.deletedAt,f.commander,f.copilot,f.flightAttendant]));
 const previous=useRef<{date:string;key:string}|null>(null);const [scheduleChanged,setScheduleChanged]=useState(false);
 useEffect(()=>{let active=true;const load=async()=>{if(!client)return;try{const next=await request<Summary>(client,'summary',{user,date});if(active){const key=JSON.stringify([next.flight?.id,next.expectedAt]);if(previous.current?.date===date&&previous.current.key!==key)setScheduleChanged(true);previous.current={date,key};setData(next);setError('');}}catch(e){if(active)setError((e as Error).message);}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);window.addEventListener('focus',load);document.addEventListener('visibilitychange',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',load);};},[client,user,date,schedule]);
 async function checkin(){if(!client||readOnly||busy)return;setBusy(true);setError('');try{await requireSignature(async()=>{const next=await request<Summary>(client,'checkin',{date});setData(next);},'Registrar minha apresentação');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const current=data?.date===date?data:null;
 if(hideAfterCheckin&&current?.checkin)return null;
 return <section className="rounded-2xl border border-blue-200 bg-white p-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-blue-700">Cockpit</p><h2 className="text-lg font-bold">Minha apresentação</h2></div><label className="text-xs">Data da programação<input aria-label="Data da apresentação" type="date" value={date} onChange={e=>{if(e.target.value){setScheduleChanged(false);setDate(e.target.value);}}} className="ml-2 min-h-11 rounded-xl border px-2 text-base"/></label></header>{error?<p role="alert" className="mt-2 text-red-700">{error}</p>:null}{current?<>{current.flight&&current.expectedAt&&current.scheduledAt?<><div className="my-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-blue-50 p-3"><p className="text-sm">Apresentação prevista</p><strong className="text-xl">{time(current.expectedAt)}</strong><p className="text-xs">{current.leadMinutes} minutos antes · horário de Brasília</p></div><div className="p-3"><b>{current.flight.prefix} · {current.flight.maintenancePostId?'Voo/giro de manutenção':'Voo programado'}</b><p>{time(current.scheduledAt)} · {current.flight.base}</p><button onClick={()=>onOpenTrail(current.flight!)} className="mt-1 min-h-11 text-blue-700">Abrir no trilho</button></div></div><p className="text-xs text-slate-600">Calculado pela primeira atividade com horário definido em que você está na tripulação. Antecedência inicial para teste; ajustável em Cadastros.</p></>:<p className="my-3 text-sm">Nenhum voo ou giro com horário e tripulação definidos para você nesta data.</p>}{current.checkin?<div className="mt-3 rounded-xl bg-emerald-50 p-3"><b>Check-in registrado: {time(current.checkin.checked_at)}</b><p className="text-xs">Previsão no momento do registro: {time(current.checkin.expected_at)} · {current.checkin.flight_snapshot.prefix}</p></div>:<button disabled={busy||readOnly||!current.canCheckin} onClick={()=>void checkin()} className="mt-3 min-h-11 rounded-xl bg-blue-700 px-4 text-white disabled:opacity-40">{busy?'Registrando…':'Registrar minha apresentação'}</button>}{current.changed||scheduleChanged?<p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">A programação foi atualizada. Confira a previsão acima.{current.checkin?' Seu check-in original foi preservado.':''}</p>:null}{!current.checkin&&current.flight&&!current.canCheckin?<p className="mt-2 text-xs">O check-in fica disponível no dia da apresentação.</p>:null}</>:<p className="mt-3 text-sm">{client?'Consultando programação…':'Conecte-se para consultar a apresentação.'}</p>}</section>;
}
export function CrewPresentationSettings({client,requireSignature}:{client:SupabaseClient|null;requireSignature:Signature}){
 const [flight,setFlight]=useState(45),[maintenance,setMaintenance]=useState(45),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{if(!client)return;let active=true;request<{flight_minutes:number;maintenance_minutes:number}>(client,'settings').then(s=>{if(active){setFlight(s.flight_minutes);setMaintenance(s.maintenance_minutes);setLoaded(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[client]);
 async function save(){if(!client)return;setBusy(true);setError('');setMessage('');try{await requireSignature(async()=>{await request(client,'configure',{flightMinutes:flight,maintenanceMinutes:maintenance});setMessage('Antecedência atualizada. Os check-ins anteriores foram preservados.');},'Configurar apresentação da tripulação');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="rounded-xl border p-4 md:col-span-2"><summary className="cursor-pointer font-bold">Cockpit · antecedência da apresentação</summary><p className="my-3 text-sm">Parâmetros operacionais para teste. Os horários seguem Brasília, como a programação atual do aplicativo.</p><div className="grid gap-3 sm:grid-cols-2">{[{label:'Voos — minutos antes',value:flight,set:setFlight},{label:'Giros de manutenção — minutos antes',value:maintenance,set:setMaintenance}].map(item=><label key={item.label}>{item.label}<input type="number" min={0} max={1440} step={1} value={item.value} onChange={e=>item.set(Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>)}</div><button disabled={!loaded||busy||![flight,maintenance].every(v=>Number.isInteger(v)&&v>=0&&v<=1440)} onClick={()=>void save()} className="mt-3 min-h-11 rounded-xl bg-blue-700 px-4 text-white disabled:opacity-40">Salvar antecedência</button>{error?<p role="alert" className="mt-2 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-2 text-emerald-700">{message}</p>:null}</details>;
}
