'use client';
import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Suggestion={title:string;description:string;notes:string;snapshot:string};
export function DraftReviewEditor({client,user,model,title,description,onChange,onActive,disabled=false}:{client:SupabaseClient|null;user:string;model:string;title:string;description:string;onChange:(title:string,description:string)=>void;onActive:(active:boolean)=>void;disabled?:boolean}){
 const [open,setOpen]=useState(false),[suggestion,setSuggestion]=useState<Suggestion|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const applied=useRef('');const mobileText=useRef<HTMLTextAreaElement>(null);
 const snapshot=JSON.stringify({title,description,model});
 function activate(){if(disabled)return;setOpen(true);onActive(true);}
 function close(){setOpen(false);onActive(false);}
 useEffect(()=>{if(open&&window.matchMedia('(max-width: 1023px)').matches)mobileText.current?.focus();},[open]);
 useEffect(()=>{
  if(!open||disabled||title.trim().length+description.trim().length<8||applied.current===snapshot)return;
  const controller=new AbortController();let current=true;
  const timer=setTimeout(async()=>{setBusy(true);setError('');try{const session=await client?.auth.getSession();if(!session?.data.session)throw Error('Entre novamente para usar a revisão.');if(!current)return;const response=await fetch('/api/ai/draft-review',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.data.session.access_token}`,'x-employee':user},body:snapshot});const data=await response.json();if(!response.ok)throw Error(data.error);if(current)setSuggestion({...data,snapshot});}catch(e){if(current)setError((e as Error).message);}finally{if(current)setBusy(false);}},1500);
  return()=>{current=false;clearTimeout(timer);controller.abort();setBusy(false);};
 },[snapshot,open,disabled,client,user,title,description]);
 const current=suggestion?.snapshot===snapshot?suggestion:null;
 const fields=(mirror=false)=><><label className="block text-sm font-bold">{mirror?'Seu título':'Título'}<input aria-label={mirror?'Rascunho — título':'Título'} maxLength={500} disabled={disabled} value={title} onFocus={mirror?undefined:activate} onChange={e=>onChange(e.target.value,description)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="mt-3 block text-sm font-bold">{mirror?'Seu relato':'Descrição'}<textarea ref={mirror?mobileText:undefined} aria-label={mirror?'Rascunho — descrição':'Descrição'} maxLength={12000} disabled={disabled} rows={5} value={description} onFocus={mirror?undefined:activate} onChange={e=>onChange(title,e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label></>;
 return <div className={open?'grid min-w-0 gap-4 lg:grid-cols-2':''}><div>{fields()}<button type="button" disabled={disabled} onClick={activate} className="mt-2 text-sm font-bold text-blue-700">Revisar redação com IA</button></div>{open?<section aria-label="Revisão do rascunho" className="fixed inset-0 z-[250] overflow-y-auto bg-white p-4 pb-8 lg:static lg:z-auto lg:rounded-xl lg:border lg:bg-blue-50 lg:p-4"><header className="mb-3 flex items-center justify-between gap-3"><h3 className="font-bold">Revisão com IA</h3><button type="button" onClick={close} className="min-h-11 rounded-lg border px-3">Voltar ao formulário</button></header>{fields(true)}<div className="mt-4 rounded-xl border bg-white p-3"><h4 className="font-bold">Sugestão de redação</h4>{current?<><strong className="mt-3 block whitespace-pre-wrap">{current.title}</strong><p className="mt-2 whitespace-pre-wrap">{current.description}</p>{current.notes?<p className="mt-3 whitespace-pre-wrap text-sm text-amber-800">{current.notes}</p>:null}<button type="button" disabled={disabled} className="mt-3 min-h-11 rounded-lg bg-blue-700 px-4 font-bold text-white" onClick={()=>{applied.current=JSON.stringify({title:current.title,description:current.description,model});onChange(current.title,current.description);close();}}>Usar sugestão no relato</button></>:<p role="status" className="mt-2 text-sm text-slate-600">{busy?'Revisando…':'Escreva seu relato. A sugestão aparece após uma pausa na digitação.'}</p>}{error?<p role="alert" className="mt-2 text-sm text-red-700">{error}</p>:null}</div><p className="mt-3 text-xs text-slate-600">Revisão de redação. Confira os fatos antes de confirmar o relato. Nenhuma referência técnica foi consultada automaticamente.</p></section>:null}</div>;
}
