'use client';
import {AssistantForm} from './assistant-form';
import {useCallback,useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {OperationData,FlightCounter} from '@/lib/flight-operations';
import {type CockpitEntry,valueOf} from '@/lib/cockpit';

type Props={client:SupabaseClient|null;flightId:string;operation?:OperationData;readOnly?:boolean;expanded?:boolean;requireSignature:(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>};
const button='min-h-11 rounded-xl border border-blue-200 bg-white px-3 py-2 text-sm text-blue-800 disabled:opacity-40';
export function FlightChecksSummary({client,flightId}:{client:SupabaseClient|null;flightId:string}){
 const [data,setData]=useState<OperationData|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!client)return;let active=true;const load=async()=>{const result=await client.rpc('get_flight_operation',{p_flight_id:flightId});if(!active)return;if(result.error)setError(result.error.message);else{setData(result.data as OperationData);setError('');}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>{active=false;clearInterval(timer);};},[client,flightId]);
 const labels:Record<string,string>={drain:'Dreno',fuel:'Abastecimento',preflight:'Pré-voo',between:'Entre voos',hums:'HUMS',postflight:'Inspeção após voo'};
 return <details className="rounded-xl border bg-white p-3"><summary className="min-h-11 cursor-pointer py-2 text-sm font-bold">Verificações vinculadas ao voo</summary>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}{!data&&!error?<p>Consultando verificações…</p>:null}{data&&!Object.keys(data.checks).length?<p className="text-sm">Nenhuma verificação registrada.</p>:null}{Object.entries(data?.checks||{}).map(([key,check])=><div key={key} className="my-2 rounded-xl bg-slate-50 p-3 text-sm"><b>{labels[check.kind]||labels[key]||key}</b><p>{check.approval?check.approval.result==='ok'?'Conferido · OK':'Conferido · não conforme':check.execution?'Executado · aguardando conferência':'Pendente'}</p>{check.execution?<p>Execução: mat. {check.execution.actor} · {new Date(check.execution.at).toLocaleString('pt-BR')}</p>:null}{check.approval?<p>Conferência: mat. {check.approval.actor} · {new Date(check.approval.at).toLocaleString('pt-BR')}</p>:null}{check.targetFlightId!==flightId?<p>Vinculada à operação anterior desta aeronave.</p>:null}</div>)}</details>;
}
export function FlightCounters({client,flightId,operation,readOnly=false,expanded=false,requireSignature}:Props){
 const [open,setOpen]=useState(expanded),[loaded,setLoaded]=useState<OperationData|null>(null),[rows,setRows]=useState<CockpitEntry[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<FlightCounter|null>(null),[previous,setPrevious]=useState(''),[equipment,setEquipment]=useState(''),[message,setMessage]=useState('');
 const data=operation||loaded;
 const load=useCallback(async()=>{if(!client)return;try{
  const [counterResult,opResult]=await Promise.all([client.rpc('cockpit',{p_action:'list',p_payload:{kind:'counter'}}),operation?Promise.resolve({data:operation,error:null}):client.rpc('get_flight_operation',{p_flight_id:flightId})]);
  if(counterResult.error)throw counterResult.error;if(opResult.error)throw opResult.error;
  setRows((counterResult.data as CockpitEntry[]).filter(r=>r.flight_id===flightId));setLoaded(opResult.data as OperationData);setError('');
 }catch(e){setError((e as Error).message);}finally{setLoading(false);}},[client,flightId,operation]);
 useEffect(()=>{if(!open)return;let active=true;const refresh=()=>{if(active)void load();};const first=setTimeout(refresh,0),timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{active=false;clearTimeout(first);clearInterval(timer);window.removeEventListener('focus',refresh);};},[open,load]);
 function edit(metric:FlightCounter){const row=rows.find(r=>valueOf(r.data,'eventMetric')===metric.key);setSelected(metric);setPrevious(valueOf(row?.data||{},'previous'));setEquipment(valueOf(row?.data||{},'equipment'));setMessage('');}
 async function save(){if(!client||!data||!selected||busy)return;setBusy(true);setError('');try{
  const row=rows.find(r=>valueOf(r.data,'eventMetric')===selected.key);
  await requireSignature(async()=>{const {error}=await client.rpc('cockpit',{p_action:'save',p_payload:{id:row?.id||`flight-counter:${flightId}:${selected.key}`,kind:'counter',flightId,revision:row?.revision||0,data:{eventMetric:selected.key,sourceRevision:data.revision,previous:previous===''?null:Number(previous),equipment}}});if(error)throw error;setSelected(null);setMessage('Contador registrado neste voo. Disponível também no Cockpit.');await load();},'Conferir contador do voo');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details open={open} onToggle={e=>setOpen(e.currentTarget.open)} className="rounded-xl border border-blue-200 bg-slate-50 p-3"><summary className="min-h-11 cursor-pointer py-2 text-sm font-bold">Contadores do voo</summary>{open?<div className="space-y-3 text-sm"><p>Valores calculados dos eventos registrados. O saldo anterior é opcional; sem ele, fica registrado somente o incremento deste voo.</p>
 {loading?<p role="status">Consultando contadores…</p>:null}{!loading&&!data?.counters?<p>Contadores indisponíveis. Recarregue os registros.</p>:null}
 <div className="grid gap-2 sm:grid-cols-2">{data?.counters?.map(metric=>{const saved=rows.find(r=>valueOf(r.data,'eventMetric')===metric.key);const stale=saved&&(data.counterSource&&valueOf(saved.data,'sourceFingerprint')?valueOf(saved.data,'sourceFingerprint')!==data.counterSource:Number(valueOf(saved.data,'sourceRevision'))!==data.revision);return <div key={metric.key} className="min-w-0 rounded-xl border bg-white p-3"><strong>{metric.label}</strong><p>{metric.value} {metric.unit.toLowerCase()}{metric.inProgress?' · período em andamento':''}</p>{saved?<p className={stale?'text-amber-800':'text-green-800'}>{stale?'Eventos alterados · confira novamente':`Conferido${valueOf(saved.data,'current')?` · acumulado ${valueOf(saved.data,'current')}`:''}`}</p>:null}{!readOnly&&(data.canPilot||data.canSign)?<button disabled={busy||loading||metric.inProgress||!data.events.length} className={button+' mt-2'} onClick={()=>edit(metric)}>{saved?'Atualizar leitura':'Registrar leitura'}</button>:null}</div>;})}</div>
 {selected?<div className="rounded-xl border bg-white p-3"><AssistantForm client={client} disabled={busy||readOnly} form={{id:`counter:${flightId}:${selected.key}`,label:`Contador · ${selected.label}`,mode:'draft',revision:data?.revision,fields:{previous:{label:`Valor anterior informado em ${selected.unit}, sem calcular`,value:previous,maxLength:40},equipment:{label:'Equipamento',value:equipment,maxLength:200}}}} onApply={values=>{if(values.previous!==undefined){const n=Number(values.previous.replace(',','.'));if(!Number.isFinite(n)||n<0)throw Error('Valor anterior inválido.');}if(values.previous!==undefined)setPrevious(values.previous===''?'':String(Number(values.previous.replace(',','.'))));if(values.equipment!==undefined)setEquipment(values.equipment);}}/><b>{selected.label}</b><label className="mt-3 block">Valor anterior ({selected.unit.toLowerCase()}) · opcional<input aria-label="Valor anterior do contador" type="number" min="0" step="any" value={previous} onChange={e=>setPrevious(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label className="mt-3 block">Identificação do equipamento · opcional<input value={equipment} onChange={e=>setEquipment(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><p className="my-3">Incremento: {data?.counters?.find(m=>m.key===selected.key)?.value??selected.value}{previous!==''?` · acumulado proposto: ${Number(previous)+(data?.counters?.find(m=>m.key===selected.key)?.value??selected.value)}`:''}</p><button className={button} disabled={busy||previous!==''&&(!Number.isFinite(Number(previous))||Number(previous)<0)} onClick={()=>void save()}>Salvar leitura</button><button className={button+' ml-2'} disabled={busy} onClick={()=>setSelected(null)}>Cancelar</button></div>:null}
 <p className="text-xs text-slate-600">Decolagem a pouso e acionamentos não representam, por si só, horas regulamentares ou ciclos de vida dos componentes. Integração com o eDB ainda pendente.</p>
 {error?<p role="alert" className="text-red-700">{error}<button className={button+' ml-2'} onClick={()=>void load()}>Recarregar</button></p>:null}{message?<p role="status" className="text-green-800">{message}</p>:null}</div>:null}</details>;
}
