"use client";
import {useCallback,useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Mark={spot:string;confirmed:boolean;actor?:string;name?:string;at?:string;reason?:string};
type State=Mark&{history:Mark[];waiting?:string};
export function FlightPosition({supabase,flightId,compact=false,readOnly=false,requireSignature}:{supabase:SupabaseClient|null;flightId:string;compact?:boolean;readOnly?:boolean;requireSignature?:(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>}){
 const [data,setData]=useState<State|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!supabase)return;const r=await supabase.rpc('get_flight_position',{p_flight_id:flightId});if(r.error){setError(r.error.message);return;}setData(r.data);setError('');},[supabase,flightId]);
 useEffect(()=>{const initial=setTimeout(()=>void load(),0);const id=setInterval(()=>void load(),10000);const refresh=()=>void load();window.addEventListener('flight-position-change',refresh);window.addEventListener('focus',refresh);const ch=supabase?.channel(`position-${flightId}-${compact}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'shared_app_state'},refresh).subscribe();return()=>{clearTimeout(initial);clearInterval(id);window.removeEventListener('flight-position-change',refresh);window.removeEventListener('focus',refresh);if(ch)void supabase?.removeChannel(ch);};},[load,supabase,flightId,compact]);
 async function mark(confirmed:boolean){if(!data?.spot||!supabase||!requireSignature)return;setBusy(true);try{await requireSignature(async()=>{const r=await supabase.rpc('mark_flight_position',{p_flight_id:flightId,p_spot:data.spot,p_confirmed:confirmed,p_request_id:crypto.randomUUID()});if(r.error)throw r.error;setData(r.data);window.dispatchEvent(new Event('flight-position-change'));},'Assinar situação da aeronave na posição');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const text=data?.spot?`Posição: ${data.spot} · ${data.confirmed?'OK — aeronave na posição':'Não — aguardando deslocamento'}`:'Posição: aguardando coordenação';
 if(compact)return <span className="mt-2 block text-xs font-semibold">{error?'Posição indisponível no momento':text}{data?.waiting?<span className="mt-1 block text-amber-800">{data.waiting}</span>:null}</span>;
 return <section className="rounded-xl border bg-blue-50/50 p-3"><p className="text-xs font-bold">{text}</p>{data?.waiting?<p className="my-2 rounded-lg bg-amber-100 p-2 text-xs font-bold text-amber-900">{data.waiting}</p>:null}{data?.spot?<><div className="mt-2 flex items-center gap-2 text-xs"><span>Aeronave na posição?</span><button disabled={busy||readOnly||!requireSignature} onClick={()=>void mark(true)} className="rounded-lg border bg-white px-3 py-2 font-bold">OK</button><button disabled={busy||readOnly||!requireSignature} onClick={()=>void mark(false)} className="rounded-lg border bg-white px-3 py-2 font-bold">Não</button></div>{data.actor?<p className="mt-2 text-[11px]">{data.name||data.actor} · Mat. {data.actor} · {data.at?new Date(data.at).toLocaleString('pt-BR'):''}</p>:null}</>:null}{error?<p role="alert" className="text-xs text-red-700">{error}</p>:null}{data?.history.length?<details className="mt-2 text-xs"><summary className="cursor-pointer">Histórico da posição</summary>{[...data.history].reverse().map((m,i)=><p key={i} className="mt-2">{m.spot||'Sem posição'} · {m.reason|| (m.confirmed?'OK':'Não')} · {m.name||m.actor||'Sistema'} {m.actor?`(Mat. ${m.actor})`:''} · {m.at?new Date(m.at).toLocaleString('pt-BR'):''}</p>)}</details>:null}</section>;
}
