"use client";
import {sendOnEnter} from "@/lib/composer-keyboard";
import {useAssistantUploadCleanup} from "./use-assistant-upload-cleanup";
import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {Bot,Send,X} from 'lucide-react';
import {duplicateFlight,importFields,importIssues,importLabels,parseFlightImportAnswer,type FlightIdentity,type ImportAttachment,type ImportedFlight} from '@/lib/flight-import';
import {prepareAssistantFiles,removeAssistantFiles} from '@/lib/assistant-uploads';
import {FileAttachmentPicker,pastedFiles} from './file-attachment-picker';
import {ChatCapture} from './chat-capture';
type Row={id:string;flight:ImportedFlight;selected:boolean;added:boolean};
export function FlightImportAssistant({client,user,aircraft,existing,disabled,onAdd}:{client:SupabaseClient|null;user:string;aircraft:{prefix:string;available?:boolean}[];existing:FlightIdentity[];disabled:boolean;onAdd:(rows:{id:string;flight:ImportedFlight;source:string}[])=>string[]}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[attachments,setAttachments]=useState<ImportAttachment[]>([]),[rows,setRows]=useState<Row[]>([]),[reply,setReply]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[recording,setRecording]=useState(false);
  useAssistantUploadCleanup(client,attachments);
 const [exchanges,setExchanges]=useState<{message:string;reply:string}[]>([]);
 const active=useRef<AbortController|null>(null),source=useRef('Texto informado');
 useEffect(()=>()=>active.current?.abort(),[]);
 async function attach(files:File[]){if(busy||disabled||reading)return;setReading(true);setError('');try{setAttachments(await prepareAssistantFiles(client,files,attachments));}catch(e){setError((e as Error).message);}finally{setReading(false);}}
 async function transcribe(file:File){if(!client||busy||disabled)return;setReading(true);setError('');try{const {data}=await client.auth.getSession();if(!data.session)throw Error('Entre novamente.');const form=new FormData();form.set('file',file);const response=await fetch('/api/ai/transcribe',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`,'x-employee':user},body:form});const result=await response.json();if(!response.ok)throw Error(result.error);setMessage(current=>[current,result.text].filter(Boolean).join('\n'));}catch(e){setError((e as Error).message);}finally{setReading(false);}}
 async function analyze(){
  if(active.current||disabled||reading||(!message.trim()&&!attachments.length))return;
  const controller=new AbortController();active.current=controller;setBusy(true);setError('');
  try{
   const session=await client?.auth.getSession();if(!session?.data.session)throw Error('Entre novamente para usar a IA.');
   const response=await fetch('/api/ai/flight-import',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.data.session.access_token}`,'x-employee':user},body:JSON.stringify({message,attachments,previous:rows.map(r=>({...r.flight,rowId:r.id})),history:exchanges.slice(-4)})});
   const data=await response.json();if(!response.ok)throw Error(data.error||'A análise falhou.');if(active.current!==controller)return;
   const answer=parseFlightImportAnswer(data);if(attachments.length)source.current=attachments.map(a=>a.name).join(', ');
   setRows(answer.flights.map(flight=>{const previous=rows.find(r=>r.id===flight.rowId);return {id:previous?.id||crypto.randomUUID(),flight,selected:true,added:previous?.added===true&&importFields.every(k=>previous.flight[k]===flight[k])};}));
   setReply(answer.reply);setExchanges(current=>[...current,{message:message||attachments.map(a=>a.name).join(', '),reply:answer.reply}]);setMessage('');void removeAssistantFiles(client,attachments);setAttachments([]);
  }catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(active.current===controller){active.current=null;setBusy(false);}}
 }
 const identities=(row:Row)=>existing.filter(other=>other.id!==row.id);
 function add(){if(busy||disabled)return;const chosen=rows.filter(r=>r.selected&&!r.added&&!duplicateFlight(r.flight,identities(r)));const added=onAdd(chosen.map(r=>({id:r.id,flight:r.flight,source:source.current})));setRows(current=>current.map(r=>added.includes(r.id)?{...r,added:true,selected:false}:r));setReply(`${added.length} voo(s) aplicado(s) à programação. Use Programar para salvar; os campos pendentes podem ser completados depois.`);}
 return <section className="mb-4 rounded-2xl border border-blue-200 bg-blue-50 p-3"><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-blue-800"><Bot size={18}/>{open?'Recolher assistente da programação':'Montar programação com IA'}</button>
 {open?<div className="mt-3 space-y-3">
 {exchanges.length?<div className="max-h-60 space-y-2 overflow-auto" aria-label="Conversa da programação">{exchanges.map((entry,index)=><div key={index}><p className="ml-4 rounded-lg bg-emerald-100 p-2 text-sm whitespace-pre-wrap">{entry.message}</p><p className="mr-4 mt-1 rounded-lg bg-white p-2 text-sm whitespace-pre-wrap">{entry.reply}</p></div>)}</div>:null}
 <textarea onKeyDown={e=>sendOnEnter(e,analyze,disabled||busy||reading||recording||!client||(!message.trim()&&!attachments.length))} aria-label="Programação ou orientação" enterKeyHint="send" title="Enter envia · Shift+Enter cria uma nova linha" onPaste={e=>{const files=pastedFiles(e);if(files.length){e.preventDefault();void attach(files);}}} maxLength={16000} rows={3} value={message} disabled={busy||disabled} onChange={e=>setMessage(e.target.value)} placeholder="Fale, escreva ou cole uma imagem. Ex.: coloque todos os voos para hoje." className="w-full rounded-xl border bg-white p-3 text-sm"/>
 <FileAttachmentPicker accept="application/pdf,image/*,audio/*" disabled={busy||disabled||reading} onFiles={files=>files.length===1&&files[0].type.startsWith('audio/')?void transcribe(files[0]):void attach(files)}/>
 {attachments.map((file,index)=><p key={index} className="flex items-center gap-2 break-all text-xs">{file.name}<button type="button" disabled={busy||reading} aria-label={`Remover ${file.name}`} onClick={()=>{void removeAssistantFiles(client,[file]);setAttachments(current=>current.filter((_,i)=>i!==index));}}><X size={16}/></button></p>)}
 <div className="flex items-center gap-2"><ChatCapture allowVideo={false} disabled={busy||disabled||reading} onSend={transcribe} onRecording={setRecording} onError={setError}/><button type="button" disabled={disabled||busy||reading||recording||!client||(!message.trim()&&!attachments.length)} onClick={()=>void analyze()} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40"><Send size={17}/>{reading?'Preparando anexo…':busy?'Analisando…':'Enviar'}</button></div>
 <details className="text-xs text-slate-600"><summary className="cursor-pointer">Sobre os anexos e a privacidade</summary><p>Até 10 imagens ou PDFs, 20 MB por arquivo e 40 MB por mensagem. A análise utiliza a API OpenAI configurada pela organização. Até 100 voos por análise; resultados maiores podem ser divididos em partes.</p></details>
 {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}{reply?<p role="status" className="whitespace-pre-wrap text-sm text-blue-900">{reply}</p>:null}
 {rows.map((row,index)=>{const duplicate=duplicateFlight(row.flight,identities(row)),issues=importIssues(row.flight,aircraft);return <article key={row.id} className="rounded-xl border bg-white p-3"><label className="flex min-h-11 items-center gap-2 text-sm font-bold"><input type="checkbox" aria-label={`Incluir voo ${index+1}`} checked={row.selected&&!duplicate&&!row.added} disabled={row.added||duplicate||busy||disabled} onChange={e=>setRows(current=>current.map(r=>r.id===row.id?{...r,selected:e.target.checked}:r))}/>{`Voo ${index+1}`}{row.added?' · aplicado':duplicate?' · possível duplicidade':''}</label><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{importFields.map(key=><label key={key} className="text-xs font-bold">{importLabels[key]}<input aria-label={`${importLabels[key]} do voo encontrado ${index+1}`} maxLength={key==='destination'?300:80} value={row.flight[key]??''} disabled={busy||disabled} onChange={e=>setRows(current=>current.map(r=>r.id===row.id?{...r,added:false,selected:true,flight:{...r.flight,[key]:key==='prefix'?e.target.value.toUpperCase():e.target.value||null}}:r))} placeholder={key==='date'?'AAAA-MM-DD':key==='departure'||key==='duration'?'HH:MM':'Não informado'} className="mt-1 min-h-11 w-full rounded-lg border px-2 text-sm"/></label>)}</div>{row.flight.notes?<details className="mt-2 text-xs text-slate-600"><summary className="min-h-8 cursor-pointer">Origem e observações</summary><p className="whitespace-pre-wrap break-words">{row.flight.notes}</p></details>:null}{issues.length?<p className="mt-2 text-xs text-amber-800">Pendências: {issues.join('; ')}.</p>:null}</article>;})}
 {rows.length?<button type="button" onClick={add} disabled={disabled||busy||!rows.some(r=>r.selected&&!r.added&&!duplicateFlight(r.flight,identities(r)))} className="min-h-11 w-full rounded-xl bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40">Aplicar voos à programação</button>:null}
 </div>:null}</section>;
}
