"use client";
import {useEffect,useRef,useState} from "react";
import type {SupabaseClient} from "@supabase/supabase-js";
import {Bot,Upload,X} from "lucide-react";
import {duplicateFlight,importFields,importIssues,importLabels,parseFlightImportAnswer,type FlightIdentity,type ImportAttachment,type ImportedFlight} from "@/lib/flight-import";
type Row={id:string;flight:ImportedFlight;selected:boolean;added:boolean};

export function FlightImportAssistant({client,user,aircraft,existing,disabled,onAdd}:{client:SupabaseClient|null;user:string;aircraft:{prefix:string;available?:boolean}[];existing:FlightIdentity[];disabled:boolean;onAdd:(rows:{id:string;flight:ImportedFlight;source:string}[])=>string[]}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(""),[attachment,setAttachment]=useState<ImportAttachment>(),[rows,setRows]=useState<Row[]>([]),[reply,setReply]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reading,setReading]=useState(false);
 const active=useRef<AbortController|null>(null),fileVersion=useRef(0),source=useRef("");
 useEffect(()=>()=>{active.current?.abort();fileVersion.current++;},[]);
 async function filePicked(file?:File){const version=++fileVersion.current;setAttachment(undefined);setError("");setReading(false);if(!file)return;
  if(file.size>2000000||!["application/pdf","image/png","image/jpeg","image/webp"].includes(file.type)){setError("Use PDF, PNG, JPG ou WebP de até 2 MB.");return;}
  setReading(true);try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error("Não foi possível ler o arquivo."));reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file);});if(version===fileVersion.current)setAttachment({name:file.name.slice(0,180),data});}catch(e){if(version===fileVersion.current)setError((e as Error).message);}finally{if(version===fileVersion.current)setReading(false);}
 }
 async function analyze(){if(active.current||disabled||reading||(!message.trim()&&!attachment))return;const controller=new AbortController();active.current=controller;setBusy(true);setError("");
  try{const session=await client?.auth.getSession();if(!session?.data.session)throw Error("Entre novamente para usar a IA.");if(controller.signal.aborted)return;
   const response=await fetch("/api/ai/flight-import",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.data.session.access_token}`,"x-employee":user},body:JSON.stringify({message,attachment})});const data=await response.json();if(active.current!==controller)return;if(!response.ok)throw Error(data.error||"A análise falhou.");
   const answer=parseFlightImportAnswer(data);source.current=attachment?.name||"Texto informado à IA";setRows(answer.flights.map(flight=>({id:crypto.randomUUID(),flight,selected:true,added:false})));setReply(answer.reply);
  }catch(e){if(active.current===controller&&!controller.signal.aborted)setError((e as Error).message);}finally{if(active.current===controller){active.current=null;setBusy(false);}}
 }
 const identities=(row:Row)=>[...existing,...rows.filter(other=>other.id!==row.id&&other.added).map(other=>({prefix:other.flight.prefix||"",date:other.flight.date||"",departure:other.flight.departure||""}))];
 function add(){if(busy||disabled)return;const chosen=rows.filter(row=>row.selected&&!row.added&&!duplicateFlight(row.flight,identities(row)));const added=onAdd(chosen.map(row=>({id:row.id,flight:row.flight,source:source.current})));setRows(current=>current.map(row=>added.includes(row.id)?{...row,added:true,selected:false}:row));setReply(`${added.length} voo(s) adicionado(s) aos rascunhos. Complete os campos e use Programar para salvar. Itens duplicados foram mantidos para revisão.`);}
 return <section className="mb-4 rounded-2xl border border-blue-200 bg-blue-50 p-3"><button type="button" aria-expanded={open} onClick={()=>{if(open){active.current?.abort();active.current=null;setBusy(false);}setOpen(!open);}} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-blue-800"><Bot size={18}/>{open?"Recolher importação com IA":"Importar programação com IA"}</button>
 {open?<div className="mt-3 space-y-3"><p className="text-sm">Envie texto, uma imagem ou PDF de até 2 MB, com até 30 voos. Revise os resultados antes de adicionar aos rascunhos. O arquivo será enviado à OpenAI para análise.</p><label className="block text-sm font-semibold">Programação ou orientação<textarea maxLength={16000} rows={4} value={message} disabled={busy||disabled} onChange={e=>setMessage(e.target.value)} placeholder="Cole a programação. Se a data não estiver completa, informe o ano explicitamente." className="mt-1 w-full rounded-xl border bg-white p-3 text-sm"/></label><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border bg-white px-3 text-sm"><Upload size={16}/>Anexar programação<input aria-label="Arquivo da programação" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" disabled={busy||disabled||reading} className="sr-only" onChange={e=>void filePicked(e.target.files?.[0])}/></label>{attachment?<p className="flex items-center gap-2 break-all text-xs">{attachment.name}<button type="button" disabled={busy} aria-label="Remover anexo da programação" onClick={()=>{fileVersion.current++;setAttachment(undefined);}}><X size={16}/></button></p>:null}<button type="button" disabled={disabled||busy||reading||!client||(!message.trim()&&!attachment)} onClick={()=>void analyze()} className="ml-2 min-h-11 rounded-xl bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40">{reading?"Lendo arquivo…":busy?"Analisando…":"Analisar programação"}</button>{rows.length?<p className="text-xs text-slate-600">Uma nova análise substitui esta lista de sugestões; os rascunhos já adicionados são preservados.</p>:null}
 {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}{reply?<p role="status" className="whitespace-pre-wrap text-sm text-blue-900">{reply}</p>:null}
 {rows.map((row,index)=>{const duplicate=duplicateFlight(row.flight,identities(row)),issues=importIssues(row.flight,aircraft);return <article key={row.id} className="rounded-xl border bg-white p-3"><label className="flex min-h-11 items-center gap-2 text-sm font-bold"><input type="checkbox" aria-label={`Incluir voo ${index+1}`} checked={row.selected&&!duplicate} disabled={row.added||duplicate||busy||disabled} onChange={e=>setRows(current=>current.map(r=>r.id===row.id?{...r,selected:e.target.checked}:r))}/>{`Voo encontrado ${index+1}`}{row.added?" · adicionado":duplicate?" · possível duplicidade":""}</label><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{importFields.map(key=><label key={key} className="text-xs font-bold">{importLabels[key]}<input aria-label={`${importLabels[key]} do voo encontrado ${index+1}`} maxLength={key==="destination"?300:80} value={row.flight[key]??""} disabled={row.added||busy||disabled} onChange={e=>setRows(current=>current.map(r=>r.id===row.id?{...r,flight:{...r.flight,[key]:key==="prefix"?e.target.value.toUpperCase():e.target.value||null}}:r))} placeholder={key==="date"?"AAAA-MM-DD":key==="departure"||key==="duration"?"HH:MM":"Não informado"} className="mt-1 min-h-11 w-full rounded-lg border px-2 text-sm"/></label>)}</div>{row.flight.notes?<p className="mt-2 whitespace-pre-wrap text-xs text-slate-600">Origem e observações: {row.flight.notes}</p>:null}{!row.added&&issues.length?<p className="mt-2 text-xs text-amber-800">Para conferir: {issues.join("; ")}. Você pode completar nos rascunhos.</p>:null}</article>;})}
 {rows.length?<button type="button" onClick={add} disabled={disabled||busy||!rows.some(row=>row.selected&&!row.added&&!duplicateFlight(row.flight,identities(row)))} className="min-h-11 rounded-xl bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40">Adicionar selecionados aos rascunhos</button>:null}</div>:null}</section>;
}
