"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {SupabaseClient} from "@supabase/supabase-js";
import {ArrowLeft,MessageCircle,Plus,Send,UserPlus,Users,Paperclip,CheckCheck,Search,X} from "lucide-react";
import {ModalLayer} from "./modal-layer";
import {UserAvatar,type UserDirectory} from "./user-avatar";
import {MediaGallery} from "./record-media";
import {mediaFormat,type RecordMedia} from "@/lib/record-media";

type Person={id:string;name:string;role:string;base:string};
type Conversation={id:string;title:string;post_id:string|null;record_id?:string|null;participants:string;updated_at:string;unread:number;members:{id:string;name:string}[];message_count:number;last_message:string};
type Member={id:string;name:string;joinedAt:string;addedBy:string;lastReadId:number};
type Message={id:number;sender:string;body:string;attachments:RecordMedia[];kind:string;created_at:string};
type Detail={conversation:Conversation;members:Member[];messages:Message[]};
function conversationName(c:Pick<Conversation,"title"|"post_id"|"record_id">,members:{id:string;name:string}[],user:string){
 if(c.post_id||c.record_id)return c.title;
 const others=members.filter(m=>m.id!==user);
 if(members.length===2)return others[0]?.name||"Conversa";
 return c.title&&c.title!=="Conversa"?c.title:`Grupo · ${others.map(m=>m.name.split(" ")[0]).join(", ")}`;
}
function ChatAvatar({members,user,directory}:{members:{id:string;name:string}[];user:string;directory:UserDirectory}){
 const other=members.find(m=>m.id!==user);
 return members.length===2&&other?<UserAvatar employeeNumber={other.id} directory={{...directory,[other.id]:{...directory[other.id],name:other.name,avatar:directory[other.id]?.avatar||""}}}/>:<span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-800"><Users size={21}/></span>;
}
const field="w-full rounded-xl border border-slate-300 bg-white p-3 text-sm";
async function call<T>(client:SupabaseClient,action:string,payload:Record<string,unknown>={}):Promise<T>{const{data,error}=await client.rpc("internal_chat",{p_action:action,p_payload:payload});if(error)throw new Error(error.message);return data as T;}

export function InternalChat({supabase,user,directory,onOpenActivity}:{onOpenActivity:(id:string)=>void;supabase:SupabaseClient|null;user:string;directory:UserDirectory}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<string|null>(null),[conversations,setConversations]=useState<Conversation[]>([]),[people,setPeople]=useState<Person[]>([]),[creating,setCreating]=useState(false),[error,setError]=useState("");
 const [busy,setBusy]=useState(false),[search,setSearch]=useState(""),[recordCreation,setRecordCreation]=useState<string|null>(null);const createId=useRef<string|null>(null);
 const refresh=useCallback(async()=>{if(!supabase)return;try{setConversations(await call<Conversation[]>(supabase,"list"));setError("");}catch(e){if(open)setError((e as Error).message);}},[supabase,open]);
 useEffect(()=>{const first=setTimeout(()=>void refresh(),0);const t=setInterval(()=>{if(document.visibilityState==="visible")void refresh();},open?3000:10000);return()=>{clearTimeout(first);clearInterval(t);};},[refresh,open]);
 useEffect(()=>{if(!open||!supabase)return;let active=true;void call<Person[]>(supabase,"people").then(p=>{if(active)setPeople(p);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[open,supabase]);
 useEffect(()=>{const handler=(event:Event)=>{if(!supabase)return;const postId=(event as CustomEvent<string>).detail;if(!postId)return;setOpen(true);setCreating(false);setError("");setBusy(true);void call<{id:string}>(supabase,"create",{id:crypto.randomUUID(),postId}).then(r=>{setSelected(r.id);void refresh();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));};window.addEventListener("flight-ia-chat-activity",handler);return()=>window.removeEventListener("flight-ia-chat-activity",handler);},[supabase,refresh]);
 useEffect(()=>{const handler=(event:Event)=>{if(!supabase)return;const rid=(event as CustomEvent<string>).detail;setOpen(true);setError("");setBusy(true);void recordCall(supabase,"summary",rid).then(async summary=>{if(summary.exists){if(!summary.member)throw Error("Peça a um participante para incluir você na conversa desta ocorrência.");setCreating(false);setSelected(summary.conversation!.id);}else{setRecordCreation(rid);setCreating(true);setSelected(null);}}).catch(e=>setError(e.message)).finally(()=>setBusy(false));};window.addEventListener("flight-ia-chat-record",handler);return()=>window.removeEventListener("flight-ia-chat-record",handler);},[supabase]);
 useEffect(()=>{const handler=()=>setOpen(false);window.addEventListener("flight-ia-open-record",handler);return()=>window.removeEventListener("flight-ia-open-record",handler);},[]);
 const unread=conversations.reduce((n,c)=>n+Number(c.unread),0);
 return <><button type="button" aria-label={`Mensagens${unread?`, ${unread} não lidas`:""}`} title="Mensagens" onClick={()=>{setOpen(true);setError("");}} className="relative grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white/15 text-white"><MessageCircle size={20}/>{unread?<span className="absolute -right-1 -top-1 rounded-full bg-amber-300 px-1.5 text-[10px] font-bold text-blue-950">{unread>99?"99+":unread}</span>:null}</button>
 {open?<ModalLayer><div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/60 p-0 sm:p-5"><section role="dialog" aria-modal="true" aria-label="Mensagens internas" className="flex h-[100dvh] sm:h-[90dvh] min-h-0 w-full max-w-6xl flex-col overflow-hidden sm:rounded-2xl bg-white text-[#17324d] shadow-xl"><header className="flex shrink-0 items-center justify-between border-b p-3"><h2 className="font-bold">Mensagens</h2><div className="flex gap-2"><button aria-label="Nova conversa" onClick={()=>{createId.current=crypto.randomUUID();setRecordCreation(null);setCreating(true);setSelected(null);setError("");}} className="rounded-lg bg-blue-50 p-2 text-blue-700"><Plus size={20}/></button><button aria-label="Fechar mensagens" onClick={()=>setOpen(false)} className="p-2"><X size={20}/></button></div></header>{error?<p role="alert" className="shrink-0 bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{busy?<p className="p-3 text-sm">Abrindo conversa…</p>:null}
 <div className="flex min-h-0 flex-1">{!creating?<aside className={`${selected?"hidden sm:flex":"flex"} w-full shrink-0 flex-col border-r bg-white sm:w-80`} aria-label="Conversas">
 <label className="m-3 flex items-center gap-2 rounded-xl bg-slate-100 px-3 py-2"><Search size={17}/><input aria-label="Buscar conversas" placeholder="Pesquisar conversa" value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label>
 <div className="min-h-0 flex-1 overflow-y-auto">{conversations.filter(c=>`${c.title} ${c.participants}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(c=><button key={c.id} onClick={()=>{setSelected(c.id);setError("");}} className={`flex w-full items-center gap-3 border-b border-slate-100 p-4 text-left ${selected===c.id?"bg-emerald-50":"hover:bg-slate-50"}`}>
 <ChatAvatar members={c.members||[]} user={user} directory={directory}/><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="truncate text-sm">{conversationName(c,c.members||[],user)}</strong><time className="shrink-0 text-[10px] text-slate-500">{new Date(c.updated_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></span>
 {c.record_id?<span className="text-[10px] font-bold text-emerald-700">REGISTRO TÉCNICO</span>:c.post_id?<span className="text-[10px] font-bold text-emerald-700">ATIVIDADE</span>:c.members?.length>2?<span className="text-[10px] text-slate-500">Grupo · {c.members.length} participantes</span>:null}<span className="mt-1 flex items-center gap-2"><span className="flex-1 truncate text-xs text-slate-500">{c.last_message||"Conversa iniciada"}</span>{Number(c.unread)>0?<b className="rounded-full bg-emerald-600 px-2 py-0.5 text-[10px] text-white">{c.unread}</b>:null}</span></span></button>)}{!conversations.length?<p className="p-6 text-sm text-slate-500">Nenhuma conversa. Use + para começar.</p>:null}</div></aside>:null}
 {creating?<div className="min-w-0 flex-1 overflow-y-auto p-4"><h3 className="mb-3 font-bold">Nova conversa</h3><PeopleForm people={people.filter(p=>p.id!==user)} submitLabel="Iniciar conversa" onCancel={()=>setCreating(false)} onSubmit={async(members,title)=>{if(!supabase)return;const r=recordCreation?await openRecordChat(supabase,recordCreation,members):await call<{id:string}>(supabase,"create",{id:createId.current??(createId.current=crypto.randomUUID()),members,title});setCreating(false);setSelected(r.id);await refresh();}} titleField/></div>:selected&&supabase?<ChatThread key={selected} id={selected} client={supabase} user={user} directory={directory} people={people} onBack={()=>setSelected(null)} onRead={refresh} onOpenActivity={postId=>{setOpen(false);onOpenActivity(postId);}}/>:<p className="hidden p-6 text-sm text-slate-500 sm:block">Selecione uma conversa ou inicie uma nova.</p>}
 </div></section></div></ModalLayer>:null}</>;
}

function PeopleForm({people,onSubmit,onCancel,titleField=false,submitLabel}:{people:Person[];onSubmit:(ids:string[],title:string)=>Promise<void>;onCancel:()=>void;titleField?:boolean;submitLabel:string}){
 const [search,setSearch]=useState(""),[selected,setSelected]=useState<string[]>([]),[title,setTitle]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const normalize=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const visible=people.filter(p=>normalize(`${p.name} ${p.id} ${p.base}`).includes(normalize(search)));
 return <div className="space-y-3">{titleField?<label className="block text-sm">Assunto (opcional)<input className={field} value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label>:<p className="text-xs text-slate-600">Os novos participantes poderão ler o histórico desta conversa. Em atividades, os avisos em Designações seguem as permissões de trabalho de cada participante.</p>}<input aria-label="Buscar participantes" className={field} placeholder="Qualquer funcionário: nome, matrícula ou base" value={search} onChange={e=>setSearch(e.target.value)}/><p className="text-xs">{selected.length} selecionado(s)</p><div className="max-h-64 space-y-2 overflow-y-auto">{visible.map(p=><label key={p.id} className="flex cursor-pointer items-center gap-3 rounded-lg border p-2 text-sm"><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(ids=>ids.includes(p.id)?ids.filter(id=>id!==p.id):[...ids,p.id])}/><span>{p.name} · {p.id}<small className="block text-slate-500">{p.base}</small></span></label>)}</div>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}<div className="flex justify-end gap-2"><button disabled={busy} className="rounded-lg border px-3 py-2 text-sm" onClick={onCancel}>Cancelar</button><button disabled={busy||!selected.length} className="rounded-lg bg-blue-700 px-3 py-2 text-sm text-white disabled:opacity-40" onClick={async()=>{setBusy(true);setError("");try{await onSubmit(selected,title);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?"Salvando…":submitLabel}</button></div></div>;
}

function ChatThread({id,client,user,directory,people,onBack,onRead,onOpenActivity}:{onOpenActivity:(id:string)=>void;id:string;client:SupabaseClient;user:string;directory:UserDirectory;people:Person[];onBack:()=>void;onRead:()=>Promise<void>}){
 const [detail,setDetail]=useState<Detail|null>(null),[messages,setMessages]=useState<Message[]>([]),[body,setBody]=useState(""),[files,setFiles]=useState<File[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[inviting,setInviting]=useState(false),[membersOpen,setMembersOpen]=useState(false),[more,setMore]=useState(false),[olderBusy,setOlderBusy]=useState(false),[retryPending,setRetryPending]=useState(false);
 const panel=useRef<HTMLDivElement>(null),bottom=useRef(true),initial=useRef(true),active=useRef(true),readId=useRef(0);
 const attempt=useRef<{requestId:string;body:string;files:File[];attachments:RecordMedia[]}|null>(null);
 const load=useCallback(async()=>{try{const data=await call<Detail>(client,"messages",{id});if(!active.current)return;setDetail(data);setMessages(previous=>[...new Map([...previous,...data.messages].map(m=>[m.id,m])).values()].sort((a,b)=>a.id-b.id));if(initial.current){setMore(data.messages.length===50);initial.current=false;}const last=data.messages.at(-1)?.id||0;if(bottom.current){requestAnimationFrame(()=>{if(panel.current)panel.current.scrollTop=panel.current.scrollHeight;});if(document.visibilityState==="visible"&&last>readId.current){await call(client,"read",{id,messageId:last});readId.current=last;await onRead();}}}catch(e){if(active.current)setError((e as Error).message);}},[client,id,onRead]);
 useEffect(()=>{active.current=true;const first=setTimeout(()=>void load(),0);const t=setInterval(()=>{if(document.visibilityState==="visible")void load();},3000);return()=>{active.current=false;clearTimeout(first);clearInterval(t);};},[load]);
 async function send(){if(busy||(!body.trim()&&!files.length))return;setBusy(true);setRetryPending(true);setError("");try{const a=attempt.current??(attempt.current={requestId:crypto.randomUUID(),body:body.trim(),files:[...files],attachments:[]});const {data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Entre novamente para enviar.");for(let i=a.attachments.length;i<a.files.length;i++){const file=a.files[i],format=mediaFormat(file),mid=crypto.randomUUID(),path=`${id}/${data.user.id}/${mid}.${file.name.split('.').pop()}`;const{error}=await client.storage.from("internal-chat").upload(path,file,{contentType:format.contentType,upsert:false});if(error)throw new Error(error.message);a.attachments.push({id:mid,name:file.name,type:format.type,url:path,bucket:"internal-chat"});}await call(client,"send",{id,requestId:a.requestId,body:a.body,attachments:a.attachments});attempt.current=null;setRetryPending(false);setBody("");setFiles([]);bottom.current=true;await load();await onRead();}catch(e){setError((e as Error).message+" Use Enviar para tentar novamente com a mesma mensagem.");}finally{setBusy(false);}}
 const pending=busy||retryPending;
 return <div className="flex min-h-0 min-w-0 flex-1 flex-col"><header className="shrink-0 border-b p-3"><div className="flex items-center gap-2"><button aria-label="Voltar às conversas" onClick={onBack} className="p-2"><ArrowLeft size={18}/></button><ChatAvatar members={detail?.members||[]} user={user} directory={directory}/><h3 className="min-w-0 flex-1 truncate text-sm font-bold">{detail?conversationName(detail.conversation,detail.members,user):"Carregando…"}</h3><button aria-label="Adicionar participantes" onClick={()=>setInviting(v=>!v)} className="rounded-lg bg-blue-50 p-2 text-blue-700"><UserPlus size={18}/></button></div><button onClick={()=>setMembersOpen(v=>!v)} aria-expanded={membersOpen} className="mt-1 text-xs text-blue-700">{detail?.members.length||0} participantes</button>{membersOpen?<div className="mt-2 max-h-28 overflow-auto text-xs">{detail?.members.map(m=><p key={m.id}>{m.name} · {m.id} — incluído em {new Date(m.joinedAt).toLocaleString('pt-BR')}</p>)}</div>:null}{detail?.conversation.record_id?<RecordConversation recordId={detail.conversation.record_id} client={client} insideChat/>:null}{detail?.conversation.post_id?<div className="mt-1"><button className="text-xs font-bold text-blue-700" onClick={()=>onOpenActivity(detail.conversation.post_id!)}>Abrir atividade</button><p className="text-[11px] text-slate-500">O resultado técnico continua sendo registrado na atividade.</p></div>:null}</header>
 {inviting?<div className="min-h-0 flex-1 overflow-y-auto p-3"><PeopleForm people={people.filter(p=>!detail?.members.some(m=>m.id===p.id))} submitLabel="Adicionar participantes" onCancel={()=>setInviting(false)} onSubmit={async(members)=>{await call(client,"invite",{id,members});setInviting(false);await load();await onRead();}}/></div>:<><div ref={panel} aria-label="Histórico da conversa" onScroll={()=>{if(panel.current)bottom.current=panel.current.scrollHeight-panel.current.scrollTop-panel.current.clientHeight<50;}} className="min-h-0 flex-1 space-y-3 overflow-y-auto bg-[#efeae2] p-4 sm:px-8">{more?<button disabled={olderBusy} className="w-full text-xs text-blue-700" onClick={async()=>{setOlderBusy(true);try{const beforeHeight=panel.current?.scrollHeight||0;const d=await call<Detail>(client,"messages",{id,before:messages[0]?.id});setMore(d.messages.length===50);setMessages(prev=>[...new Map([...d.messages,...prev].map(m=>[m.id,m])).values()].sort((a,b)=>a.id-b.id));requestAnimationFrame(()=>{if(panel.current)panel.current.scrollTop=panel.current.scrollHeight-beforeHeight;});}catch(e){setError((e as Error).message);}finally{setOlderBusy(false);}}}>Carregar mensagens anteriores</button>:null}{messages.map(m=><article key={m.id} className={`w-fit max-w-[90%] rounded-xl p-3 shadow-sm ${m.kind==='members'?'mx-auto bg-white/80 text-xs':m.sender===user?'ml-auto bg-[#d9fdd3]':'mr-auto bg-white'}`}><div className="mb-1 flex items-center gap-2"><UserAvatar employeeNumber={m.sender} directory={directory} size="xs"/><b className="text-xs">{directory[m.sender]?.name||detail?.members.find(p=>p.id===m.sender)?.name||m.sender}</b></div><p className="whitespace-pre-wrap break-words text-sm">{m.body}</p><MediaGallery items={m.attachments} supabase={client}/><p className="mt-2 text-[10px] text-slate-500">Mat. {m.sender} · {new Date(m.created_at).toLocaleString('pt-BR')}{m.sender===user&&m.kind==='message'?<span className="ml-2 inline-flex items-center gap-1" title="Leitura registrada pelos participantes"><CheckCheck size={14} className={detail?.members.some(p=>p.id!==user&&Number(p.lastReadId)>=m.id)?'text-sky-600':'text-slate-400'}/> {detail?.members.filter(p=>p.id!==user&&Number(p.lastReadId)>=m.id).length||0}</span>:null}</p></article>)}</div>
 <div className="shrink-0 border-t bg-[#f0f2f5] p-3">{error?<p role="alert" className="mb-2 text-xs text-red-700">{error}</p>:null}
 {files.length?<div className="mb-2 flex max-h-24 flex-wrap gap-2 overflow-auto">{files.map((file,i)=><span key={i} className="flex max-w-full items-center gap-2 rounded-lg bg-white p-2 text-xs"><span className="truncate">{file.name}</span><button aria-label={`Remover ${file.name}`} disabled={pending} onClick={()=>setFiles(f=>f.filter((_,index)=>i!==index))}><X size={14}/></button></span>)}</div>:null}
 <div className="flex items-end gap-2"><label title="Anexar imagem, vídeo ou áudio" className="grid h-11 w-11 shrink-0 cursor-pointer place-items-center rounded-full text-slate-600 hover:bg-white"><Paperclip size={23}/><input aria-label="Anexar mídia" className="sr-only" disabled={pending} type="file" multiple accept="image/*,video/*,audio/*,.m4a,.mp3,.mp4,.mov,.wav,.ogg,.opus" onChange={e=>{try{const next=Array.from(e.target.files||[]);if(files.length+next.length>10)throw Error('Máximo de 10 anexos.');next.forEach(mediaFormat);setFiles(f=>[...f,...next]);setError('');}catch(err){setError((err as Error).message);}e.target.value='';}}/></label>
 <textarea aria-label="Mensagem" readOnly={pending} rows={1} maxLength={8000} value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&window.matchMedia('(min-width: 640px)').matches){e.preventDefault();void send();}}} placeholder="Digite uma mensagem" className="max-h-28 min-h-11 min-w-0 flex-1 resize-none rounded-2xl border-0 bg-white px-4 py-3 text-sm outline-none"/>
 <button aria-label="Enviar mensagem" disabled={busy||(!body.trim()&&!files.length)} onClick={()=>void send()} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-emerald-700 text-white disabled:opacity-40"><Send size={20}/></button></div></div></>}

 </div>;
}

export function ActivityConversation({postId,client,onOpen}:{postId:string;client:SupabaseClient|null;onOpen:()=>void}){
 const [conversation,setConversation]=useState<Conversation|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;const load=async()=>{if(!client)return;try{const list=await call<Conversation[]>(client,"list");if(active){setConversation(list.find(c=>c.post_id===postId)||null);setError("");}}catch{if(active)setError("Não foi possível carregar o resumo da conversa.");}};void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load();},10000);return()=>{active=false;clearInterval(t);};},[client,postId]);
 return <section className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h3 className="flex items-center gap-2 text-sm font-bold"><MessageCircle size={18}/>Conversa desta atividade</h3><p className="mt-1 text-xs text-slate-600">O histórico permanece vinculado a esta atividade, mesmo após a conclusão.</p>{conversation?<><p className="mt-2 text-sm">{conversation.message_count} mensagem(ns) · {conversation.members.length} participantes</p><p className="mt-1 text-xs text-slate-600">{conversation.participants}</p></>:<p className="mt-2 text-xs">Abra para consultar ou iniciar a conversa com os envolvidos. O acesso ao histórico é dos participantes.</p>}{error?<p role="alert" className="text-xs text-red-700">{error}</p>:null}<button onClick={onOpen} className="mt-3 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">{conversation?'Abrir conversa':'Conversa da atividade'}</button></section>;
}

type RecordInfo={id:string;prefix:string;title:string;code:string;type:"fault"|"discrepancy"|"inspection"};
type RecordSummary={record:RecordInfo;exists:boolean;member:boolean;conversation:Conversation|null;links:RecordInfo[]};
async function recordCall(client:SupabaseClient,action:string,id:string){const{data,error}=await client.rpc("maintenance_chat",{p_action:action,p_record_id:id});if(error)throw Error(error.message);return data as RecordSummary;}
async function openRecordChat(client:SupabaseClient,id:string,members:string[]){const{data,error}=await client.rpc("maintenance_chat",{p_action:"open",p_record_id:id,p_members:members});if(error)throw Error(error.message);return data as {id:string};}
export function requestRecordChat(id:string){window.dispatchEvent(new CustomEvent("flight-ia-chat-record",{detail:id}));}
function openTechnicalRecord(record:RecordInfo){window.dispatchEvent(new CustomEvent("flight-ia-open-record",{detail:record}));}
export function RecordConversation({recordId,client,insideChat=false}:{recordId:string;client:SupabaseClient|null;insideChat?:boolean}){
 const [summary,setSummary]=useState<RecordSummary|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;const load=async()=>{if(!client)return;try{const data=await recordCall(client,"summary",recordId);if(active){setSummary(data);setError("");}}catch(e){if(active)setError((e as Error).message);}};void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load();},10000);return()=>{active=false;clearInterval(t);};},[client,recordId]);
 const label=summary?.record.type==='fault'?'pane':'ocorrência';
 return <section className={`${insideChat?'mt-2 max-h-40 overflow-auto':'my-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3'} text-xs`}>
 {insideChat?<button className="font-bold text-emerald-800" onClick={()=>summary&&openTechnicalRecord(summary.record)}>Abrir {label} · {summary?.record.code}</button>:<><h4 className="font-bold">Conversa desta {label}</h4><p className="my-2 text-slate-600">Histórico próprio desta ocorrência, preservado após o encerramento.</p>{summary?.member?<p>{summary.conversation?.message_count||0} mensagens · {summary.conversation?.unread||0} novas<br/>{summary.conversation?.participants}</p>:null}<button className="mt-2 rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white" onClick={()=>requestRecordChat(recordId)}>{summary?.exists?'Abrir conversa':'Iniciar conversa'}</button>{summary?.exists&&!summary.member?<p className="mt-1">Peça a um participante para incluir você e acessar as mensagens.</p>:null}</>}
 {summary?.links.length?<details className="mt-3" open={!insideChat}><summary className="cursor-pointer font-bold">Ocorrências vinculadas ({summary.links.length})</summary><div className="space-y-2 pt-2">{summary.links.map(link=><div key={link.id} className="rounded-lg border bg-white p-2"><b>{link.prefix} · {link.title}</b><p>{link.code}</p><div className="mt-1 flex gap-3"><button className="font-bold text-blue-700" onClick={()=>openTechnicalRecord(link)}>Abrir ocorrência</button><button className="font-bold text-emerald-700" onClick={()=>requestRecordChat(link.id)}>Abrir conversa</button></div></div>)}</div></details>:null}{error?<p role="alert" className="text-red-700">{error}</p>:null}</section>;
}
