"use client";
import {useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';

type Row={id:string;revision:number;technical_case:Record<string,unknown>};
export function MaintenanceTaskClosure({client,postId,actionId,recordId,revision,onSaved,requireSignature}:{client:SupabaseClient|null;postId?:string;actionId?:string;recordId?:string;revision:number;onSaved:(row:{data:Record<string,unknown>;revision:number})=>void|Promise<void>;requireSignature:(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[record,setRecord]=useState<Row|null>(null),[closeRecord,setCloseRecord]=useState(false),[confirmed,setConfirmed]=useState(false),[aprs,setAprs]=useState(''),[officialId,setOfficialId]=useState(''),[officialClosed,setOfficialClosed]=useState(false);
 const [openedRevision,setOpenedRevision]=useState(revision);
 async function show(){if(!client||busy)return;setBusy(true);setError('');try{
  if(recordId){const {data,error}=await client.from('maintenance_records').select('id,revision,technical_case').eq('id',recordId).single();if(error)throw error;setRecord(data);setOpenedRevision(data.revision);setCloseRecord(true);setConfirmed(false);setReason('');setAprs(data.technical_case.aprsRef||'');setOfficialId(data.technical_case.officialId||'');setOfficialClosed(!!data.technical_case.officialClosed);setOpen(true);return;}
  const {data:post,error:postError}=await client.from('operational_wall_posts').select('data,revision').eq('id',postId).single();if(postError)throw postError;
  setOpenedRevision(post.revision);setRecord(null);setCloseRecord(false);setConfirmed(false);setReason('');
  if(post.data.maintenanceRecordId){const {data,error}=await client.from('maintenance_records').select('id,revision,technical_case').eq('id',post.data.maintenanceRecordId).single();if(error)throw error;setRecord(data);setCloseRecord(data.technical_case.investigation!=='closed');setAprs(data.technical_case.aprsRef||'');setOfficialId(data.technical_case.officialId||'');setOfficialClosed(!!data.technical_case.officialClosed);}
  setOpen(true);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!client||busy||!reason.trim()||(closeRecord&&!confirmed))return;setBusy(true);setError('');try{
  await requireSignature(async()=>{const {data,error}=await client.rpc(recordId?'close_maintenance_record':'close_maintenance_task',recordId?{p_record_id:recordId,p_expected_revision:openedRevision,p_reason:reason,p_closure:{confirmed,aprsRef:aprs,officialId,officialClosed}}:{p_post_id:postId,p_action_id:actionId,p_expected_revision:openedRevision,p_reason:reason,p_closure:closeRecord&&record?{revision:record.revision,confirmed,aprsRef:aprs,officialId,officialClosed}:null});if(error)throw error;if(!data?.data)throw Error('O servidor não confirmou o encerramento.');await onSaved(data);setOpen(false);},'Assinar encerramento da ação');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-2">{!open?<button type="button" disabled={busy} onClick={()=>void show()} className="rounded-lg border border-emerald-600 px-3 py-2 text-xs font-bold text-emerald-800 disabled:opacity-40">{busy?'Carregando…':recordId?'Encerrar relato e registrar disponibilidade':'Encerrar ação'}</button>:<section aria-label="Encerramento da ação" className="space-y-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><p className="text-sm font-bold">Revisão do inspetor ou superior</p><label className="block text-sm">Conclusão do responsável<textarea aria-label="Conclusão do responsável" value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2" rows={2}/></label>{!recordId&&record&&record.technical_case.investigation!=='closed'?<label className="block text-sm"><input type="checkbox" checked={closeRecord} onChange={e=>{setCloseRecord(e.target.checked);setConfirmed(false);}}/> Encerrar também o relato de origem e registrar disponibilidade</label>:null}{closeRecord?<div className="space-y-2"><label className="block text-sm">Referência da APRS confirmada<input aria-label="Referência da APRS confirmada" value={aprs} onChange={e=>setAprs(e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2"/></label><label className="block text-sm">Identificador no eDB, quando aplicável<input aria-label="Identificador no eDB, quando aplicável" value={officialId} onChange={e=>setOfficialId(e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2"/></label>{officialId||record?.technical_case.official==='pending'||['discrepancy','recurrence'].includes(String(record?.technical_case.report))?<label className="block text-sm"><input type="checkbox" checked={officialClosed} onChange={e=>setOfficialClosed(e.target.checked)}/> Conferi o encerramento no eDB</label>:null}<label className="block text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo as referências acima, o encerramento do relato e a disponibilidade</label><p className="text-xs text-slate-600">Outras pendências da aeronave continuam sendo verificadas. As referências devem corresponder aos registros oficiais.</p></div>:<p className="text-xs">Encerra somente esta ação. A situação do relato permanece separada.</p>}<div className="flex flex-wrap gap-2"><button disabled={busy||!reason.trim()||(closeRecord&&(!confirmed||!aprs.trim()))} onClick={()=>void save()} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">{busy?'Salvando…':'Confirmar encerramento'}</button><button disabled={busy} onClick={()=>setOpen(false)} className="rounded-lg border px-3 py-2 text-sm">Cancelar</button></div></section>}{error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}</div>;
}
