"use client";
import {useEffect,useId,useMemo,useState} from 'react';
import {Link2,Search,X} from 'lucide-react';
import {ModalLayer} from './modal-layer';
import {searchOccurrences,type OccurrenceFilters} from '@/lib/occurrence-search';
import type {MaintenanceRecord} from './maintenance-records';

const field='mt-1 min-h-11 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 text-sm text-slate-900';
export function OccurrenceLinkPicker({current,records,onLink,onClose,onSearch}:{current:MaintenanceRecord;records:MaintenanceRecord[];onLink:(record:MaintenanceRecord)=>Promise<boolean>|boolean;onClose:()=>void;onSearch?:(filters:OccurrenceFilters,offset:number)=>Promise<{records:MaintenanceRecord[];hasMore:boolean}>}){
 const titleId=useId();const [filters,setFilters]=useState<OccurrenceFilters>({query:'',prefix:current.prefix,base:'',model:'',status:'',type:'',from:'',until:''});
 const [remote,setRemote]=useState<MaintenanceRecord[]>([]),[hasMore,setHasMore]=useState(false),[searching,setSearching]=useState(false);
 const [expanded,setExpanded]=useState(false),[limit,setLimit]=useState(40),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const update=(patch:Partial<OccurrenceFilters>)=>{setFilters(f=>({...f,...patch}));setLimit(40);if(onSearch){setRemote([]);setHasMore(false);setSearching(true);}};
 const available=[...records,...remote].filter(record=>record.id!==current.id&&!current.links.includes(record.id));
 const bases=[...new Set(available.map(r=>r.base))].sort();const models=[...new Set(available.filter(r=>!filters.base||r.base===filters.base).map(r=>r.model))].sort();
 const results=useMemo(()=>onSearch?remote:searchOccurrences(records,current,filters),[records,current,filters,onSearch,remote]);
 const invalidPeriod=Boolean(filters.from&&filters.until&&filters.from>filters.until);
 useEffect(()=>{if(!onSearch)return;let active=true;const timer=setTimeout(()=>{setSearching(true);setError('');void onSearch(filters,limit-40).then(page=>{if(active){setRemote(previous=>limit===40?page.records:[...previous,...page.records]);setHasMore(page.hasMore);}}).catch(e=>{if(active){setRemote([]);setHasMore(false);setError((e as Error).message);}}).finally(()=>{if(active)setSearching(false);});},250);return()=>{active=false;clearTimeout(timer);};},[filters,limit,onSearch]);
 async function link(record:MaintenanceRecord){if(busy)return;setBusy(true);setError('');try{if(await onLink(record))onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <ModalLayer><div className="fixed inset-0 z-[90] grid place-items-end bg-slate-950/70 p-0 sm:place-items-center sm:p-5" onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();e.stopPropagation();onClose();}}}>
  <section role="dialog" aria-modal="true" aria-labelledby={titleId} className="flex max-h-[94dvh] w-full max-w-4xl flex-col overflow-hidden rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl">
   <header className="flex shrink-0 items-start justify-between gap-3 border-b border-slate-200 bg-white p-4 sm:p-5"><div><h2 id={titleId} className="text-xl font-extrabold text-slate-900">Vincular ocorrência</h2><p className="mt-1 text-sm text-slate-600">Encontre o registro relacionado a {current.prefix}.</p></div><button type="button" disabled={busy} aria-label="Fechar busca de ocorrências" onClick={onClose} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-slate-100"><X size={20}/></button></header>
   <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
    <fieldset disabled={busy} className="space-y-3"><label className="block text-sm font-semibold text-slate-700">Buscar ocorrência<div className="relative"><Search size={18} className="absolute left-3 top-4 text-slate-400"/><input autoFocus maxLength={160} type="search" autoComplete="off" data-lpignore="true" name="occurrence-search" aria-label="Buscar ocorrência" value={filters.query} onChange={e=>update({query:e.target.value})} placeholder="Código, título, palavra do relato ou TC" className={field+' pl-10'}/></div></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Prefixo<input type="search" name="occurrence-prefix-search" autoComplete="off" data-lpignore="true" maxLength={20} aria-label="Prefixo da ocorrência" value={filters.prefix} onChange={e=>update({prefix:e.target.value.toUpperCase()})} placeholder="Ex.: CHT ou PR-CHT" className={field}/></label><label className="text-sm font-semibold">Situação<select aria-label="Situação da ocorrência" value={filters.status} onChange={e=>update({status:e.target.value})} className={field}><option value="">Todas</option><option value="open">Em aberto</option><option value="closed">Encerrada</option></select></label></div>
    <div className="flex flex-wrap items-center justify-between gap-2"><button type="button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)} className="min-h-11 text-sm font-bold text-blue-700">{expanded?'Recolher filtros':'Mais filtros · modelo, base e período'}</button><button type="button" onClick={()=>update({query:'',prefix:'',base:'',model:'',status:'',type:'',from:'',until:''})} className="min-h-11 text-sm text-slate-600">Limpar filtros</button></div>
    {expanded?<div className="grid gap-3 rounded-2xl bg-slate-50 p-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm">Base<select aria-label="Base da ocorrência" value={filters.base} onChange={e=>update({base:e.target.value,model:''})} className={field}><option value="">Todas as bases</option>{bases.map(base=><option key={base}>{base}</option>)}</select></label><label className="text-sm">Modelo<select aria-label="Modelo da ocorrência" value={filters.model} onChange={e=>update({model:e.target.value})} className={field}><option value="">Todos os modelos</option>{models.map(model=><option key={model}>{model}</option>)}</select></label><label className="text-sm">Tipo<select aria-label="Tipo da ocorrência" value={filters.type} onChange={e=>update({type:e.target.value})} className={field}><option value="">Todos</option><option value="fault">Relato técnico</option><option value="discrepancy">Caso técnico</option><option value="inspection">Inspeção programada</option></select></label><label className="text-sm">De<input aria-label="Ocorrências desde" type="date" value={filters.from} max={filters.until||undefined} onChange={e=>update({from:e.target.value})} className={field}/></label><label className="text-sm">Até<input aria-label="Ocorrências até" type="date" value={filters.until} min={filters.from||undefined} onChange={e=>update({until:e.target.value})} className={field}/></label></div>:null}</fieldset>
    <p role="status" className="my-4 text-sm text-slate-600">{searching?'Buscando ocorrências…':invalidPeriod?'Confira o período: a data inicial deve vir antes da final.':`${results.length} ocorrência(s) ${hasMore?'carregada(s)':'encontrada(s)'} · mais recentes primeiro`}</p>
    {error?<p role="alert" className="mb-3 text-sm text-red-700">{error}</p>:null}
    <div className="space-y-3" aria-label="Resultados de ocorrências">{!invalidPeriod&&results.slice(0,limit).map(record=><button type="button" disabled={busy} onClick={()=>void link(record)} key={record.id} className="block w-full rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:border-blue-500 hover:bg-blue-50 focus-visible:outline-blue-500"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-blue-800">{record.prefix} · {record.ticketCode||'Sem código'}</strong><span className={`rounded-full px-2 py-1 text-xs ${record.status==='open'?'bg-amber-50 text-amber-800':'bg-slate-100 text-slate-600'}`}>{record.status==='open'?'Em aberto':'Encerrada'}</span></div><h3 className="mt-2 font-bold text-slate-900">{record.title}</h3><p className="mt-1 line-clamp-2 whitespace-pre-wrap break-words text-sm text-slate-600">{record.description}</p><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>{record.model} · {record.base} · {new Date(record.createdAt).toLocaleString('pt-BR')}</span><span className="inline-flex items-center gap-1 font-bold text-blue-700"><Link2 size={15}/>Vincular</span></div></button>)}</div>
    {!searching&&!error&&!results.length&&!invalidPeriod?<p className="rounded-2xl border border-dashed p-7 text-center text-sm text-slate-600">Nenhuma ocorrência encontrada. Tente outro termo ou amplie os filtros.</p>:null}
    {!invalidPeriod&&(onSearch?hasMore:results.length>limit)?<button type="button" disabled={searching} onClick={()=>setLimit(n=>n+40)} className="mt-3 min-h-11 w-full rounded-xl border text-sm font-bold text-blue-700">Mostrar mais ocorrências</button>:null}
   </div>
  </section>
 </div></ModalLayer>;
}
