'use client';
import {useState} from 'react';
import {durationFromArrival,minutesClock,timeMinutes} from '@/lib/flight-planned-times';
export function PlannedTimesEditor({flight,onSave,onClose}:{flight:{id:string;revision:number;departure:string;duration:number;actualEngineStart?:string|null};onSave:(id:string,revision:number,departure:string,duration:number)=>Promise<boolean>;onClose:()=>void}){
 const [departure,setDeparture]=useState(flight.departure),[duration,setDuration]=useState(minutesClock(flight.duration*60)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const start=flight.actualEngineStart||departure;const arrival=Number.isFinite(timeMinutes(start)+timeMinutes(duration))?minutesClock(timeMinutes(start)+timeMinutes(duration)):'';
 async function save(){if(busy||!Number.isFinite(timeMinutes(departure)+timeMinutes(duration)))return;setBusy(true);setError('');try{if(await onSave(flight.id,flight.revision,departure,timeMinutes(duration)/60))onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section aria-label="Horários previstos" className="space-y-4"><div className="grid gap-3 sm:grid-cols-3">{[{label:'Saída prevista',value:departure,change:setDeparture},{label:'Tempo previsto (HH:MM)',value:duration,change:setDuration},{label:'Pouso previsto',value:arrival,change:(value:string)=>setDuration(Number.isFinite(durationFromArrival(start,value))?minutesClock(durationFromArrival(start,value)*60):'')}].map(field=><label key={field.label} className="text-sm font-bold">{field.label}<input aria-label={field.label} disabled={busy} type="time" value={field.value} onChange={e=>field.change(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>)}</div><p className="text-sm text-slate-600">O pouso previsto acompanha a duração{flight.actualEngineStart?' a partir da decolagem real':''}. Para corrigir horários realizados, use Eventos da operação.</p>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}<div className="flex justify-end gap-2"><button disabled={busy} onClick={onClose} className="rounded-xl border px-4 py-2">Cancelar</button><button disabled={busy||!Number.isFinite(timeMinutes(departure)+timeMinutes(duration))} onClick={()=>void save()} className="rounded-xl bg-blue-700 px-4 py-2 font-bold text-white">{busy?'Salvando…':'Salvar alterações'}</button></div></section>;
}
