"use client";
import {technicalCardBorder,initialTechnicalCase,reportTypes} from "@/lib/technical-case";
import {useState} from "react";
import type {MaintenanceRecord} from "./maintenance-records";
import {AssignmentPicker,type Person} from "./action-fields";
import {UserAvatar,type UserDirectory} from "./user-avatar";
export type PlanningAction="assign"|"exclude"|"execute"|"tc"|"acknowledge";
export function TcField({value,onChange,disabled=false}:{value:string;onChange:(v:string)=>void;disabled?:boolean}){
 return <div className="flex flex-wrap items-center gap-2"><label className="min-w-0 flex-1 text-sm font-semibold">TC / WO Task<input aria-label="TC / WO Task" disabled={disabled} className="mt-1 w-full rounded-lg border bg-white p-2 text-slate-900" placeholder="Número da TC" value={value} onChange={e=>onChange(e.target.value)}/></label><label className="mt-5 flex items-center gap-1 text-sm"><input type="checkbox" disabled={disabled} checked={value==="N/A"} onChange={e=>onChange(e.target.checked?"N/A":"")}/>N/A</label></div>;
}
export function ServicePlanning({items,people,directory,canManage,canExecute,onOpen,onAction}:{items:MaintenanceRecord[];people:Person[];directory:UserDirectory;canManage:boolean;canExecute:boolean;onOpen:(item:MaintenanceRecord)=>void;onAction:(items:MaintenanceRecord[],action:PlanningAction,assigned:string[],text:string)=>Promise<void>}){
 const[selected,setSelected]=useState<string[]>([]),[action,setAction]=useState<PlanningAction|null>(null),[assigned,setAssigned]=useState<string[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const picked=items.filter(i=>selected.includes(i.id));
 async function submit(){if(!action||!picked.length)return;setBusy(true);setError("");try{await onAction(picked,action,assigned,text);setSelected([]);setAction(null);setText("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="mt-4 space-y-3">{picked.length?<section className="sticky top-2 z-20 rounded-xl border bg-white p-3 shadow-md"><div className="flex flex-wrap items-center gap-2"><strong>{picked.length} selecionados</strong><button onClick={()=>setAction("acknowledge")} className="rounded-lg border px-3 py-2">Ciente</button>{canManage?<><button onClick={()=>{setAction("exclude");setText("");}} className="rounded-lg border px-3 py-2 text-red-700">Excluir do planejamento</button><button onClick={()=>setAction("assign")} className="rounded-lg border px-3 py-2">Designar</button></>:null}{canExecute?<button onClick={()=>{setAction("execute");setText("");}} className="rounded-lg bg-green-700 px-3 py-2 text-white">Dar OK</button>:null}<button onClick={()=>{setSelected([]);setAction(null);}}>Limpar seleção</button></div>{action?<div className="mt-3 space-y-2">{action==="acknowledge"?<p className="text-sm">Registrar sua ciência. Pendências continuam na passagem; concluídos ficam no seu histórico até uma nova intervenção.</p>:action==="assign"?<AssignmentPicker expanded people={people.filter(p=>picked.every(i=>i.base===p.assignedBase))} value={assigned} onChange={setAssigned}/>:action==="execute"?<><p className="text-sm">Confirme somente o que foi executado em todos os itens selecionados. O encerramento técnico pelo inspetor permanece separado.</p><textarea aria-label="Execução em lote" placeholder="Descreva o que foi executado" className="w-full rounded-lg border p-2" value={text} onChange={e=>setText(e.target.value)}/></>:action==="tc"?<TcField value={text} onChange={setText}/>:<p className="text-sm">Excluir {picked.length} itens do planejamento, sem reagendamento automático. Os registros e as ações vinculadas serão preservados.</p>}<button disabled={busy||(action==="execute"&&!text.trim())||(action==="assign"&&!assigned.length)} onClick={()=>void submit()} className="rounded-lg bg-blue-700 px-3 py-2 text-white disabled:opacity-40">{busy?"Salvando…":"Confirmar"}</button><button className="ml-3" onClick={()=>setAction(null)}>Cancelar</button></div>:null}{error?<p role="alert" className="text-red-700">{error}</p>:null}</section>:null}{[...items].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)).map(item=>{
 const latest=[...item.entries].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))[0];
 const shift=item.lastWorkShift||latest?.workShift||item.originShift||people.find(p=>p.employeeNumber===(latest?.employeeNumber||item.createdBy))?.workShift;
 const night=shift==="night";
 return <article key={item.id} className={`rounded-2xl border-t-4 p-3 shadow-sm ${item.recordType!=="inspection"?technicalCardBorder(item.technicalCase||initialTechnicalCase()):latest?.result==="satisfactory"?"border-emerald-500":latest?.result==="nonconforming"?"border-red-500":"border-amber-400"}`} style={{backgroundColor:night?"#e5ecf3":"#ffffff",color:"#17324d"}}><div className="flex items-start gap-3">{<input type="checkbox" aria-label={`Selecionar ${item.title}`} className="mt-1 h-5 w-5 shrink-0" checked={selected.includes(item.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/> }<div className="grid min-w-0 flex-1 gap-x-5 gap-y-2 md:grid-cols-[minmax(0,1fr)_minmax(220px,32%)]"><button onClick={()=>onOpen(item)} className="min-w-0 text-left"><div className="flex flex-wrap items-center gap-2"><strong className="font-mono">{item.prefix}</strong><span className="hidden md:inline rounded bg-white/70 px-2 py-0.5 text-xs">{item.status==="closed"?"Encerrado":item.planningState==="completed"?"Execução OK":"Em aberto"}</span><span className="hidden text-xs md:inline">{item.recordType==="inspection"?"Programada":reportTypes[item.technicalCase?.report||"report"]}</span>{item.planningState==="excluded"?<span className="hidden text-xs md:inline">Excluído do planejamento</span>:null}</div><h3 className="mt-1 line-clamp-1 font-extrabold">{item.title}</h3>{item.description!==item.title?<p className="mt-1 line-clamp-2 whitespace-pre-wrap text-sm">{item.description}</p>:null}{latest?.kind==="action"?<p className="mt-1 hidden line-clamp-2 text-sm md:block">Última execução: {latest.description}</p>:null}</button><div className="hidden min-w-0 space-y-1 text-xs md:block"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">TC: {item.tc||"não informada"}</strong>{canManage||canExecute?<button className="rounded border px-2 py-0.5" onClick={()=>{setSelected([item.id]);setAction("tc");setText(item.tc);}}>Editar TC</button>:null}</div><p className="line-clamp-2 font-semibold">Designado: {item.assignedTo.length?item.assignedTo.map(id=>directory[id]?.name||people.find(p=>p.employeeNumber===id)?.displayName||id).join(", "):"Ainda não designado"}</p><p>{night?"Noturno":shift==="day"?"Diurno":"Turno não informado"} · {new Date(item.updatedAt).toLocaleString("pt-BR")}</p><div className="flex flex-wrap items-center gap-1 opacity-80"><UserAvatar employeeNumber={item.lastUpdatedBy||latest?.employeeNumber||item.createdBy} directory={directory} size="xs"/><span>{directory[item.lastUpdatedBy||latest?.employeeNumber||item.createdBy]?.name||people.find(p=>p.employeeNumber===(item.lastUpdatedBy||latest?.employeeNumber||item.createdBy))?.displayName||item.createdBy}</span><span>{(item.lastMission||latest?.mission||item.originMission||"").replace("mission_","Missão ")}</span></div><p className="truncate opacity-70">{item.ticketCode}</p></div></div></div></article>;
 })}{!items.length?<p className="rounded-xl border border-dashed bg-white p-8 text-center">Nenhum serviço corresponde aos filtros.</p>:null}</div>;
}
