"use client";
import {useState} from "react";
import type {SupabaseClient} from "@supabase/supabase-js";
import {FileAttachmentPicker,pastedFiles} from "./file-attachment-picker";
import {prepareAssistantFiles,removeAssistantFiles,assistantFileAccept} from "@/lib/assistant-uploads";
import {parseServiceImportAnswer,type ImportedService} from "@/lib/service-import";
export function ServiceImportAssistant({client,user,disabled,onAdd}:{client:SupabaseClient|null;user:string;disabled:boolean;onAdd:(rows:ImportedService[])=>void}){
 const[message,setMessage]=useState(""),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[reply,setReply]=useState(""),[error,setError]=useState("");
 async function analyze(){if(!client)return;setBusy(true);setError("");let attachments:Awaited<ReturnType<typeof prepareAssistantFiles>>=[];try{attachments=await prepareAssistantFiles(client,files);const{data}=await client.auth.getSession();if(!data.session)throw Error("Entre novamente");const response=await fetch("/api/ai/service-import",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`,"x-employee":user},body:JSON.stringify({message,attachments})});const result=await response.json();if(!response.ok)throw Error(result.error||"Análise indisponível");const answer=parseServiceImportAnswer(result);onAdd(answer.services);setReply([answer.reply,...answer.services.filter(s=>s.notes).map(s=>`${s.prefix||"Prefixo a conferir"}: ${s.notes}`)].join("\n"));setFiles([]);setMessage("");}catch(e){setError((e as Error).message);}finally{await removeAssistantFiles(client,attachments);setBusy(false);}}
 return <details className="rounded-xl border border-blue-200 bg-blue-50 p-3"><summary className="cursor-pointer font-bold">Importar programadas com IA</summary><p className="my-2 text-sm">Cole o mapa ou anexe imagem/PDF. Confira e edite os cards abaixo antes de publicar.</p><textarea aria-label="Mapa de manutenção para IA" className="w-full rounded-lg border bg-white p-3" rows={4} maxLength={16000} value={message} disabled={busy||disabled} onChange={e=>setMessage(e.target.value)} onPaste={e=>{const pasted=pastedFiles(e);if(pasted.length){e.preventDefault();setFiles(current=>[...current,...pasted]);}}}/><FileAttachmentPicker accept={assistantFileAccept} disabled={busy||disabled} onFiles={next=>setFiles(current=>[...current,...next])}/>{files.map((f,i)=><div key={i} className="my-1 text-xs">{f.name}<button disabled={busy} className="ml-2" onClick={()=>setFiles(current=>current.filter((_,n)=>i!==n))}>Remover</button></div>)}<button disabled={busy||disabled||(!message.trim()&&!files.length)} onClick={()=>void analyze()} className="mt-2 rounded-lg bg-blue-700 px-3 py-2 text-white disabled:opacity-40">{busy?"Preparando cards…":"Preparar cards para revisão"}</button>{reply?<p className="mt-2 whitespace-pre-wrap text-sm">{reply}</p>:null}{error?<p role="alert" className="mt-2 text-red-700">{error}</p>:null}</details>;
}
