"use client";
import {useState} from "react";
import {BookOpen,ExternalLink,Search} from "lucide-react";

export type TechnicalSource = {documentId:string;title:string;documentNumber:string;issuer:string;section:string|null;model:string|null;ata:number[];page:number;sourceUrl:string;statusNote:string;library:string;excerpt:string;score:number};

export function TechnicalSourceList({sources}:{sources:TechnicalSource[]}) {
  if (!sources.length) return null;
  return <details className="mt-3 space-y-2" aria-label="Fontes técnicas consultadas"><summary className="cursor-pointer text-xs font-bold text-slate-600">Ver fontes consultadas</summary>{sources.map(source=><article key={`${source.documentId}-${source.page}`} className="rounded-lg border border-blue-100 bg-white p-3 text-xs"><div className="flex flex-wrap items-center gap-1"><strong className="text-slate-800">{source.documentNumber}</strong><span className="rounded bg-blue-50 px-1.5 py-0.5 text-blue-800">{source.library}</span>{source.ata.length?<span>ATA {source.ata.join(", ")}</span>:null}<span>p. {source.page}</span></div><p className="mt-1 text-slate-700">{source.title}{source.section?` · ${source.section}`:""}</p><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 font-bold text-blue-700">Abrir fonte oficial <ExternalLink size={12}/></a></article>)}</details>;
}

export function TechnicalLibrarySearch() {
  const [query,setQuery]=useState("");
  const [results,setResults]=useState<TechnicalSource[]>([]);
  const [stats,setStats]=useState<{documents:number;pages:number;chunks:number}|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  async function search(value=query){const clean=value.trim();if(clean.length<2)return;setQuery(clean);setLoading(true);setError("");try{const response=await fetch("/api/technical-library/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:clean,limit:8})});const data=await response.json();if(!response.ok)throw Error(data.error);setResults(data.results||[]);setStats(data.stats);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  const examples=["HSI oscilando","altímetro travou","óleo no filtro da MGB","risco no prato oscilante"];
  return <section className="border-b bg-[#f7fafc] p-3" aria-label="Biblioteca técnica"><div className="mb-2 flex items-center justify-between"><div><h3 className="flex items-center gap-2 text-sm font-bold text-[#17324d]"><BookOpen size={17}/>Biblioteca técnica</h3><p className="text-[11px] text-slate-500">{stats?`${stats.documents} documentos · ${stats.pages} páginas indexadas`:"Fontes públicas S-92A e FAA"}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold text-amber-900">Demonstração</span></div><form onSubmit={event=>{event.preventDefault();void search();}} className="flex gap-2"><div className="relative min-w-0 flex-1"><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input aria-label="Pesquisar na biblioteca técnica" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ex.: HSI intermitente" className="h-10 w-full rounded-xl border bg-white pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></div><button disabled={loading||query.trim().length<2} className="rounded-xl bg-blue-700 px-4 text-xs font-bold text-white disabled:opacity-40">{loading?"Buscando…":"Pesquisar"}</button></form><div className="mt-2 flex flex-wrap gap-1">{examples.map(example=><button key={example} type="button" onClick={()=>void search(example)} className="rounded-full border bg-white px-2 py-1 text-[10px] text-blue-700">{example}</button>)}</div>{error?<p role="alert" className="mt-2 text-xs text-red-700">{error}</p>:null}{!loading&&query&&results.length===0&&!error?<p className="mt-3 text-xs text-slate-600">Nenhum trecho encontrado. Tente o componente, ATA ou termo em inglês.</p>:null}{results.length?<div className="mt-3 max-h-72 space-y-2 overflow-auto pr-1">{results.map(source=><article key={`${source.documentId}-${source.page}`} className="rounded-xl border bg-white p-3 text-xs shadow-sm"><div className="flex flex-wrap items-center gap-1"><strong>{source.documentNumber}</strong><span className="rounded bg-slate-100 px-1.5 py-0.5">{source.library}</span>{source.ata.length?<span className="text-blue-700">ATA {source.ata.join(", ")}</span>:null}<span>p. {source.page}</span></div><p className="mt-1 font-semibold text-slate-700">{source.title}{source.section?` · ${source.section}`:""}</p><p className="mt-2 line-clamp-4 leading-relaxed text-slate-600">{source.excerpt}</p><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[10px] text-amber-800">Confirmar revisão e aplicabilidade</span><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold text-blue-700">Fonte oficial <ExternalLink size={12}/></a></div></article>)}</div>:null}<p className="mt-2 text-[10px] text-slate-500">Fontes públicas para pesquisa e redação assistida. Procedimentos e liberação exigem publicação vigente e confirmação humana.</p></section>;
}
