"use client";
import {useEffect,useState} from "react";
import type {SupabaseClient} from "@supabase/supabase-js";
import {AlertTriangle,ShieldCheck} from "lucide-react";
import {aircraftStates,initialTechnicalCase,investigationStates,officialStates,permissionLabels,reportHints,reportTypes,technicalDisclaimer,technicalDraftReview,technicalTone,type TechnicalCase} from "@/lib/technical-case";

type Config={data:{permissions?:Record<string,string[]>;cdlEnabled:boolean;procedures:string[];recipients?:string[]};revision:number;canConfigure:boolean;permissions:Record<string,boolean>};
export function TechnicalAxes({value}:{value?:TechnicalCase}){const c=value||initialTechnicalCase();return <div className={`my-2 grid gap-1 rounded-xl border p-2 text-xs sm:grid-cols-2 ${technicalTone(c)}`}><span title={reportHints[c.report]}>◇ Tipo: <b>{reportTypes[c.report]}</b></span><span>▤ Vínculo: <b>{officialStates[c.official]}</b></span><span>✈ Aeronave: <b>{aircraftStates[c.aircraft]}</b></span><span>⌕ Investigação: <b>{investigationStates[c.investigation]}</b></span>{c.cancelledReason?<b className="col-span-full">Cancelado: {c.cancelledReason}</b>:null}{c.critical?<b className="col-span-full flex items-center gap-1"><AlertTriangle size={14}/>Alerta crítico: avaliação formal necessária</b>:null}</div>}
const input="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal disabled:bg-slate-100";
function TextField({label,value,onChange,type="text"}:{label:string;value?:string;onChange:(value:string)=>void;type?:string}){return <label className="block text-xs font-semibold">{label}<input aria-label={label} type={type} className={input} value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function AxisSelect({label,value,options,onChange,disabled=false}:{label:string;value:string;options:Record<string,string>;onChange:(value:string)=>void;disabled?:boolean}){return <label className="block text-xs font-semibold">{label}<select aria-label={label} disabled={disabled} className={input} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
export function TechnicalCasePanel({client,id,revision,value,tc,title,description,onSaved,requireSignature}:{client:SupabaseClient|null;id:string;revision:number;value?:TechnicalCase;tc:string;title:string;description:string;onSaved:()=>void;requireSignature:(action:()=>void|Promise<void>,label?:string)=>Promise<boolean>}){
 const [draft,setDraft]=useState<TechnicalCase>(value||initialTechnicalCase()),[cfg,setCfg]=useState<Config|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[history,setHistory]=useState<Array<{id:number;event:string;at:string;employee_number:string;actor_role:string;reason:string;old_value:unknown;new_value:unknown}>|null>(null),[recordTitle,setTitle]=useState(title),[recordText,setText]=useState(description),[order,setOrder]=useState(tc),[recurrence,setRecurrence]=useState("");
 useEffect(()=>{let active=true;if(client)void client.rpc("technical_case_action",{p_action:"config"}).then(({data,error})=>{if(active){if(error)setError(error.message);else setCfg(data);}});return()=>{active=false;};},[client]);
 const field=(key:string,text:string)=>setDraft(c=>({...c,[key]:text}));
 const nested=(key:"disposition"|"document"|"action",name:string,text:string)=>setDraft(c=>({...c,[key]:{...c[key],[name]:text}}));
 async function save(action="update"){if(!client||busy)return;setBusy(true);setError("");try{await requireSignature(async()=>{const payload=action==="recurrence"?{revision,description:recurrence}:{revision,case:draft,tc:order,title:recordTitle,description:recordText};const {data,error}=await client.rpc("technical_case_action",{p_action:action,p_id:id,p_payload:payload});if(error)throw Error(error.message);if(action==="recurrence"){setRecurrence("");setError(`Recorrência criada: ${data.id}. O caso original foi preservado.`);}onSaved();},"Confirmar registro técnico e autoria");}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
 const d=draft.disposition||{},doc=draft.document||{},act=draft.action||{};
 return <section className="space-y-3 rounded-xl border border-slate-200 p-3"><TechnicalAxes value={value}/>{value?.notApplicableBy?<p className="text-xs">Não aplicável confirmado por {String(value.notApplicableName||value.notApplicableBy)} · {new Date(value.notApplicableAt||"").toLocaleString("pt-BR")}</p>:null}{value?.aprsBy?<p className="text-xs">APRS: {value.aprsRef} · {String(value.aprsName||value.aprsBy)} · {new Date(value.aprsAt||"").toLocaleString("pt-BR")}</p>:null}<details><summary className="cursor-pointer font-bold">Acompanhamento técnico · atualizar</summary><p className="my-2 text-xs text-slate-600">Registra decisões dos profissionais autorizados. Não emite APRS, não autoriza voo e não substitui eDB, TC/OS ou MEL.</p><div className="grid gap-3 sm:grid-cols-2">
 <AxisSelect label="Tipo do Relato" value={draft.report} options={reportTypes} disabled={!cfg?.permissions.classify} onChange={v=>field("report",v)}/><AxisSelect label="Vínculo Oficial" value={draft.official} options={officialStates} onChange={v=>field("official",v)}/><AxisSelect label="Situação da Aeronave" value={draft.aircraft} options={aircraftStates} onChange={v=>field("aircraft",v)}/><AxisSelect label="Estágio da Investigação" value={draft.investigation} options={investigationStates} onChange={v=>field("investigation",v)}/>
 <TextField label="Identificador da discrepância no eDB" value={draft.officialId} onChange={v=>field("officialId",v)}/><TextField label="TC / Ordem de Serviço" value={order} onChange={setOrder}/>
 {draft.official==="not_applicable"?<TextField label="Justificativa de não aplicabilidade (autorização exigida)" value={draft.notApplicableReason} onChange={v=>field("notApplicableReason",v)}/>:null}
 <label className="self-center text-sm"><input type="checkbox" disabled={!cfg?.permissions.aprs} checked={!!draft.confirmAprs} onChange={e=>setDraft(c=>({...c,confirmAprs:e.target.checked}))}/> Confirmar APRS nesta atualização</label><TextField label="Referência da APRS confirmada (autorização exigida)" value={draft.aprsRef} onChange={v=>field("aprsRef",v)}/><label className="self-center text-sm"><input type="checkbox" disabled={!cfg?.permissions.aprs} checked={!!draft.officialClosed} onChange={e=>setDraft(c=>({...c,officialClosed:e.target.checked}))}/> Discrepância encerrada no eDB</label>
 </div><details className="my-3 rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer font-semibold">Disposição / diferimento</summary><div className="mt-2 grid gap-3 sm:grid-cols-2"><AxisSelect label="Tipo de disposição" value={d.type||"none"} options={{none:"Não aplicável",MEL:"MEL",...(cfg?.data.cdlEnabled?{CDL:"CDL"}:{}),procedure:"Outro procedimento aprovado"}} disabled={!cfg?.permissions.defer} onChange={v=>nested("disposition","type",v)}/>{d.type==="procedure"?<AxisSelect label="Procedimento previamente cadastrado" value={d.reference||""} options={{"":"Selecione",...Object.fromEntries((cfg?.data.procedures||[]).map(p=>[p,p]))}} onChange={v=>nested("disposition","reference",v)}/>:<TextField label="Referência da autorização" value={d.reference} onChange={v=>nested("disposition","reference",v)}/>}
 {d.type==="MEL"?[['melItem','Item MEL'],['revision','Revisão MEL'],['category','Categoria / prazo (ou não aplicável justificado)'],['maintenanceProcedures','Procedimentos de manutenção'],['operationalProcedures','Procedimentos operacionais'],['weather','Restrições meteorológicas (ou não aplicável justificado)']].map(([k,l])=><TextField key={k} label={l} value={d[k]} onChange={v=>nested("disposition",k,v)}/>):null}
 {d.type==="CDL"?[['cdlItem','Item CDL'],['revision','Revisão CDL'],['performance','Limitações / penalidades de desempenho CDL']].map(([k,l])=><TextField key={k} label={l} value={d[k]} onChange={v=>nested("disposition",k,v)}/>):null}
 <TextField label="Condições e restrições" value={d.conditions} onChange={v=>nested("disposition","conditions",v)}/><TextField label="Data limite (horário deste aparelho)" type="datetime-local" value={d.deadline?new Date(new Date(d.deadline).getTime()-new Date(d.deadline).getTimezoneOffset()*60000).toISOString().slice(0,16):""} onChange={v=>nested("disposition","deadline",v?new Date(v).toISOString():"")}/><TextField label="Correção programada" value={d.correction} onChange={v=>nested("disposition","correction",v)}/></div><label className="mt-3 block text-sm"><input type="checkbox" disabled={!cfg?.permissions.defer} checked={!!draft.confirmDisposition} onChange={e=>setDraft(c=>({...c,confirmDisposition:e.target.checked}))}/> Confirmar disposição nesta atualização</label><p className="mt-2 text-xs">O responsável e o horário são registrados pelo servidor. Alerta de prazo aos destinatários configurados a partir de 24 horas antes.</p></details>
 <details className="my-3 rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Componente, ação, testes e documento consultado</summary><div className="mt-2 grid gap-3 sm:grid-cols-2">{[['component','Componente'],['position','Posição (LH/RH)'],['performed','Ação realizada'],['test','Teste executado'],['measurement','Medição'],['limit','Limite'],['result','Resultado observado']].map(([k,l])=><TextField key={k} label={l} value={act[k]} onChange={v=>nested("action",k,v)}/>)}{[['manufacturer','Fabricante'],['model','Modelo'],['registration','Matrícula'],['serial','Número de série'],['ata','ATA'],['document','Documento'],['task','Capítulo / tarefa'],['revision','Revisão'],['effectivity','Efetividade'],['consultedAt','Data de consulta']].map(([k,l])=><TextField key={k} label={l} value={doc[k]} onChange={v=>nested("document",k,v)}/>)}</div><p className="mt-2 text-xs">Referências informadas pelo profissional. Nenhum AMM/FIM é presumido pelo aplicativo.</p></details>
 <details className="my-3 rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Corrigir texto confirmado</summary><TextField label="Título" value={recordTitle} onChange={setTitle}/><label className="block text-xs">Descrição<textarea className={input} value={recordText} rows={4} onChange={e=>setText(e.target.value)}/></label><p className="text-xs">A versão anterior, autoria e justificativa permanecerão na auditoria.</p></details>
 {value?.critical?<TextField label="Avaliação formal do alerta crítico (responsável autorizado)" value={draft.criticalReview} onChange={v=>field("criticalReview",v)}/>:null}
 <TextField label="Justificativa da alteração / confirmação" value={draft.reason} onChange={v=>field("reason",v)}/><button disabled={busy||!cfg} onClick={()=>void save()} className="mt-3 rounded-lg bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-40">Confirmar atualização</button>
 {cfg?.permissions.close?<details className="mt-3"><summary>Cancelamento com histórico</summary><TextField label="Motivo do cancelamento (não apaga o caso)" value={draft.cancelledReason} onChange={v=>field("cancelledReason",v)}/></details>:null}
 </details><details><summary className="cursor-pointer text-sm font-bold">Sintoma reapareceu · criar recorrência</summary><textarea aria-label="Descrição da recorrência" className={input} rows={3} value={recurrence} onChange={e=>setRecurrence(e.target.value)}/><button disabled={busy||!recurrence.trim()} onClick={()=>void save("recurrence")} className="mt-2 rounded-lg border px-3 py-2">Criar novo relato vinculado</button></details>
 <button className="flex items-center gap-2 text-sm text-blue-700" onClick={async()=>{if(!client)return;const {data,error}=await client.rpc("technical_case_action",{p_action:"history",p_id:id});if(error)setError(error.message);else setHistory(data);}}><ShieldCheck size={16}/>Consultar auditoria</button>{history?<div className="max-h-80 space-y-2 overflow-auto">{history.map(h=><details key={h.id} className="rounded-lg border p-2 text-xs"><summary>{h.event} · {h.employee_number||"Migração"} · {new Date(h.at).toLocaleString("pt-BR")}</summary><p>{h.actor_role} · {h.reason}</p><pre className="whitespace-pre-wrap break-all">{JSON.stringify({anterior:h.old_value,novo:h.new_value},null,2)}</pre></details>)}</div>:null}{error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}<p className="text-xs text-slate-500">{technicalDisclaimer}</p></section>;
}

export function TechnicalOperatorSettings({client}:{client:SupabaseClient|null}){
 const [cfg,setCfg]=useState<Config|null>(null),[error,setError]=useState(""),[reason,setReason]=useState("");
 useEffect(()=>{let active=true;if(client)void client.rpc("technical_case_action",{p_action:"config"}).then(({data,error})=>{if(active){if(error)setError(error.message);else setCfg(data);}});return()=>{active=false;};},[client]);
 if(!cfg?.canConfigure)return null;
 const list=(s:string)=>s.split(/[,\n]/).map(s=>s.trim());
 return <details className="my-3 rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">Autorizações do acompanhamento técnico</summary><p className="my-2 text-sm">Cadastre as matrículas autorizadas pelo operador, separadas por vírgulas. O cargo e o acesso de administrador não conferem automaticamente autorização técnica.</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(permissionLabels).map(([k,l])=><TextField key={k} label={l} value={cfg.data.permissions?.[k]?.join(", ")} onChange={v=>setCfg({...cfg,data:{...cfg.data,permissions:{...cfg.data.permissions,[k]:list(v)}}})}/>)}</div><label className="my-3 block"><input type="checkbox" checked={cfg.data.cdlEnabled} onChange={e=>setCfg({...cfg,data:{...cfg.data,cdlEnabled:e.target.checked}})}/> Operador utiliza CDL</label><TextField label="Referências de outros procedimentos aprovados (separadas por vírgula)" value={cfg.data.procedures.join(", ")} onChange={v=>setCfg({...cfg,data:{...cfg.data,procedures:list(v)}})}/><TextField label="Matrículas destinatárias dos alertas críticos e de vencimento" value={cfg.data.recipients?.join(", ")} onChange={v=>setCfg({...cfg,data:{...cfg.data,recipients:list(v)}})}/><TextField label="Motivo e referência da autorização do operador" value={reason} onChange={setReason}/><button disabled={!reason.trim()} className="mt-3 rounded-lg bg-blue-700 px-4 py-2 text-white disabled:opacity-40" onClick={async()=>{if(!client)return;const {data,error}=await client.rpc("technical_case_action",{p_action:"configure",p_payload:{revision:cfg.revision,data:{...cfg.data,permissions:Object.fromEntries(Object.entries(cfg.data.permissions||{}).map(([k,v])=>[k,v.filter(Boolean)])),procedures:cfg.data.procedures.filter(Boolean),recipients:cfg.data.recipients?.filter(Boolean)},reason}});if(error)setError(error.message);else {setCfg(data);setError("Configuração salva e auditada.");}}}>Salvar autorizações</button>{error?<p role="status">{error}</p>:null}</details>;
}
export function TechnicalDraftReview({text,role="mechanic"}:{text:string;role?:"pilot"|"mechanic"}){const [open,setOpen]=useState(false);const r=technicalDraftReview(text,role);return <div className="my-2"><button type="button" onClick={()=>setOpen(!open)} className="text-xs font-bold text-blue-700">Revisar clareza do relato (opcional)</button>{open?<div className="rounded-lg bg-blue-50 p-3 text-xs"><p>Preparação para assistência de IA · confirmação humana</p><ul className="my-2 list-inside list-disc">{r.questions.map(q=><li key={q}>{q}</li>)}</ul><p>{r.notice}</p>{r.critical?<p className="mt-2 font-bold text-red-800">Alerta crítico. O relato pode ser salvo. Uma liberação incompatível exigirá avaliação e disposição formal.</p>:null}</div>:null}</div>}

export function AircraftTechnicalStatus({client,prefix}:{client:SupabaseClient|null;prefix:string}){
 const [summary,setSummary]=useState<{total:number;attention:number;deferred:number;monitoring:number}|null>(null);
 useEffect(()=>{let live=true;async function load(){if(!client)return;const {data,error}=await client.rpc("technical_aircraft_summary",{p_prefix:prefix});if(live&&!error)setSummary(data);}void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer);};},[client,prefix]);
 if(!summary?.total)return null;
 return <p className={`rounded-lg border p-2 text-xs ${summary.attention?"border-amber-200 bg-amber-50 text-amber-900":"border-slate-200 bg-slate-50 text-slate-700"}`}>Acompanhamento técnico: {summary.attention?`${summary.attention} caso(s) exigem avaliação`:summary.deferred?`${summary.deferred} caso(s) com diferimento`:summary.monitoring?"Monitoramento pós-APRS":"Consultar registros oficiais"}. A condição de despacho deve ser conferida nos registros oficiais.</p>;
}
export function TechnicalAlerts({client}:{client:SupabaseClient|null}){
 const [alerts,setAlerts]=useState<Array<{id:number;record_id:string;message:string;at:string}>>([]);
 useEffect(()=>{let live=true;async function load(){if(!client)return;const {data,error}=await client.rpc("technical_case_action",{p_action:"alerts"});if(live&&!error)setAlerts(data||[]);}void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer);};},[client]);
 if(!alerts.length)return null;
 return <details className="my-3 rounded-xl border border-amber-300 bg-amber-50 p-3"><summary className="cursor-pointer text-sm font-bold">Alertas técnicos para você · {alerts.length}</summary>{alerts.map(a=><p key={a.id} className="mt-2 border-t border-amber-200 pt-2 text-sm">{a.message}<small className="block">{new Date(a.at).toLocaleString("pt-BR")}</small></p>)}</details>;
}
