"use client";
import {ToolSilhouette} from "./tool-silhouette";
import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {ModalLayer} from './modal-layer';
import {X,Camera,Wrench,Plus} from 'lucide-react';

export type CatalogTool={id:string;name:string;measure:string;x:number;y:number;reviewed:boolean};
export type Drawer={id:string;name:string;photo:string;reviewed:boolean;tools:CatalogTool[]};
type VisualData={catalog:{drawers:Drawer[];revision:number};loans:{id:string;status:string;employee:string;tools:{id:string}[]}[]};
const field='w-full rounded-xl border border-[#cbd9e7] bg-white p-2 text-sm';
const button='rounded-xl border px-3 py-2 text-sm font-bold disabled:opacity-40';
export async function drawerPhoto(file:File){
 if(!file.type.startsWith('image/'))throw Error('Selecione uma imagem.');
 const image=await createImageBitmap(file);const scale=Math.min(1,1500/Math.max(image.width,image.height));
 const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);image.close();return canvas.toDataURL('image/jpeg',.8);
}
function DrawerImage({drawer,selected,onSelect,onPosition,status}:{drawer:Drawer;selected:string[];onSelect:(t:CatalogTool)=>void;onPosition?:(x:number,y:number)=>void;status?:(id:string)=>string}){
 const simulated=!drawer.photo||(drawer.photo.startsWith("data:image/svg+xml")&&drawer.name.includes("DEMO"));
 if(simulated&&!onPosition)return <div className="rounded-2xl border-4 border-slate-500 bg-[#182c3b] p-3 shadow-inner"><p className="mb-3 text-xs font-bold text-slate-200">{drawer.name} · Simulação</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{drawer.tools.map((tool,index)=><button type="button" key={tool.id} aria-label={`${tool.name} ${tool.measure}`} aria-pressed={selected.includes(tool.id)} style={selected.includes(tool.id)?{borderColor:"#60a5fa",backgroundColor:"#244d6a"}:undefined} onClick={()=>onSelect(tool)} className={`relative flex h-40 items-center justify-center rounded-xl border-2 bg-[#102330] p-3 transition hover:bg-[#294454] sm:h-48 ${selected.includes(tool.id)?"border-blue-400 ring-2 ring-blue-400":status?.(tool.id)?"border-amber-400":"border-[#354d5c]"}`}><span className="absolute left-2 top-2 text-xs font-bold text-white">{index+1}</span><ToolSilhouette name={tool.name}/>{selected.includes(tool.id)?<span className="absolute right-2 top-2 rounded-full bg-blue-500 px-1.5 text-white">✓</span>:null}{status?.(tool.id)?<span className="absolute inset-x-1 bottom-1 rounded bg-amber-300 px-1 text-[9px] font-bold text-amber-950">{status(tool.id)}</span>:null}</button>)}</div></div>;
 return <div className="relative overflow-hidden rounded-2xl border bg-slate-100" onClick={e=>{if(onPosition&&e.target===e.currentTarget.querySelector('img')){const r=e.currentTarget.getBoundingClientRect();onPosition((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100);}}}>
 {drawer.photo?<img src={drawer.photo} alt={drawer.name} className="block w-full"/>:<div className="h-64"/>}
 {drawer.tools.map((t,i)=><button key={t.id} type="button" aria-label={`${t.name} ${t.measure}`} title={`${t.name} ${t.measure} · ${status?.(t.id)||'Disponível'}`} onClick={()=>onSelect(t)} style={{left:`${t.x}%`,top:`${t.y}%`}} className={`absolute grid h-8 w-8 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white text-xs font-black shadow ${selected.includes(t.id)?'bg-blue-700 text-white':status?.(t.id)?.startsWith('Com divergência')?'bg-red-600 text-white':status?.(t.id)?'bg-amber-300 text-amber-950':'bg-white text-emerald-800'}`}>{i+1}</button>)}
 </div>;
}

export function ToolboxVisualManager({supabase,boxId,boxName,requireSignature,onClose}:{supabase:SupabaseClient;boxId:string;boxName:string;requireSignature:(f:()=>void|Promise<void>,label?:string)=>Promise<boolean>;onClose:()=>void}){
 const [drawers,setDrawers]=useState<Drawer[]>([]),[revision,setRevision]=useState(0),[active,setActive]=useState(0),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[drafts,setDrafts]=useState<{id:string;drawer_id:string;created_at:string;result:{photo:string;tools:CatalogTool[]}}[]>([]),[audit,setAudit]=useState<{id:number;action:string;actor:string;at:string;payload:{before?:{name:string;measure?:string;drawer?:string}[];after?:{name:string;measure?:string;drawer?:string}[];from?:string;to?:string;reason?:string;revision?:number}}[]>([]);
 useEffect(()=>{let live=true;void supabase.rpc('get_toolbox_visual',{p_box_id:boxId}).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else{setDrawers(data.catalog.drawers);setRevision(data.catalog.revision);}setLoading(false);});return()=>{live=false;};},[supabase,boxId]);
 const drawer=drawers[active];const tool=drawer?.tools.find(t=>t.id===selected);
 function update(value:Partial<Drawer>){setDrawers(list=>list.map((d,i)=>i===active?{...d,...value}:d));}
 function updateTool(value:Partial<CatalogTool>){if(!drawer)return;update({reviewed:false,tools:drawer.tools.map(t=>t.id===selected?{...t,...value}:t)});}
 async function identify(){if(!drawer?.photo)return;setBusy(true);setError('');try{const {data}=await supabase.auth.getSession();const response=await fetch('/api/toolbox-identify',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token??''}`},body:JSON.stringify({image:drawer.photo,boxId,drawerId:drawer.id})});const payload=await response.json();if(!response.ok)throw Error(payload.error);if(payload.warning)setError(payload.warning);update({reviewed:false,tools:[...drawer.tools,...payload.tools.map((t:Omit<CatalogTool,'id'|'reviewed'>)=>({...t,id:crypto.randomUUID(),reviewed:false}))]});}catch(e){setError(e instanceof Error?e.message:'Não foi possível identificar.');}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await requireSignature(async()=>{const {error}=await supabase.rpc('save_toolbox_visual',{p_box_id:boxId,p_drawers:drawers,p_revision:revision});if(error)throw Error(error.message);setRevision(revision+1);onClose();},'Assinar cadastro das gavetas e ferramentas');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar');}finally{setBusy(false);}}
 return <ModalLayer><div className="fixed inset-0 grid place-items-center bg-slate-950/60 p-3"><section role="dialog" aria-modal="true" aria-label="Cadastro visual da caixa" className="max-h-[94dvh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-4"><header className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{boxName} · Gavetas e ferramentas</h2><button onClick={onClose} aria-label="Fechar"><X/></button></header>{error?<p role="alert" className="my-3 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>:null}{loading?<p>Carregando catálogo…</p>:<>
 <div className="mb-4 flex flex-wrap items-center gap-2"><label className="text-sm">Quantidade de gavetas <input aria-label="Quantidade de gavetas" type="number" min={Math.max(1,drawers.length)} max={30} value={drawers.length||''} onChange={e=>{const n=Math.min(30,Math.max(drawers.length,Number(e.target.value)));setDrawers(list=>[...list,...Array.from({length:n-list.length},(_,i)=>({id:crypto.randomUUID(),name:`Gaveta ${list.length+i+1}`,photo:'',reviewed:false,tools:[]}))]);}} className="ml-2 w-20 rounded-lg border p-2"/></label><button className={button} onClick={async()=>{const {data,error}=await supabase.rpc('get_toolbox_audit',{p_box_id:boxId});if(error)setError(error.message);else setAudit(data);}}>Histórico assinado</button><button className={button} onClick={async()=>{const {data,error}=await supabase.rpc("list_toolbox_identifications",{p_box_id:boxId});if(error)setError(error.message);else setDrafts(data);}}>Rascunhos da identificação</button></div>{drawer&&drafts.length?<div className="mb-3 flex flex-wrap gap-2">{drafts.map(d=><button key={d.id} className={button} onClick={()=>update({photo:d.result.photo,reviewed:false,tools:d.result.tools.map(t=>({...t,id:crypto.randomUUID(),reviewed:false}))})}>Restaurar rascunho de {new Date(d.created_at).toLocaleString("pt-BR")}</button>)}</div>:null}
 <div className="mb-4 flex flex-wrap gap-2">{drawers.map((d,i)=><button className={`${button} ${active===i?'bg-blue-600 text-white':''}`} key={d.id} onClick={()=>{setActive(i);setSelected('');}}>{d.name} {d.reviewed?'✓':'· Rascunho'}</button>)}</div>
 {drawer?<div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="space-y-3"><input aria-label="Nome da gaveta" className={field} value={drawer.name} onChange={e=>update({name:e.target.value,reviewed:false})}/><div className="flex flex-wrap gap-2"><label className={`${button} cursor-pointer`}><Camera className="mr-1 inline" size={16}/>Foto da gaveta<input aria-label="Foto da gaveta" type="file" accept="image/*" capture="environment" className="hidden" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(f)try{update({photo:await drawerPhoto(f),reviewed:false});}catch(e){setError(String(e));}}}/></label><button disabled={!drawer.photo||busy} className={button} onClick={()=>void identify()}>{busy?'Processando…':'Identificar ferramentas na foto'}</button></div><DrawerImage drawer={drawer} selected={[selected]} onSelect={t=>setSelected(t.id)} onPosition={(x,y)=>{if(tool)updateTool({x,y});}}/><p className="text-xs text-slate-500">Selecione uma marcação para editar. Toque na foto para reposicionar a marcação selecionada. Confira nomes e medidas sugeridos.</p></div>
 <div className="space-y-3"><button className={button} onClick={()=>{const id=crypto.randomUUID();update({reviewed:false,tools:[...drawer.tools,{id,name:'Nova ferramenta',measure:'',x:50,y:50,reviewed:false}]});setSelected(id);}}><Plus className="inline" size={16}/>Adicionar ferramenta</button><select aria-label="Editar ferramenta" className={field} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione a marcação</option>{drawer.tools.map((t,i)=><option key={t.id} value={t.id}>{i+1}. {t.name} {t.measure}</option>)}</select>{tool?<div className="space-y-3 rounded-xl bg-slate-50 p-3"><label className="block text-sm">Nome<input className={field} value={tool.name} onChange={e=>updateTool({name:e.target.value,reviewed:false})}/></label><label className="block text-sm">Medida / identificação<input className={field} placeholder="Confirmar medida ou informar não aplicável" value={tool.measure} onChange={e=>updateTool({measure:e.target.value,reviewed:false})}/></label><div className="flex gap-2">{(['x','y'] as const).map(axis=><label key={axis} className="text-xs">Posição {axis.toUpperCase()} (%)<input type="number" min={0} max={100} className={field} value={Math.round(tool[axis])} onChange={e=>updateTool({[axis]:Math.min(100,Math.max(0,Number(e.target.value)))})}/></label>)}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={tool.reviewed} onChange={e=>updateTool({reviewed:e.target.checked})}/>Nome, medida e posição conferidos</label><button className={`${button} text-red-700`} onClick={()=>{update({reviewed:false,tools:drawer.tools.filter(t=>t.id!==selected)});setSelected('');}}>Excluir marcação</button></div>:null}<label className="flex items-center gap-2 rounded-xl bg-blue-50 p-3 text-sm"><input type="checkbox" disabled={!drawer.tools.length||drawer.tools.some(t=>!t.reviewed)} checked={drawer.reviewed} onChange={e=>update({reviewed:e.target.checked})}/>Gaveta conferida e liberada para uso</label><p className="text-xs text-slate-500">{drawer.tools.length} ferramentas · {drawer.tools.filter(t=>t.reviewed).length} conferidas</p></div></div>:<p>Informe a quantidade de gavetas para começar.</p>}
 <button disabled={busy||!drawers.length} onClick={()=>void save()} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-40">Salvar catálogo com assinatura</button>{audit.length?<div className="mt-4 space-y-2">{audit.map(a=><details key={a.id} className="rounded-xl border p-3"><summary>{auditLabel(a.action)} · Mat. {a.actor} · {new Date(a.at).toLocaleString('pt-BR')}</summary><div className="mt-2 text-sm">{a.payload.from?<p>{a.payload.from} → {a.payload.to}</p>:null}{a.payload.reason?<p>Motivo: {a.payload.reason}</p>:null}{a.payload.before?<p>Antes: {a.payload.before.map(t=>`${t.name} ${t.measure??""} · ${t.drawer??""}`).join(", ")}</p>:null}{a.payload.after?<p>Depois: {a.payload.after.map(t=>`${t.name} ${t.measure??""} · ${t.drawer??""}`).join(", ")}</p>:null}{a.payload.revision?<p>Versão conferida: {a.payload.revision}</p>:null}</div></details>)}</div>:null}</>}</section></div></ModalLayer>;
}
const statusLabels:Record<string,string>={awaiting_approval:'Retirada registrada',open:'Emprestada',returned:'Aguardando conferência',divergence:'Com divergência'};
export function auditLabel(action:string){return ({save_visual_catalog:'Catálogo atualizado',release_transfer:'Transferência liberada',receive_transfer:'Transferência recebida',correct_tool_selection:'Seleção corrigida',take_tool:'Retirada registrada',approve_tool_withdrawal:'Retirada confirmada',confirm_tool_return:'Devolução conferida'} as Record<string,string>)[action]??action;}

export function ToolboxPicker({supabase,boxId,selected,onChange,onCatalog,excludeEvent}:{supabase:SupabaseClient;boxId:string;selected:string[];onChange:(ids:string[])=>void;onCatalog?:(exists:boolean)=>void;excludeEvent?:string}){
 const [data,setData]=useState<VisualData|null>(null),[active,setActive]=useState(0),[error,setError]=useState(''),[focus,setFocus]=useState('');
 useEffect(()=>{let live=true;setData(null);setError('');setActive(0);async function load(){const {data,error}=await supabase.rpc('get_toolbox_visual',{p_box_id:boxId});if(!live)return;if(error){setError(error.message);onCatalog?.(true);}else{setData(data);onCatalog?.(data.catalog.drawers.length>0);}}void load();const timer=setInterval(()=>void load(),15000);return()=>{live=false;clearInterval(timer);};},[supabase,boxId,onCatalog]);
 if(error)return <p role="alert" className="text-red-700">{error}</p>;if(!data)return <p>Carregando gavetas…</p>;if(!data.catalog.drawers.length)return <p className="text-xs text-slate-500">Caixa sem catálogo visual. Registre os nomes abaixo.</p>;
 const drawers=data.catalog.drawers,drawer=drawers[active],all=drawers.flatMap(d=>d.tools.map(t=>({...t,drawer:d.name}))),focused=all.find(t=>t.id===focus);
 function status(id:string){const loan=data!.loans.find(l=>l.id!==excludeEvent&&l.tools.some(t=>t.id===id));return loan?`${statusLabels[loan.status]??loan.status} · Mat. ${loan.employee}`:'';}
 function choose(t:CatalogTool){setFocus(t.id);if(!status(t.id)&&!selected.includes(t.id))onChange([...selected,t.id]);}
 return <div className="space-y-3"><div className="flex flex-wrap gap-2">{drawers.map((d,i)=><button type="button" key={d.id} onClick={()=>setActive(i)} className={`${button} ${active===i?'bg-blue-600 text-white':''}`}>{d.name}</button>)}</div>{drawer?.reviewed?<><DrawerImage drawer={drawer} selected={selected} onSelect={choose} status={status}/><div className="grid grid-cols-2 gap-2">{drawer.tools.map((t,i)=><button type="button" key={t.id} onClick={()=>choose(t)} className={`${button} text-left ${selected.includes(t.id)?'bg-blue-50 border-blue-600':''}`}><Wrench className="mr-1 inline" size={14}/>{i+1}. {t.name} {t.measure}<small className="block">{status(t.id)||'Disponível'}</small></button>)}</div></>:<p className="rounded-xl bg-amber-50 p-3 text-sm">Gaveta ainda não conferida. Solicite a revisão ao responsável pelo cadastro.</p>}{focused?<p className="rounded-xl bg-blue-50 p-3 font-bold">{focused.name} · {focused.measure||'Sem medida'} · {focused.drawer}<small className="block">{status(focused.id)}</small></p>:null}
 <div className="space-y-2"><strong className="text-sm">Confira sua seleção ({selected.length})</strong>{selected.map(id=>{const t=all.find(t=>t.id===id);return <div key={id} className="rounded-xl border p-3 text-sm"><strong>{t?.name} {t?.measure}</strong><p>{t?.drawer}</p><div className="mt-2 flex gap-2"><button type="button" className={button} onClick={()=>{onChange(selected.filter(s=>s!==id));setActive(Math.max(0,drawers.findIndex(d=>d.tools.some(t=>t.id===id))));setFocus('');}}>Trocar ferramenta</button><button type="button" className={button} onClick={()=>onChange(selected.filter(s=>s!==id))}>Remover</button></div></div>;})}</div></div>;
}


